import Link from "next/link";
import { AlertTriangle, ArrowRight, CalendarDays, CheckCircle2, GitBranch, ListTodo, Target, Waypoints } from "lucide-react";
import type { TeamMetric, TeamMissionControlState, TeamMemberProfile } from "../models/TeamMissionControlState";

const metricTone: Record<TeamMetric["tone"], string> = {
  blue: "border-blue-200 bg-blue-50/70 text-blue-700", teal: "border-teal-200 bg-teal-50/70 text-teal-700",
  amber: "border-amber-200 bg-amber-50/70 text-amber-800", rose: "border-rose-200 bg-rose-50/70 text-rose-700",
  slate: "border-slate-200 bg-white text-slate-700",
};

function OwnerBadge({ owner, compact = false }: { owner: TeamMemberProfile; compact?: boolean }) {
  return <span data-assigned-consultant={owner.id} className={`inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white font-bold text-slate-600 ${compact ? "px-2 py-1 text-[10px]" : "px-3 py-1.5 text-xs"}`}>
    <span className="flex h-5 w-5 items-center justify-center rounded-full bg-slate-900 text-[8px] font-black text-white">{owner.initials}</span>{owner.name}
  </span>;
}

export function TeamMissionControlPage({ state }: { state: TeamMissionControlState }) {
  return <div data-team-mission-control className="space-y-7 pb-8">
    <section className="overflow-hidden rounded-3xl border border-slate-800 bg-slate-950 text-white shadow-xl">
      <div className="grid gap-8 p-7 lg:grid-cols-[1fr_auto] lg:p-9">
        <div><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-teal-400/10 px-3 py-1 text-xs font-black uppercase tracking-[0.2em] text-teal-300">Team Mission Control</span><span className="text-sm text-slate-400">{state.dateLabel}</span></div>
          <h2 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">{state.teamName}</h2>
          <p className="mt-3 max-w-3xl text-base leading-7 text-slate-300">One operating view of candidate momentum, consultant follow-through, and the decisions that need leadership attention.</p>
          <div className="mt-6 flex flex-wrap items-center gap-3"><OwnerBadge owner={state.viewer} /><span className="text-sm font-semibold text-slate-400">Authorized branch · {state.scopeOptions.length - 2} reporting members</span></div>
        </div>
        <div className="min-w-64 rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${state.health.attentionCount ? "bg-amber-400/10 text-amber-300" : "bg-emerald-400/10 text-emerald-300"}`}>{state.health.attentionCount ? <AlertTriangle size={20} /> : <CheckCircle2 size={20} />}</span><div><p className="text-xs font-black uppercase tracking-widest text-slate-400">Team health</p><p className="mt-1 text-lg font-black">{state.health.label}</p></div></div><p className="mt-4 text-sm leading-6 text-slate-300">{state.health.detail}</p></div>
      </div>
    </section>

    <section aria-label="Team scope" className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
      <div className="flex items-center gap-2"><GitBranch size={17} className="text-blue-600" /><h2 className="text-sm font-black uppercase tracking-[0.16em] text-slate-700">Operating scope</h2><span className="ml-auto hidden text-xs font-semibold text-slate-400 sm:block">Selecting a team leader includes their authorized subtree</span></div>
      <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{state.scopeOptions.map((scope) => <Link key={scope.id} data-team-scope={scope.id} aria-current={scope.id === state.selectedScope.id ? "page" : undefined} href={scope.id === "all" ? "/crm/team" : `/crm/team?scope=${encodeURIComponent(scope.id)}`} className={`shrink-0 rounded-xl border px-4 py-2.5 text-left transition ${scope.id === state.selectedScope.id ? "border-blue-600 bg-blue-600 text-white shadow-sm" : "border-slate-200 bg-slate-50 text-slate-700 hover:border-blue-300"}`} style={{ marginLeft: scope.depth ? `${scope.depth * 8}px` : undefined }}><span className="block text-sm font-black">{scope.label}</span><span className={`block text-[10px] font-semibold ${scope.id === state.selectedScope.id ? "text-blue-100" : "text-slate-400"}`}>{scope.description}</span></Link>)}</div>
    </section>

    {state.scopedMember && <section data-consultant-drilldown className="flex flex-col gap-5 rounded-2xl border border-blue-200 bg-blue-50/60 p-5 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-600 font-black text-white">{state.scopedMember.initials}</span><div><p className="text-xs font-black uppercase tracking-widest text-blue-600">Consultant operating view</p><h2 className="mt-1 text-xl font-black text-slate-950">{state.scopedMember.name} · {state.scopedMember.roleLabel}</h2><p className="mt-1 text-sm text-slate-600">{state.scopedMember.pipelineSummary}</p></div></div><div className="flex gap-5 text-sm"><div><strong className="block text-xl text-slate-950">{state.scopedMember.candidateCount}</strong><span className="text-slate-500">active</span></div><div><strong className="block text-xl text-slate-950">{state.scopedMember.attentionCount}</strong><span className="text-slate-500">attention</span></div><div><strong className="block text-xl text-slate-950">{state.scopedMember.meetingsThisWeek}</strong><span className="text-slate-500">meetings</span></div></div></section>}

    <section aria-label="Executive team metrics" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{state.metrics.map((metric) => <article key={metric.id} data-team-metric={metric.id} className={`rounded-2xl border p-5 ${metricTone[metric.tone]}`}><p className="text-[10px] font-black uppercase tracking-[0.16em] opacity-80">{metric.label}</p><p className="mt-3 text-3xl font-black text-slate-950">{metric.value}</p><p className="mt-1 text-xs font-semibold opacity-75">{metric.detail}</p></article>)}</section>

    <section aria-labelledby="team-members-title"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-blue-600">Leadership span</p><h2 id="team-members-title" className="mt-1 text-2xl font-black text-slate-950">Where the team needs you</h2></div><span className="text-sm font-semibold text-slate-400">{state.members.length} member{state.members.length === 1 ? "" : "s"} in scope</span></div>
      <div className="mt-4 grid gap-3 xl:grid-cols-2">{state.members.map((member) => <Link key={member.id} data-team-member={member.id} href={member.scopeHref} className={`group rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md ${member.selected ? "border-blue-400 ring-2 ring-blue-100" : "border-slate-200"}`}><div className="flex items-start gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-900 font-black text-white">{member.initials}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-black text-slate-950">{member.name}</h3><p className="text-xs font-semibold text-slate-500">{member.roleLabel} · {member.location}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${member.attentionCount ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{member.attentionCount ? `${member.attentionCount} need attention` : "On track"}</span></div><p className="mt-3 truncate text-xs font-semibold capitalize text-slate-500">{member.pipelineSummary}</p><div className="mt-4 grid grid-cols-4 gap-3 border-t border-slate-100 pt-4 text-center"><Signal value={member.candidateCount} label="Candidates" /><Signal value={member.meetingsThisWeek} label="Meetings" /><Signal value={member.overdueTasks} label="Overdue" /><Signal value={member.activeReferrals} label="Referrals" /></div><p className="mt-4 flex items-center justify-between text-xs font-semibold text-slate-400"><span>Latest · {member.latestActivity}</span><span className="inline-flex items-center gap-1 text-blue-600">View scope <ArrowRight size={13} /></span></p></div></div></Link>)}</div>
    </section>

    <div className="grid gap-6 2xl:grid-cols-[1.45fr_0.9fr]">
      <section aria-labelledby="team-pipeline-title" className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-slate-200 p-5"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-teal-600">Team pipeline</p><h2 id="team-pipeline-title" className="mt-1 text-2xl font-black text-slate-950">Candidate movement</h2></div><div className="flex flex-wrap gap-2">{state.pipelineStages.map((stage) => <span key={stage.id} className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-600">{stage.label} · {stage.count}</span>)}</div></header>
        <div className="divide-y divide-slate-100">{state.pipeline.map((candidate) => <article key={candidate.id} data-team-candidate={candidate.id} className="grid gap-4 p-5 sm:grid-cols-[minmax(0,1.2fr)_minmax(150px,.7fr)_minmax(180px,1fr)_auto] sm:items-center"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-xs font-black text-slate-700">{candidate.initials}</span><div className="min-w-0"><Link href={candidate.href} className="font-black text-slate-950 hover:text-blue-700">{candidate.fullName}</Link><div className="mt-1"><OwnerBadge owner={candidate.owner} compact /></div></div></div><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">{candidate.stageLabel}</p><p className="mt-1 text-sm font-bold text-slate-700">{candidate.readiness === null ? "Readiness pending" : `${candidate.readiness}% readiness`}</p></div><div><p className="truncate text-sm font-bold text-slate-800">{candidate.nextAction}</p><p className={`mt-1 text-xs font-semibold ${candidate.attention ? "text-amber-700" : "text-slate-400"}`}>{candidate.attention ? candidate.attentionLabel : `Last activity ${candidate.lastActivityLabel}`}</p></div><Link href={candidate.href} aria-label={`Open ${candidate.fullName}`} className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 text-slate-500 hover:border-blue-300 hover:text-blue-700"><ArrowRight size={16} /></Link></article>)}</div>
      </section>

      <section aria-labelledby="attention-title" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-600">Manager attention</p><h2 id="attention-title" className="mt-1 text-2xl font-black text-slate-950">Intervene with purpose</h2></div><AlertTriangle className="text-amber-500" /></div><div className="mt-5 space-y-3">{state.attention.map((item) => <article key={item.id} data-attention-item={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-slate-900">{item.title}</p><p className="mt-1 text-sm font-bold text-slate-600">{item.candidateName}</p></div><span className={`rounded-full px-2 py-1 text-[9px] font-black uppercase tracking-wider ${item.severity === "critical" ? "bg-rose-50 text-rose-700" : item.severity === "high" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{item.severity}</span></div><div className="mt-3"><OwnerBadge owner={item.owner} compact /></div><p className="mt-3 text-sm leading-6 text-slate-600">{item.reason}</p><Link href={item.href} className="mt-3 inline-flex items-center gap-1 text-xs font-black text-blue-700">{item.actionLabel}<ArrowRight size={13} /></Link></article>)}{state.attention.length === 0 && <p className="rounded-xl bg-emerald-50 p-5 text-sm font-bold text-emerald-700">No manager interventions are required in this scope.</p>}</div></section>
    </div>

    <section aria-labelledby="activity-title" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-blue-600">Situational awareness</p><h2 id="activity-title" className="mt-1 text-2xl font-black text-slate-950">Today &amp; upcoming</h2></div><div className="flex gap-4 text-xs font-bold text-slate-400"><span className="inline-flex items-center gap-1"><CalendarDays size={14} /> Meetings</span><span className="inline-flex items-center gap-1"><ListTodo size={14} /> Follow-through</span></div></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{state.activity.map((item) => <Link key={item.id} data-team-activity={item.id} href={item.href} className="rounded-xl border border-slate-200 p-4 transition hover:border-blue-300 hover:bg-blue-50/30"><div className="flex items-center justify-between"><ActivityIcon kind={item.kind} /><span className="text-[10px] font-black uppercase text-slate-400">{item.whenLabel}</span></div><p className="mt-3 font-black text-slate-900">{item.title}</p><p className="mt-1 text-xs font-semibold text-slate-500">{item.candidateName ?? "Team operating rhythm"}</p><div className="mt-3"><OwnerBadge owner={item.owner} compact /></div></Link>)}</div></section>
  </div>;
}

function Signal({ value, label }: { value: number; label: string }) { return <div><strong className="block text-lg font-black text-slate-900">{value}</strong><span className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</span></div>; }
function ActivityIcon({ kind }: { kind: "task" | "meeting" | "referral" | "stage-change" }) { const Icon = kind === "meeting" ? CalendarDays : kind === "task" ? ListTodo : kind === "referral" ? Target : Waypoints; return <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-50 text-blue-600"><Icon size={16} /></span>; }
