'use server';import{revalidatePath}from'next/cache';import{z}from'zod';import{resolveWorkspaceComposition}from'@/feature/platform/composition/resolveWorkspaceComposition';import{criteriaSchema,readyErrors}from'../models/validation';import type{CampaignStatus}from'../models/Marketing';import {parseCampaignSave} from '../studio/save';import {assertCampaignWritable} from '../studio/persistence';import {visualCopy} from '../studio/legacy';import {renderStudioEmail} from '../studio/render';
import{getPublicEnvironment}from'@/lib/env';
import {studioErrorMessage} from '../studio/errors';
async function usesHostedStudio(){const r=await resolveWorkspaceComposition();if(r.status!=='resolved')throw Error('An active workspace is required.');return r.session.kind==='production';}
async function repo(){const r=await resolveWorkspaceComposition();if(r.status!=='resolved')throw new Error('An active workspace is required.');return r.composition.dependencies.marketing}
export async function previewSegmentAction(value:unknown){return(await repo()).previewCriteria(criteriaSchema.parse(value))}
export async function saveSegmentAction(value:unknown){const x=z.object({id:z.string().optional(),name:z.string().trim().min(1).max(100),description:z.string().max(500),criteria:criteriaSchema}).parse(value);const saved=await(await repo()).saveSegment(x);revalidatePath('/crm/segments');return saved.id}
export async function duplicateSegmentAction(id:string){const saved=await(await repo()).duplicateSegment(z.string().parse(id));revalidatePath('/crm/segments');return saved.id}
export async function previewAudienceAction(type:'segment'|'list',id:string){return(await repo()).previewAudience(z.enum(['segment','list']).parse(type),z.string().min(1).parse(id))}
export async function saveCampaignAction(value:unknown){const x=parseCampaignSave(value);const r=await repo();const existing=x.id?await r.getCampaign(x.id):undefined;if(x.id)assertCampaignWritable(existing,x.expectedUpdatedAt);if(x.content.version===2&&await usesHostedStudio()){const {resolveBranding,resolveMedia}=await import('../media/server');x.brandingSnapshot=existing?.brandingSnapshot&&!x.refreshBranding?existing.brandingSnapshot:await resolveBranding();await resolveMedia(x.content,x.brandingSnapshot);}const preview=x.audienceType&&x.audienceId?await r.previewAudience(x.audienceType,x.audienceId):null;const campaign={...x,status:x.status as CampaignStatus,updatedAt:''};if(x.status==='ready'){const errors=readyErrors(campaign,Boolean(preview?.eligible));if(errors.length)throw new Error(`Complete before Ready: ${errors.join(', ')}.`)}const saved=await r.saveCampaign(campaign);revalidatePath('/crm/campaigns');return saved.id}
export async function duplicateCampaignAction(id:string){const saved=await(await repo()).duplicateCampaign(z.string().parse(id));revalidatePath('/crm/campaigns');return saved.id}
async function delivery(){const r=await resolveWorkspaceComposition();if(r.status!=='resolved')throw new Error('An active workspace is required.');return r.composition}
export async function reviewCampaignSendAction(id:string){const c=await delivery();return c.dependencies.marketingDelivery.review(z.string().min(1).parse(id))}
export async function confirmCampaignSendAction(id:string,key:string,reviewToken?:string){const c=await delivery();if(c.dependencies.marketingDeliveryProvider.mode==='unavailable')throw new Error('External marketing delivery provider is not configured. No message was queued or sent.');const run=await c.dependencies.marketingDelivery.confirm(z.string().min(1).parse(id),z.string().min(16).max(255).parse(key),c.session.kind==='demo',reviewToken);revalidatePath(`/crm/campaigns/${id}`);return run.id}
export async function processCampaignSendAction(id:string){const c=await delivery();const run=await c.dependencies.marketingDelivery.process(z.string().min(1).parse(id),c.dependencies.marketingDeliveryProvider,getPublicEnvironment().APP_URL);revalidatePath('/crm/campaigns');return run}

export async function createVisualCopyAction(id:string){const r=await repo();const source=await r.getCampaign(z.string().min(1).parse(id));if(!source||source.content.version!==1)throw new Error('A supported legacy campaign is required.');const saved=await r.saveCampaign({...source,id:'',name:(source.name+' visual copy').slice(0,120),status:'draft',content:visualCopy(source.content)});revalidatePath('/crm/campaigns');return saved.id;}
export async function previewStudioAction(value:unknown,subject:string,preheader:string,sender:string,campaignId?:string,refreshBranding=false){const r=await repo();let branding;let assets;if(await usesHostedStudio()){const {resolveBranding,resolveMedia}=await import('../media/server');const existing=campaignId?await r.getCampaign(campaignId):undefined;if(campaignId&&!existing)throw Error('Campaign not found.');branding=existing?.brandingSnapshot&&!refreshBranding?existing.brandingSnapshot:await resolveBranding();const {parseEmailDocument}=await import('../studio/document');assets=await resolveMedia(parseEmailDocument(value),branding);}return renderStudioEmail(value,{assets,subject,preheader,personalization:{first_name:'Jordan',preferred_name:'Jordan',consultant_name:sender||'Your consultant'},compliance:{sender:branding?.name||sender||'Your consultant',postalAddress:branding?.postalAddress||'Sender postal address required before delivery',unsubscribeUrl:'https://example.invalid/unsubscribe/preview'},preview:true});}
// Expected validation/conflict errors are data, not production-sanitized exceptions.
export async function saveStudioDraftAction(value:unknown){try{return{ok:true as const,id:await saveCampaignAction(value)}}catch(error){return{ok:false as const,error:studioErrorMessage(error)}}}
export async function previewStudioResultAction(value:unknown,subject:string,preheader:string,sender:string,campaignId?:string,refreshBranding=false){try{return{ok:true as const,preview:await previewStudioAction(value,subject,preheader,sender,campaignId,refreshBranding)}}catch(error){return{ok:false as const,error:studioErrorMessage(error)}}}

export async function reviewStudioSendResultAction(id:string){try{return{ok:true as const,review:await reviewCampaignSendAction(id)}}catch(error){return{ok:false as const,error:error instanceof Error?error.message:'Audience review unavailable.'}}}
export async function confirmStudioSendResultAction(id:string,key:string,reviewToken:string){try{const sendId=await confirmCampaignSendAction(id,key,z.uuid().parse(reviewToken));return{ok:true as const,run:await processCampaignSendAction(sendId)}}catch(error){return{ok:false as const,error:error instanceof Error?error.message:'Confirmation unavailable.'}}}
export async function sendStudioTestAction(value:unknown){try{
 const input=z.object({id:z.string().min(1),revision:z.string().min(1),recipient:z.email(),key:z.string().min(16).max(255)}).strict().parse(value);
 const c=await delivery();if(c.session.kind!=='production')throw Error('Test email requires a connected workspace.');
 const {StudioDeliveryService}=await import('../delivery/StudioDeliveryService');const {createServerSupabaseClient}=await import('@/lib/supabase/server');const session=c.session;
 const service=new StudioDeliveryService(await createServerSupabaseClient(),{user:{id:session.identity.userId,email:session.identity.email},organization:session.organization,membership:session.membership,capabilities:session.capabilities},c.dependencies.marketing);
 const result=await service.test(input.id,input.revision,input.recipient,input.key,c.dependencies.marketingDeliveryProvider);return{ok:true as const,result};
 }catch(error){return{ok:false as const,error:error instanceof z.ZodError?'Enter a valid test email address.':error instanceof Error?error.message:'Test email unavailable.'}}}
