'use server';import{revalidatePath}from'next/cache';import{z}from'zod';import{resolveWorkspaceComposition}from'@/feature/platform/composition/resolveWorkspaceComposition';import{criteriaSchema,contentSchema,invalidTokens,readyErrors}from'../models/validation';import type{CampaignStatus}from'../models/Marketing';
import{getPublicEnvironment}from'@/lib/env';
async function repo(){const r=await resolveWorkspaceComposition();if(r.status!=='resolved')throw new Error('An active workspace is required.');return r.composition.dependencies.marketing}
export async function previewSegmentAction(value:unknown){return(await repo()).previewCriteria(criteriaSchema.parse(value))}
export async function saveSegmentAction(value:unknown){const x=z.object({id:z.string().optional(),name:z.string().trim().min(1).max(100),description:z.string().max(500),criteria:criteriaSchema}).parse(value);const saved=await(await repo()).saveSegment(x);revalidatePath('/crm/segments');return saved.id}
export async function duplicateSegmentAction(id:string){const saved=await(await repo()).duplicateSegment(z.string().parse(id));revalidatePath('/crm/segments');return saved.id}
const campaignSchema=z.object({id:z.string(),name:z.string().trim().min(1).max(120),description:z.string().max(1000),subject:z.string().max(180),previewText:z.string().max(220),senderName:z.string().max(120),replyTo:z.string().max(320),audienceType:z.enum(['segment','list']).nullable(),audienceId:z.string(),content:contentSchema,status:z.enum(['draft','ready'])});
export async function previewAudienceAction(type:'segment'|'list',id:string){return(await repo()).previewAudience(z.enum(['segment','list']).parse(type),z.string().min(1).parse(id))}
export async function saveCampaignAction(value:unknown){const x=campaignSchema.parse(value);const r=await repo();const preview=x.audienceType&&x.audienceId?await r.previewAudience(x.audienceType,x.audienceId):null;const campaign={...x,status:x.status as CampaignStatus,updatedAt:''};if(x.status==='ready'){const errors=readyErrors(campaign,Boolean(preview?.eligible));if(errors.length)throw new Error(`Complete before Ready: ${errors.join(', ')}.`)}if(invalidTokens(x.content,x.subject,x.previewText).length)throw new Error('Remove unsupported personalization tokens.');const saved=await r.saveCampaign(campaign);revalidatePath('/crm/campaigns');return saved.id}
export async function duplicateCampaignAction(id:string){const saved=await(await repo()).duplicateCampaign(z.string().parse(id));revalidatePath('/crm/campaigns');return saved.id}
async function delivery(){const r=await resolveWorkspaceComposition();if(r.status!=='resolved')throw new Error('An active workspace is required.');return r.composition}
export async function reviewCampaignSendAction(id:string){const c=await delivery();return c.dependencies.marketingDelivery.review(z.string().min(1).parse(id))}
export async function confirmCampaignSendAction(id:string,key:string){const c=await delivery();if(c.dependencies.marketingDeliveryProvider.mode==='unavailable')throw new Error('External marketing delivery provider is not configured. No message was queued or sent.');const run=await c.dependencies.marketingDelivery.confirm(z.string().min(1).parse(id),z.string().min(16).max(255).parse(key),c.session.kind==='demo');revalidatePath(`/crm/campaigns/${id}`);return run.id}
export async function processCampaignSendAction(id:string){const c=await delivery();const run=await c.dependencies.marketingDelivery.process(z.string().min(1).parse(id),c.dependencies.marketingDeliveryProvider,getPublicEnvironment().APP_URL);revalidatePath('/crm/campaigns');return run}
