import type { CandidateAction } from "../models/CandidateAction";

import { Button, Card } from "@/feature/ui";

type Props = {
  status: string;
  readiness: number;
  confidence: number;
  decisionWindow: string;
  primaryAction: CandidateAction | null;
};

export function AICommandCenter({
  status,
  readiness,
  confidence,
  decisionWindow,
  primaryAction,
}: Props) {
  return (
    <Card
      title="AI Command Center"
      subtitle="Executive guidance generated by FranGroove AI."
    >
      <div className="space-y-8">
        <section className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">
              Candidate Status
            </p>

            <div className="mt-3 inline-flex rounded-full bg-emerald-100 px-4 py-2 text-sm font-semibold text-emerald-700">
              {status}
            </div>
          </div>

          <div className="grid grid-cols-3 gap-5 text-center">
            <Metric
              label="Readiness"
              value={`${readiness}/100`}
            />

            <Metric
              label="Confidence"
              value={`${confidence}%`}
            />

            <Metric
              label="Decision"
              value={decisionWindow}
            />
          </div>
        </section>

        {primaryAction ? (
          <section className="rounded-3xl border border-blue-200 bg-gradient-to-r from-blue-50 via-indigo-50 to-slate-50 p-8">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">
              Next Best Action
            </p>

            <h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-900">
              {primaryAction.title}
            </h2>

            <p className="mt-4 max-w-3xl leading-8 text-slate-700">
              {primaryAction.description}
            </p>

            <div className="mt-8 grid gap-5 lg:grid-cols-2">
              <div className="rounded-2xl border border-white bg-white/80 p-5">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
                  Why AI recommends this
                </p>

                <p className="mt-3 leading-7 text-slate-700">
                  {primaryAction.reason}
                </p>
              </div>

              <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5">
                <p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">
                  Expected Outcome
                </p>

                <p className="mt-3 leading-7 text-slate-700">
                  {primaryAction.recommendedOutcome}
                </p>
              </div>
            </div>

            <div className="mt-8 flex flex-wrap items-center gap-3">
              {primaryAction.tags.map((tag) => (
                <span
                  key={tag}
                  className="rounded-full bg-white px-3 py-1 text-xs font-medium text-slate-600 shadow-sm"
                >
                  {tag}
                </span>
              ))}
            </div>

            <div className="mt-8 flex flex-wrap gap-4">
              <Button>
                Execute Action
              </Button>

              <Button variant="secondary">
                Generate Brief
              </Button>

              <Button variant="secondary">
                Email Candidate
              </Button>

              <Button variant="ghost">
                View Assessment
              </Button>
            </div>
          </section>
        ) : (
          <section className="rounded-3xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center">
            <h2 className="text-xl font-semibold text-slate-900">
              No Recommended Actions
            </h2>

            <p className="mt-3 text-slate-600">
              The intelligence engine did not generate any actions for this
              candidate.
            </p>
          </section>
        )}
      </div>
    </Card>
  );
}

type MetricProps = {
  label: string;
  value: string;
};

function Metric({
  label,
  value,
}: MetricProps) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
        {label}
      </p>

      <p className="mt-2 text-2xl font-bold tracking-tight text-slate-900">
        {value}
      </p>
    </div>
  );
}
