begin;
create extension if not exists pgtap with schema extensions;
select plan(18);
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.consultant_tasks'::regclass),'consultant_tasks enforces RLS');
select ok(not has_table_privilege('anon','public.consultant_tasks','select,insert,update,delete'),'consultant_tasks denies anonymous access');
select ok(exists(select 1 from pg_trigger where tgrelid='public.consultant_tasks'::regclass and tgname='consultant_tasks_identity'),'consultant_tasks protects identity');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.consultant_calendar_events'::regclass),'consultant_calendar_events enforces RLS');
select ok(not has_table_privilege('anon','public.consultant_calendar_events','select,insert,update,delete'),'consultant_calendar_events denies anonymous access');
select ok(exists(select 1 from pg_trigger where tgrelid='public.consultant_calendar_events'::regclass and tgname='consultant_calendar_events_identity'),'consultant_calendar_events protects identity');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.consultant_reminders'::regclass),'consultant_reminders enforces RLS');
select ok(not has_table_privilege('anon','public.consultant_reminders','select,insert,update,delete'),'consultant_reminders denies anonymous access');
select ok(exists(select 1 from pg_trigger where tgrelid='public.consultant_reminders'::regclass and tgname='consultant_reminders_identity'),'consultant_reminders protects identity');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.consultant_task_dismissals'::regclass),'consultant_task_dismissals enforces RLS');
select ok(not has_table_privilege('anon','public.consultant_task_dismissals','select,insert,update,delete'),'consultant_task_dismissals denies anonymous access');
select ok(exists(select 1 from pg_trigger where tgrelid='public.consultant_task_dismissals'::regclass and tgname='consultant_task_dismissals_identity'),'consultant_task_dismissals protects identity');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.candidate_brand_considerations'::regclass),'candidate_brand_considerations enforces RLS');
select ok(not has_table_privilege('anon','public.candidate_brand_considerations','select,insert,update,delete'),'candidate_brand_considerations denies anonymous access');
select ok(exists(select 1 from pg_trigger where tgrelid='public.candidate_brand_considerations'::regclass and tgname='candidate_brand_considerations_identity'),'candidate_brand_considerations protects identity');
select ok(not (select prosecdef from pg_proc where oid='public.set_candidate_brand_consideration(text,text,text)'::regprocedure),'selection executes with caller RLS');
select ok(not has_function_privilege('anon','public.set_candidate_brand_consideration(text,text,text)','execute'),'anonymous selection denied');
select ok(exists(select 1 from pg_indexes where indexname='candidate_one_selected_brand' and indexdef like '%UNIQUE%'),'one selected brand per tenant candidate');
select * from finish();
rollback;
