"use client";
import { ConsiderationControls } from "@/feature/referral-package/components/ConsiderationControls";
import { useState } from "react";
import Link from "next/link";
import type { PersistedCandidateWorkspace } from "@/feature/crm/models/PersistedCandidateWorkspace";
import { compareBrands, explainComparison, fitLabels, type BrandReferralResult, type FitFactor } from "../production/BrandReferralEngine";

const tones = { aligned: "bg-teal-50 text-teal-900", validate: "bg-amber-50 text-amber-900", constraint: "bg-rose-50 text-rose-900", unknown: "bg-slate-100 text-slate-700" };
export function FitFactorList({ factors }: { factors: FitFactor[] }) {
  return <div className="space-y-3">{factors.map(f => <div key={f.label} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-sm font-bold">{f.label}</h4><span className={`rounded-full px-2 py-1 text-xs font-bold ${tones[f.state]}`}>{fitLabels[f.state]}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{f.explanation}</p><details className="mt-2 text-xs text-slate-500"><summary className="cursor-pointer py-2">View evidence{f.provisional ? " · Provisional" : ""}</summary><p>Candidate: {f.candidateSource}</p><p className="mt-1 break-words">Brand: {f.brandSource}</p><p className="mt-1">{f.evidence.join("; ") || "No verified brand evidence supplied for this factor."}</p></details></div>)}</div>;
}
export function BrandReferralWorkspace({ row, results, considerations=[] }: { row: PersistedCandidateWorkspace; results: BrandReferralResult[]; considerations?:{brand_public_id:string;state:string}[] }) {
  const [selected, setSelected] = useState<string[]>([]);
  const comparisons = compareBrands(results, selected);
  const rankedSelection = results.filter(result => selected.includes(result.brandId));
  const explanation = rankedSelection.length >= 2 ? explainComparison(rankedSelection[0], rankedSelection[1]) : null;
  const base = `/crm/candidates/${encodeURIComponent(row.candidate.id)}`;
  const analysis = row.assessment?.analysis;
  if (!analysis) return <section className="rounded-2xl border bg-white p-6"><h1 className="text-2xl font-black">Brand Referral Engine</h1><p className="mt-3 text-slate-600">Complete the trusted assessment before reviewing candidate-specific brand fit.</p><Link href={base} className="mt-4 inline-flex min-h-11 items-center font-bold text-blue-700">Return to Candidate 360</Link></section>;
  return <div className="min-w-0 space-y-7" data-brand-referral-engine>
    <nav aria-label="Candidate journey" className="flex flex-wrap gap-3 text-sm font-bold text-blue-700"><Link className="py-2" href="/crm">Mission Control</Link><Link className="py-2" href="/crm/candidates">Pipeline</Link><Link className="py-2" href={base}>Candidate 360</Link><Link className="py-2" href={`/crm/${row.candidate.id}/discovery`}>Discovery</Link></nav>
    <header className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-widest text-teal-300">Consultant decision support</p><h1 className="mt-3 text-3xl font-black">Brand Referral Engine</h1><h2 className="mt-4 text-xl font-bold">{row.candidate.firstName} {row.candidate.lastName}</h2><p className="mt-2 max-w-3xl leading-7 text-slate-300">{analysis.consultantBrief.ownershipOrientation.text}</p><div className="mt-5 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white/10 px-3 py-2">{analysis.ownershipProfile.primary}</span><span className="rounded-full bg-white/10 px-3 py-2">Profile confidence {Math.round(analysis.ownershipProfile.confidence * 100)}% · not a fit score</span></div></header>
    <section aria-label="Candidate financial context" className="grid gap-3 sm:grid-cols-3">{[["Reported liquid capital", analysis.financial.liquidCapital], ["Reported net worth", analysis.financial.netWorth], ["Investment preference", analysis.financial.investmentRange]].map(([label, value]) => <div key={label} className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 break-words font-bold">{value}</p></div>)}</section>
    <p className="text-sm text-slate-600">{analysis.financial.disclaimer} Rankings use fit bands, then supported factors and missing evidence. Ties use brand name; there is no implied precision between tied brands. Unknown facts never become positive assumptions.</p>
    {analysis.tensions.length > 0 && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-black text-amber-950">Keep these candidate tensions in view</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-amber-950">{analysis.tensions.map(t => <li key={t.title}><strong>{t.title}:</strong> {t.explanation}</li>)}</ul></section>}
    <section id="brand-comparison" aria-labelledby="comparison-heading" className="scroll-mt-24 rounded-2xl border border-blue-200 bg-blue-50 p-5 sm:p-6"><h2 id="comparison-heading" className="text-xl font-black">Compare your options</h2><p aria-live="polite" className="mt-2 text-sm text-slate-600">{selected.length} of 3 brands selected. Choose brands below to compare the reasons, tradeoffs and unknowns side by side.</p>
      {explanation && <div className="mt-4 rounded-xl bg-white p-4 text-sm leading-6 text-slate-700"><p className="font-bold">{explanation.summary}</p><p className="mt-2">Where {rankedSelection[1].name} may be stronger: {explanation.alternativeAdvantages.join(", ") || "no additional supported factor distinguishes it in the current evidence; review the tradeoffs below"}.</p><p className="mt-2">Unknown facts remain diligence questions for both options. A ranking does not settle the consultant&apos;s decision.</p></div>}
      {comparisons.length > 0 && <div className="mt-5 grid gap-4 lg:grid-cols-3">{comparisons.map(r => <article key={r.brandId} className="min-w-0 rounded-xl bg-white p-4"><h3 className="font-black">{r.name}</h3><p className="mt-1 text-sm font-bold text-blue-800">{r.band}</p><p className="mt-3 text-xs text-slate-600">{r.strengths.length} supported factors · {r.concerns.filter(f => f.state === "constraint").length} potential conflicts · {r.unknowns.length} unknown factors</p><div className="mt-4"><FitFactorList factors={r.factors} /></div><p className="mt-4 text-sm font-semibold">Next: {r.nextStep}</p><Link className="mt-3 inline-flex min-h-11 items-center text-sm font-bold text-blue-700" href={`${base}/referral?brand=${encodeURIComponent(r.brandId)}`}>Prepare handoff for {r.name}</Link></article>)}</div>}
    </section>
    <section aria-labelledby="ranked-heading"><h2 id="ranked-heading" className="text-xl font-black">Opportunities to investigate</h2><p className="mt-2 text-sm text-slate-600">These are research priorities, not franchisor approval or verified territory availability.</p><div className="mt-5 space-y-5">{results.map((r, index) => <article key={r.brandId} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6" data-brand-result={r.brandId}>
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-teal-700">Review order {index + 1}{r.concept ? " · Concept profile" : ""}</p><h3 className="mt-2 text-2xl font-black">{r.name}</h3><p className="mt-2 font-bold text-blue-800">{r.band}</p></div><button type="button" aria-pressed={selected.includes(r.brandId)} disabled={!selected.includes(r.brandId) && selected.length >= 3} onClick={() => setSelected(s => s.includes(r.brandId) ? s.filter(id => id !== r.brandId) : [...s, r.brandId].slice(0, 3))} className="min-h-11 rounded-xl border border-blue-300 px-4 text-sm font-bold text-blue-800 disabled:opacity-50">{selected.includes(r.brandId) ? "Remove from comparison" : "Compare"} {r.name}</button></div>
      <ConsiderationControls candidateId={row.candidate.id} brandId={r.brandId} state={considerations.find(c=>c.brand_public_id===r.brandId)?.state}/><p className="mt-3 text-xs text-slate-500">{r.evidenceLabel}</p><div className="mt-5 grid gap-5 md:grid-cols-3"><Summary title="Supports fit" factors={r.strengths} /><Summary title="Concerns and validation" factors={r.concerns} /><Summary title="Important unknowns" factors={r.unknowns} /></div>
      <div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-sm font-bold">Financial compatibility: {fitLabels[r.financial]}</p><p className="mt-2 text-sm leading-6 text-slate-600">{r.nextStep}</p></div>
      <details className="mt-4"><summary className="cursor-pointer py-3 text-sm font-bold text-blue-800">Inspect fit and supporting evidence for {r.name}</summary><FitFactorList factors={r.factors} /></details>
      <div className="mt-4 flex flex-wrap gap-3"><Link href={`/crm/brands/${encodeURIComponent(r.brandId)}?candidate=${encodeURIComponent(row.candidate.id)}`} className="inline-flex min-h-11 items-center rounded-xl border px-4 text-sm font-bold">Open {r.name} Brand Intelligence</Link><Link href={`${base}/referral?brand=${encodeURIComponent(r.brandId)}`} className="inline-flex min-h-11 items-center rounded-xl bg-teal-700 px-4 text-sm font-bold text-white">Prepare handoff for {r.name}</Link></div>
    </article>)}</div>{!results.length && <p className="mt-5 rounded-xl border bg-white p-5">No published Brand Intelligence profiles are available in this workspace.</p>}</section>
  </div>;
}
function Summary({ title, factors }: { title: string; factors: FitFactor[] }) { return <div><h4 className="text-sm font-black">{title}</h4><ul className="mt-2 space-y-2 text-sm text-slate-600">{factors.slice(0, 3).map(f => <li key={f.label}>{f.label}: {f.explanation}</li>)}{!factors.length && <li>None identified from the available evidence.</li>}</ul>{factors.length > 3 && <p className="mt-2 text-xs text-slate-500">{factors.length - 3} more in the full evidence review.</p>}</div>; }
