"use client";

import Link from "next/link";
import { useActionState } from "react";
import { AlertTriangle, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, BadgeCheck, ShieldCheck } from "lucide-react";
import type { CandidateBrandRecommendationState, CandidateBrandStrategyState } from "../models/CandidateBrandStrategyState";
import { updateStrategyBuilder, type StrategyActionState } from "../actions/strategy-builder";
import { startBrandPresentation } from "../actions/brand-presentation";

const initialState: StrategyActionState = { status: "idle" };
const reactionLabels = { "strong-interest": "Strong Interest", interested: "Interested", neutral: "Neutral", "not-interested": "Not Interested" } as const;
const dispositionLabels = { refer: "Refer", "continue-research": "Continue Research", hold: "Hold", remove: "Remove" } as const;

function Unavailable({ state }: { state: CandidateBrandStrategyState }) {
  return <main className="mx-auto max-w-5xl p-8"><Link href={`/crm/candidates/${state.candidate.id}`} className="text-sm font-bold text-slate-500">← Candidate 360</Link><section className="mt-8 rounded-3xl border border-amber-200 bg-white p-8"><AlertTriangle className="text-amber-600" /><h1 className="mt-3 text-2xl font-black">Brand Strategy is not ready for {state.candidate.fullName}</h1><p className="mt-3 text-sm text-slate-600">{state.unavailableReason}</p></section></main>;
}

function Hidden({ state, item, kind }: { state: CandidateBrandStrategyState; item: CandidateBrandRecommendationState; kind: string }) {
  return <><input type="hidden" name="candidateId" value={state.candidate.id} /><input type="hidden" name="brandId" value={item.brandId} /><input type="hidden" name="kind" value={kind} /></>;
}

function RecommendationCard({ state, item, action, pending }: { state: CandidateBrandStrategyState; item: CandidateBrandRecommendationState; action: (payload: FormData) => void; pending: boolean }) {
  return <article aria-label={`${item.brandName} recommendation`} className={`rounded-2xl border bg-white p-5 shadow-sm ${item.selectedForPresentation ? "border-teal-400 ring-1 ring-teal-200" : "border-slate-200"}`}>
    <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-blue-600"><span>AI Rank #{item.rank} · </span><span>{item.recommendationLabel}</span></p><h3 className="mt-1 text-xl font-black">{item.brandName}</h3><p className="text-xs text-slate-500">{item.category}</p></div><div className="text-right"><strong className="text-3xl font-black">{item.score}%</strong><p className="text-[10px] font-black uppercase text-slate-400">AI Match</p><p className="text-xs text-slate-500">{item.confidence}% confidence</p></div></div>
    <p className="mt-4 text-sm leading-6 text-slate-600">{item.rationale}</p>
    <ul className="mt-3 grid gap-1 text-xs text-slate-700 sm:grid-cols-2">{item.fitDimensions.slice(0, 4).map((fit) => <li key={fit.id}>• {fit.label}: {fit.alignment}% alignment</li>)}</ul>
    {item.concerns[0] && <p className="mt-3 rounded-lg bg-amber-50 p-2 text-xs text-amber-800"><strong>Tradeoff:</strong> {item.concerns[0]}</p>}
    <p className={`mt-3 text-xs font-bold ${item.qualified ? "text-emerald-700" : "text-rose-700"}`}><span>{item.qualified ? "Financially Qualified" : "Not Financially Qualified"}</span><span> · {item.investment.requiredInvestment}</span></p>
    <details className="mt-4 rounded-xl bg-slate-50 p-3"><summary className="cursor-pointer text-xs font-black">Evidence & presentation guidance</summary><div className="mt-3 grid gap-4 text-xs sm:grid-cols-2"><div><strong>Why this fits</strong>{item.evidence.slice(0, 4).map((evidence) => <p key={evidence.id} className="mt-1 text-slate-600">{evidence.title} · {evidence.source}</p>)}</div><div><strong>Lead with</strong><p className="mt-1 text-slate-600">{item.presentationGuidance.leadWith.join(" · ")}</p><strong className="mt-2 block">Suggested transition</strong><p className="mt-1 text-slate-600">{item.presentationGuidance.suggestedTransition}</p></div></div></details>
    <Link href={`/crm/brands/${item.brandId}`} className="mt-3 inline-flex text-xs font-black text-blue-600">View Brand Profile</Link>
    {!state.workflow.historical && <form action={action} className="mt-4"><Hidden state={state} item={item} kind="toggle-presentation" /><button disabled={pending} aria-pressed={item.selectedForPresentation} className={`w-full rounded-xl px-4 py-2.5 text-sm font-black ${item.selectedForPresentation ? "border border-slate-300 text-slate-700" : "bg-blue-600 text-white"}`}>{item.selectedForPresentation ? "Remove from Presentation Set" : "Add to Presentation Set"}</button></form>}
  </article>;
}

export function CandidateBrandStrategyPage({ state }: { state: CandidateBrandStrategyState }) {
  const [result, action, pending] = useActionState(updateStrategyBuilder, initialState);
  if (!state.available) return <Unavailable state={state} />;
  const selected = state.recommendations.filter((item) => item.selectedForPresentation).sort((a, b) => (a.presentationOrder ?? 999) - (b.presentationOrder ?? 999));
  return <main className="mx-auto max-w-7xl space-y-5 p-6 lg:p-8">
    <header><Link href={`/crm/candidates/${state.candidate.id}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} />Back to {state.candidate.fullName}</Link><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-blue-600">Brand presentation strategy</p><h1 aria-label={`Brand Strategy for ${state.candidate.fullName}`} className="mt-1 text-3xl font-black">Why these brands for {state.candidate.fullName}?</h1><p className="mt-1 max-w-3xl text-sm text-slate-600">Compare the ownership fit and tradeoffs, then choose what to present. You control every downstream decision.</p></div><div aria-label="Candidate Readiness" className="flex items-center gap-3 rounded-xl border bg-white px-4 py-3"><div><p className="text-xs font-black uppercase text-slate-400">Candidate Readiness</p><p className="text-xs text-slate-500">Distinct from brand fit</p></div><p className="text-2xl font-black">{state.candidate.readiness}%</p></div></div></header>
    {state.leadRecommendation && <section className="rounded-2xl border border-blue-200 bg-blue-50 px-5 py-4"><p className="text-xs font-black uppercase tracking-[0.18em] text-blue-700">Recommended presentation lead</p><p className="mt-1 text-base font-black">{state.leadRecommendation.statement}</p><h2 className="mt-2 text-xs font-black uppercase text-blue-700">{state.leadRecommendation.comparisonHeading}</h2><p className="mt-1 text-sm text-slate-700">{state.leadRecommendation.comparisonExplanation}</p></section>}
    <section className="flex flex-wrap gap-x-6 gap-y-2 rounded-xl border bg-white px-4 py-3" aria-label="Strategy workflow">{[["Workflow", state.workflow.label], ["Brands", state.recommendations.length], ["Presented", `${state.workflow.presented}/${state.workflow.selected}`], ["Strong Interest", state.workflow.strongInterest], ["Referral", state.workflow.referralSelections]].map(([label, value]) => <div key={label} className="flex items-baseline gap-2"><p className="text-xs font-bold text-slate-500">{label}</p><p className="text-sm font-black">{value}</p></div>)}</section>
    {result.message && <p aria-live="polite" className={`rounded-xl p-3 text-sm font-bold ${result.status === "error" ? "bg-rose-50 text-rose-700" : "bg-teal-50 text-teal-700"}`}>{result.message}</p>}
    <section><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">Evidence-backed brand options</p><h2 aria-label="Ranked alternatives" className="mt-1 text-2xl font-black">Viable for different reasons</h2><p className="mb-4 mt-1 text-sm text-slate-500">Compare why each ownership model fits and what to validate before presenting.</p><div className="grid gap-4 lg:grid-cols-2">{state.recommendations.map((item) => <RecommendationCard key={item.brandId} state={state} item={item} action={action} pending={pending} />)}</div></section>
    <section aria-label="Presentation Set" className="rounded-3xl border bg-white p-6"><p className="text-xs font-black uppercase tracking-[0.2em] text-teal-600">Presentation Set</p><h2 className="mt-1 text-2xl font-black">Consultant presentation order</h2><p className="text-sm text-slate-500">Presentation order does not change AI rank.</p>
      {selected.length === 0 ? <p className="mt-5 rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Select one or more recommendations to create the Presentation Set.</p> : <div className="mt-5 space-y-4">{!state.workflow.historical ? <form action={startBrandPresentation}><input type="hidden" name="candidateId" value={state.candidate.id} /><button className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white">{state.workflow.presented ? "Continue Brand Presentation" : "Start Brand Presentation"}<ArrowRight size={16} /></button></form> : <Link href={`/crm/candidates/${state.candidate.id}/strategy/presentation`} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-5 py-3 text-sm font-black text-white">Review Brand Presentation <ArrowRight size={16} /></Link>}{selected.map((item, index) => <article key={item.brandId} aria-label={`${item.brandName} presentation`} className="rounded-2xl border p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-black text-teal-700">Presentation #{item.presentationOrder} · AI Rank #{item.rank}{item.presentedAt ? " · Presented" : " · Not Presented"}</p><h3 className="text-xl font-black">{item.brandName}</h3></div>{!state.workflow.historical && <div className="flex gap-2"><form action={action}><Hidden state={state} item={item} kind="move" /><input type="hidden" name="direction" value="up" /><button disabled={pending || index === 0} aria-label={`Move ${item.brandName} up`} className="rounded-lg border p-2 disabled:opacity-30"><ArrowUp size={16} /></button></form><form action={action}><Hidden state={state} item={item} kind="move" /><input type="hidden" name="direction" value="down" /><button disabled={pending || index === selected.length - 1} aria-label={`Move ${item.brandName} down`} className="rounded-lg border p-2 disabled:opacity-30"><ArrowDown size={16} /></button></form></div>}</div>
          <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl bg-blue-50 p-4 text-xs"><p><strong>Why it fits:</strong> {item.rationale}</p><p className="mt-2 text-amber-800"><strong>Concern:</strong> {item.concerns[0] ?? "No material concern recorded."}</p><p className="mt-2 font-black">AI Match {item.score}% · unchanged</p></div><form action={action} className="grid gap-3"><Hidden state={state} item={item} kind="response" /><label className="text-xs font-black">Candidate Reaction<select aria-label={`${item.brandName} Candidate Reaction`} name="reaction" required disabled={state.workflow.historical} defaultValue={item.candidateReaction ?? ""} className="mt-1 w-full rounded-lg border p-2.5 text-sm"><option value="" disabled>Select reaction</option>{Object.entries(reactionLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-black">Consultant Note<textarea aria-label={`${item.brandName} Consultant Note`} name="notes" disabled={state.workflow.historical} defaultValue={item.consultantNotes} rows={2} className="mt-1 w-full rounded-lg border p-2.5 text-sm" /></label>{!state.workflow.historical && <button disabled={pending} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-black text-white">Save Candidate Response</button>}</form></div>
          <div className="mt-4 border-t pt-4"><p className="text-xs font-black uppercase text-slate-500">Final Shortlist</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(dispositionLabels).map(([value, label]) => state.workflow.historical ? item.shortlistDisposition === value && <span key={value} className="rounded-lg bg-teal-50 px-3 py-2 text-xs font-black text-teal-700">{label}</span> : <form action={action} key={value}><Hidden state={state} item={item} kind="disposition" /><input type="hidden" name="disposition" value={value} /><button disabled={pending} aria-pressed={item.shortlistDisposition === value} className={`rounded-lg border px-3 py-2 text-xs font-black ${item.shortlistDisposition === value ? "border-teal-500 bg-teal-50 text-teal-700" : "border-slate-200"}`}>{label}</button></form>)}</div></div>
        </article>)}</div>}
    </section>
    {state.referralDecision && <section aria-label="Referral Readiness" className="rounded-3xl bg-slate-950 p-7 text-white"><div className="flex flex-wrap items-center justify-between gap-5"><div className="flex gap-4"><ShieldCheck className={state.referralDecision.passed ? "text-emerald-300" : "text-amber-300"} /><div><p className={state.referralDecision.passed ? "text-xs font-black uppercase text-emerald-300" : "text-xs font-black uppercase text-amber-300"}>Referral Readiness · {state.referralDecision.gateLabel}</p><h2 className="mt-1 text-2xl font-black">{state.referralDecision.heading}</h2><p className="mt-2 max-w-2xl text-sm text-slate-300">{state.referralDecision.explanation}</p>{state.referralDecision.unresolvedReasons.length > 0 && <ul className="mt-3 space-y-1 text-xs text-amber-200">{state.referralDecision.unresolvedReasons.map((reason) => <li key={reason}>• {reason}</li>)}</ul>}</div></div><Link href={`/crm/candidates/${state.candidate.id}/referral`} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black">{state.referralDecision.passed ? "Open Referral Studio" : "Prepare Referral Anyway"} <ArrowRight size={16} /></Link></div></section>}
    {state.workflow.historical && <section className="rounded-2xl border border-teal-200 bg-teal-50 p-5"><div className="flex gap-3"><BadgeCheck className="text-teal-700" /><div><h2 className="font-black">Completed Strategy History</h2><p className="text-sm text-teal-900">Prior presentation, response, shortlist, and referral decisions remain visible.</p></div></div></section>}
  </main>;
}
