import Link from "next/link";
import { AlertTriangle, ArrowLeft, ArrowRight, BadgeCheck, BarChart3, CircleDollarSign, Lightbulb, ShieldCheck, Sparkles } from "lucide-react";
import type { CandidateBrandRecommendationState, CandidateBrandStrategyState } from "../models/CandidateBrandStrategyState";

function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }

function FitBars({ item }: { item: CandidateBrandRecommendationState }) {
  return <div className="grid gap-3 sm:grid-cols-2">{item.fitDimensions.map((dimension) => <div key={dimension.id}><div className="mb-1.5 flex justify-between text-xs font-bold text-slate-600"><span>{dimension.label}</span><span>{dimension.alignment}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-500" style={{ width: `${dimension.alignment}%` }} /></div></div>)}</div>;
}

function Unavailable({ state }: { state: CandidateBrandStrategyState }) {
  return <main className="mx-auto max-w-5xl p-6 lg:p-10"><Link href={`/crm/candidates/${state.candidate.id}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} />Candidate 360</Link><section className="mt-8 rounded-3xl border border-amber-200 bg-white p-8 shadow-sm"><div className="flex gap-4"><AlertTriangle className="text-amber-600" /><div><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-600">Intelligence unavailable</p><h1 className="mt-2 text-2xl font-black text-slate-950">Brand Strategy is not ready for {state.candidate.fullName}</h1><p className="mt-3 text-sm text-slate-600">{state.unavailableReason}</p></div></div></section></main>;
}

function Guidance({ item }: { item: CandidateBrandRecommendationState }) {
  const guidance = item.presentationGuidance;
  return <div className="rounded-2xl border border-slate-200 p-5"><h3 className="flex items-center gap-2 font-black text-slate-900"><Lightbulb size={18} className="text-amber-500" />How to present it</h3><div className="mt-4 space-y-4 text-sm text-slate-700"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Lead with</p><ul className="mt-2 space-y-2">{guidance.leadWith.map((text) => <li key={text} className="flex gap-2"><ArrowRight size={14} className="mt-1 shrink-0 text-blue-500" />{text}</li>)}</ul></div><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Emphasize</p><p className="mt-2 leading-6">{guidance.emphasize.join(" · ")}</p></div><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Suggested transition</p><p className="mt-2 leading-6">{guidance.suggestedTransition}</p></div></div></div>;
}

export function CandidateBrandStrategyPage({ state }: { state: CandidateBrandStrategyState }) {
  if (!state.available) return <Unavailable state={state} />;
  const [top, ...alternatives] = state.recommendations;
  return <main className="mx-auto max-w-7xl space-y-8 p-6 lg:p-10">
    <header><Link href={`/crm/candidates/${state.candidate.id}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-900"><ArrowLeft size={16} />Candidate 360</Link><div className="mt-6 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-blue-600">AI Brand Strategy</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Brand Strategy for {state.candidate.fullName}</h1><p className="mt-3 text-lg font-black text-slate-900">{state.leadRecommendation?.statement}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{state.overallStrategy}</p></div>{state.candidate.readiness !== null && <div aria-label="Candidate Readiness" className="w-52 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Candidate Readiness</p><div className="mt-2 flex items-end justify-between"><strong className="text-3xl font-black text-slate-950">{state.candidate.readiness}%</strong><span className="text-xs font-bold text-slate-500">Canonical score</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-500" style={{ width: `${state.candidate.readiness}%` }} /></div></div>}</div></header>

    {state.leadRecommendation && <section className="rounded-2xl border border-blue-100 bg-blue-50/60 p-6"><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">{state.leadRecommendation.comparisonHeading}</p><p className="mt-2 max-w-5xl text-sm leading-6 text-slate-700">{state.leadRecommendation.comparisonExplanation}</p></section>}

    <section className="overflow-hidden rounded-3xl border border-blue-200 bg-white shadow-[0_20px_60px_-35px_rgba(15,23,42,0.35)]"><div className="bg-gradient-to-r from-blue-950 via-slate-950 to-slate-900 p-7 text-white lg:p-9"><div className="flex justify-between gap-4"><div><span className="inline-flex items-center gap-2 rounded-full bg-blue-500/20 px-3 py-1 text-xs font-black uppercase tracking-wider text-blue-200"><Sparkles size={13} />{top.recommendationLabel}</span><h2 className="mt-4 text-3xl font-black">{top.brandName}</h2><p className="mt-1 text-sm text-slate-300">{top.category}</p></div><div className="text-right"><p className="text-5xl font-black">{top.score}</p><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Evidence-backed fit</p></div></div><p className="mt-6 max-w-4xl text-base leading-7 text-slate-200">{top.rationale}</p></div><div className="grid gap-8 p-7 lg:grid-cols-[1.15fr_0.85fr] lg:p-9"><div><h3 className="mb-5 flex items-center gap-2 text-sm font-black uppercase tracking-wider text-slate-900"><BarChart3 size={17} className="text-blue-600" />Fit profile</h3><FitBars item={top} /><h3 className="mb-3 mt-8 text-sm font-black uppercase tracking-wider text-slate-900">Validated evidence</h3><div className="space-y-2">{top.evidence.map((evidence) => <div key={evidence.id} className="rounded-xl bg-slate-50 p-3"><p className="text-sm font-bold text-slate-800">{evidence.title}</p><p className="mt-0.5 text-xs leading-5 text-slate-500">{evidence.description}</p></div>)}</div></div><aside className="space-y-4"><div className={`rounded-2xl border p-5 ${top.qualified ? "border-emerald-200 bg-emerald-50" : "border-rose-200 bg-rose-50"}`}><div className="flex items-center gap-2 font-black text-slate-900"><CircleDollarSign size={19} />{top.qualified ? "Financially Qualified" : "Not Financially Qualified"}</div><p className="mt-2 text-sm leading-6 text-slate-600">{top.investment.explanation}</p><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><p><span className="text-slate-500">Investment range</span><strong className="mt-1 block">{top.investment.requiredInvestment}</strong></p><p><span className="text-slate-500">Candidate capital</span><strong className="mt-1 block">{money(top.investment.candidateInvestableCapital)}</strong></p></div></div><Guidance item={top} />{top.concerns.length > 0 && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 className="flex items-center gap-2 font-black text-slate-900"><AlertTriangle size={18} className="text-amber-600" />Address directly</h3><ul className="mt-3 space-y-2 text-sm text-slate-700">{top.concerns.map((text) => <li key={text}>• {text}</li>)}</ul></div>}</aside></div></section>

    <section><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-slate-400">Comparison set</p><h2 className="mt-1 text-2xl font-black text-slate-950">Ranked alternatives</h2></div><p className="text-sm font-semibold text-slate-500">Presentation order: {state.presentationOrder.join(" → ")}</p></div><div className="grid gap-5 lg:grid-cols-2">{alternatives.map((item) => <article key={item.brandId} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-wider text-blue-600">#{item.rank} · {item.recommendationLabel}</span><h3 className="mt-2 text-xl font-black text-slate-900">{item.brandName}</h3><p className="text-xs text-slate-500">{item.category}</p></div><span className="text-3xl font-black text-slate-900">{item.score}</span></div><p className="my-5 text-sm leading-6 text-slate-600">{item.rationale}</p><FitBars item={item} /><div className={`mt-5 rounded-xl p-3 text-sm font-bold ${item.qualified ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{item.qualified ? <BadgeCheck className="mr-2 inline" size={16} /> : <AlertTriangle className="mr-2 inline" size={16} />}{item.qualified ? "Financially Qualified" : "Financial qualification blocks presentation"}</div></article>)}</div></section>

    {state.referralDecision && <section aria-label="Referral Gate" className="rounded-3xl border border-slate-200 bg-slate-950 p-7 text-white lg:flex lg:items-center lg:justify-between lg:p-9"><div className="flex gap-4"><span className={`h-fit rounded-2xl p-3 ${state.referralDecision.passed ? "bg-emerald-400/15 text-emerald-300" : "bg-amber-400/15 text-amber-300"}`}><ShieldCheck /></span><div><p className={`text-xs font-black uppercase tracking-[0.2em] ${state.referralDecision.passed ? "text-emerald-300" : "text-amber-300"}`}>Referral Gate · {state.referralDecision.gateLabel}</p><h2 className="mt-2 text-2xl font-black">{state.referralDecision.heading}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">{state.referralDecision.explanation}</p>{state.referralDecision.unresolvedReasons.length > 0 && <ul className="mt-3 space-y-1 text-xs text-amber-200">{state.referralDecision.unresolvedReasons.map((reason) => <li key={reason}>• {reason}</li>)}</ul>}<p className="mt-3 text-sm font-bold">Next action: {state.referralDecision.nextAction}</p></div></div>{state.referralDecision.passed && state.lifecycleAction && <Link href={`/crm/candidates/${state.candidate.id}/referral`} className="mt-6 inline-flex shrink-0 items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white hover:bg-blue-700 lg:mt-0">Prepare Referral <ArrowRight size={16} /></Link>}</section>}
  </main>;
}
