"use client";

import Link from "next/link";
import { useActionState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import type { CandidateBrandPresentationState, PresentationTalkingPoint } from "../models/CandidateBrandPresentationBrief";
import { advanceBrandPresentation } from "../actions/brand-presentation";
import { updateStrategyBuilder, type StrategyActionState } from "../actions/strategy-builder";

const reactions = { "strong-interest": "Strong Interest", interested: "Interested", neutral: "Neutral", "not-interested": "Not Interested" } as const;
const dispositions = { refer: "Refer", "continue-research": "Continue Research", hold: "Hold", remove: "Remove" } as const;
const initial: StrategyActionState = { status: "idle" };

function Points({ values, concern = false }: { values: PresentationTalkingPoint[]; concern?: boolean }) {
  return values.length ? <ul className="space-y-2">{values.map((item, index) => <li key={`${index}:${item.text}`} className="flex gap-2 text-sm leading-6 text-slate-700">{concern ? <AlertTriangle size={15} className="mt-1 shrink-0 text-amber-600" /> : <CheckCircle2 size={15} className="mt-1 shrink-0 text-teal-600" />}<span>{item.text} <span className="ml-1 text-[10px] font-black uppercase text-slate-400">{item.source}</span></span></li>)}</ul> : <p className="text-sm text-slate-400">Not Yet Available</p>;
}

export function CandidateBrandPresentationPage({ state, summary }: { state: CandidateBrandPresentationState | null; summary: boolean }) {
  const [result, action, pending] = useActionState(updateStrategyBuilder, initial);
  if (!state?.available) return <main className="mx-auto max-w-5xl p-8"><Link href={`/crm/candidates/${state?.candidateId ?? ""}/strategy`} className="text-sm font-bold text-slate-500">← Brand Strategy</Link><section className="mt-8 rounded-3xl border border-amber-200 bg-white p-8"><h1 className="text-2xl font-black">Brand Presentation unavailable</h1><p className="mt-2 text-sm text-slate-600">{state?.reason ?? "Candidate not found."}</p></section></main>;
  if (summary || state.historical) return <main className="mx-auto max-w-6xl space-y-6 p-6 lg:p-10"><header><Link href={`/crm/candidates/${state.candidateId}/strategy`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} />Brand Strategy</Link><p className="mt-6 text-xs font-black uppercase tracking-[0.2em] text-teal-600">{state.historical ? "Historical Brand Presentation" : "Brand Presentation Complete"}</p><h1 className="mt-1 text-3xl font-black">{state.candidateName}</h1><p className="mt-2 text-sm text-slate-600">Presented: {state.briefs.filter((item) => item.presentedAt).length} brands · Consultant reactions and final decisions remain separate from AI Match.</p></header>
    {result.message && <p className="rounded-xl bg-slate-100 p-3 text-sm font-bold">{result.message}</p>}
    <section className="grid gap-4 md:grid-cols-2">{state.briefs.map((brief) => <article key={brief.brandId} aria-label={`${brief.brandName} presentation summary`} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-4"><div><p className="text-xs font-black text-teal-700">Presentation #{brief.presentationOrder} · AI Rank #{brief.aiRank}</p><h2 className="text-xl font-black">{brief.brandName}</h2></div><p className="text-right text-sm font-black">AI Match {brief.aiMatch}%</p></div><p className="mt-3 text-sm"><strong>Reaction:</strong> {brief.candidateReaction ? reactions[brief.candidateReaction] : "Not captured"}</p>{brief.consultantNotes && <p className="mt-2 text-sm text-slate-600">{brief.consultantNotes}</p>}<div className="mt-4 border-t pt-4"><p className="text-xs font-black uppercase text-slate-500">Final Shortlist</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(dispositions).map(([value, label]) => state.historical ? brief.shortlistDisposition === value && <span key={value} className="rounded-lg bg-teal-50 px-3 py-2 text-xs font-black text-teal-700">{label}</span> : <form action={action} key={value}><input type="hidden" name="candidateId" value={state.candidateId} /><input type="hidden" name="brandId" value={brief.brandId} /><input type="hidden" name="kind" value="disposition" /><input type="hidden" name="disposition" value={value} /><button disabled={pending} aria-pressed={brief.shortlistDisposition === value} className={`rounded-lg border px-3 py-2 text-xs font-black ${brief.shortlistDisposition === value ? "border-teal-500 bg-teal-50 text-teal-700" : "border-slate-200"}`}>{label}</button></form>)}</div></div></article>)}</section>
    {!state.historical && <section className="rounded-2xl bg-slate-950 p-6 text-white"><h2 className="text-xl font-black">What should happen next?</h2>{state.briefs.some((item) => item.shortlistDisposition === "refer") ? <Link href={`/crm/candidates/${state.candidateId}/referral`} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black">Open Referral Studio <ArrowRight size={16} /></Link> : <p className="mt-2 text-sm text-slate-300">Choose Refer for at least one brand to prepare referrals. Otherwise continue research, schedule a follow-up, or review additional recommendations.</p>}</section>}
  </main>;
  const brief = state.briefs[state.activeIndex];
  const previous = state.briefs[state.activeIndex - 1]; const next = state.briefs[state.activeIndex + 1];
  return <main className="mx-auto max-w-6xl space-y-5 p-6 lg:p-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link href={`/crm/candidates/${state.candidateId}/strategy`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} />Brand Strategy</Link><p className="mt-4 text-xs font-black uppercase tracking-[0.2em] text-teal-600">Brand Presentation · {state.candidateName}</p><h1 className="mt-1 text-3xl font-black">{brief.brandName}</h1><p className="mt-1 text-sm text-slate-500">Brand {brief.presentationOrder} of {brief.presentationCount} · Presentation Order #{brief.presentationOrder} · AI Rank #{brief.aiRank}</p></div><div className="rounded-xl border bg-white px-5 py-3 text-right"><p className="text-2xl font-black">{brief.aiMatch}%</p><p className="text-xs font-bold text-slate-500">AI Match · {brief.recommendationConfidence}% confidence</p></div></header>
    <section className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><div className="space-y-5"><article className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-blue-600">30-Second Overview</p><p className="mt-2 text-sm leading-6 text-slate-700">{brief.overview}</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{brief.facts.map((fact) => <div key={fact.label} className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] font-black uppercase text-slate-400">{fact.label}</p><p className="mt-1 text-xs font-bold">{fact.value}</p></div>)}</div></article><article className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-teal-600">Why FranGroove Matched This Brand</p><p className="mt-2 text-sm leading-6 text-slate-700">{brief.matchRationale}</p><div className="mt-3"><Points values={brief.fitFactors} /></div></article><div className="grid gap-5 md:grid-cols-2"><article className="rounded-2xl border bg-white p-5"><h2 className="font-black">What to Emphasize</h2><div className="mt-3"><Points values={brief.emphasize} /></div></article><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-black text-amber-900">Address Directly</h2><div className="mt-3"><Points values={brief.concerns} concern /></div></article></div><article className="rounded-2xl border bg-white p-5"><h2 className="font-black">Questions to Ask</h2><div className="mt-3"><Points values={brief.questions} /></div></article></div>
      <aside><form key={brief.brandId} action={advanceBrandPresentation} className="sticky top-5 rounded-2xl border bg-white p-5 shadow-sm"><input type="hidden" name="candidateId" value={state.candidateId} /><input type="hidden" name="brandId" value={brief.brandId} /><input type="hidden" name="nextBrandId" value={next?.brandId ?? ""} /><h2 className="font-black">Candidate Reaction</h2><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(reactions).map(([value, label]) => <label key={value} className="cursor-pointer rounded-lg border p-3 text-xs font-bold focus-within:ring-2 focus-within:ring-blue-500"><input type="radio" name="reaction" value={value} defaultChecked={brief.candidateReaction === value} required className="mr-2 accent-blue-600" />{label}</label>)}</div><label className="mt-4 block text-xs font-black">Consultant Note<textarea name="notes" defaultValue={brief.consultantNotes} rows={5} placeholder="Capture the candidate's reaction or objection." className="mt-2 w-full rounded-lg border p-3 text-sm" /></label><button className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 p-3 text-sm font-black text-white">{next ? "Save & Next Brand" : "Complete Presentation"}<ArrowRight size={16} /></button>{previous && <Link href={`/crm/candidates/${state.candidateId}/strategy/presentation?brandId=${encodeURIComponent(previous.brandId)}`} className="mt-3 flex justify-center text-sm font-black text-slate-600">Previous Brand</Link>}</form></aside></section>
  </main>;
}
