import {test,expect} from '@playwright/test';
for(const width of [1440,390])test(`assessment sharing controls and replacement at ${width}px`,async({page,context},info)=>{
 test.setTimeout(120000);page.setDefaultTimeout(10000);await page.setViewportSize({width,height:950});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/login');await page.getByLabel('Email address').fill('assessment-consultant@example.test');await page.getByLabel('Password').fill('Local-assessment-only-2026!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/crm$/);
 await page.goto('/crm/candidates/new');await page.getByLabel('First Name').fill('Sharing');await page.getByLabel('Last Name').fill('Proof'+width);await page.getByLabel('Email').fill(`sharing-${width}-${Date.now()}@example.test`);await page.getByRole('button',{name:'Create Candidate',exact:true}).click();await page.getByRole('link',{name:'Open candidate record',exact:true}).click();
 await expect(page).toHaveURL(/\/crm\/candidates\/cand_/);const path=new URL(page.url()).pathname;await expect(page.getByRole('navigation',{name:'Assessment actions'}).getByRole('link',{name:'Share Assessment',exact:true})).toBeVisible();await page.getByRole('navigation',{name:'Candidate journey'}).getByRole('link',{name:'Pipeline',exact:true}).click();const card=page.locator(`[data-candidate-id="${path.split('/').at(-1)}"]`);await card.getByRole('link',{name:'Share Assessment',exact:true}).click();await expect(page).toHaveURL(/#assessment-invitation$/);
 const controls=page.getByRole('region',{name:'Share assessment controls'});await expect(controls).toContainText('Not started');await controls.getByRole('button',{name:'Generate Assessment Link',exact:true}).click();const open=controls.getByRole('link',{name:'Open Assessment',exact:true});await expect(open).toHaveAttribute('target','_blank');await expect(open).toHaveAttribute('rel','noopener noreferrer');const firstPath=await open.getAttribute('href');expect(firstPath?.startsWith('/assessment/invitation/')).toBe(true);
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('blocked')}}}));await controls.getByRole('button',{name:'Copy Assessment Link',exact:true}).click();await expect(controls.getByRole('alert')).toContainText('Could not copy');
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(value:string)=>{Object.defineProperty(window,'copiedAssessment',{configurable:true,value});}}}));await controls.getByRole('button',{name:'Copy Assessment Link',exact:true}).click();await expect(controls.getByRole('status')).toContainText('Assessment link copied');expect(await page.evaluate(()=>new URL((window as unknown as {copiedAssessment:string}).copiedAssessment).origin===location.origin)).toBe(true);
 const popupPromise=context.waitForEvent('page');await open.click();const popup=await popupPromise;await expect(popup.getByRole('heading',{name:'Tell us a little about yourself'})).toBeVisible();await popup.close();await expect(page).toHaveURL(new RegExp(path));
 await page.reload();await expect(controls).toContainText('Invitation active');const replace=controls.getByRole('button',{name:'Replace Assessment Link',exact:true});await expect(replace).toBeDisabled();await expect(controls).toContainText('unfinished assessment progress unusable');await controls.getByRole('checkbox').check();await replace.click();await expect(open).toBeVisible();const secondPath=await open.getAttribute('href');expect(secondPath===firstPath).toBe(false);const old=await context.newPage();await old.goto(firstPath!);await expect(old.getByRole('heading',{name:'Assessment link unavailable'})).toBeVisible();await old.close();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`sharing-${width}.png`),fullPage:true});expect(errors).toEqual([]);
});
