import { expect, test, type Page } from "@playwright/test";

async function fillIntake(page: Page) {
  await page.getByLabel("First name").fill("Alex"); await page.getByLabel("Preferred name (optional)").fill("Lex"); await page.getByLabel("Last name").fill("Morgan"); await page.getByLabel("Email",{exact:true}).fill("alex.morgan@example.com"); await page.getByLabel("Mobile phone").fill("407-555-0132"); await page.getByLabel("Street address").fill("100 Conference Way"); await page.getByLabel("Address line 2 (optional)").fill("Suite 4"); await page.getByLabel("City").fill("Orlando"); await page.getByLabel("State/Province").fill("FL"); await page.getByLabel("ZIP/Postal code").fill("32801"); await page.getByLabel("Current occupation/title").fill("Operations Executive"); await page.getByLabel("Current employer (optional)").fill("Acme"); await page.getByLabel("LinkedIn profile (optional)").fill("https://linkedin.com/in/alex-morgan"); await page.getByLabel("Have you owned a business before?").selectOption("yes"); await page.getByLabel(/Briefly describe/).fill("Previously operated a local services company."); await page.getByLabel("Have you previously explored franchise ownership?").selectOption("yes"); await page.getByLabel("Preferred contact method").selectOption("text"); await page.getByLabel("Best general contact time").selectOption("afternoon");
}
async function answerVisibleQuestions(page: Page) { const groups=page.locator("fieldset");for(let i=0;i<await groups.count();i++){const group=groups.nth(i);if(!(await group.locator("input:checked").count()))await group.locator("input").first().check();} }

test("intake, consent, exclusive choices, conditional follow-up, back and refresh resume", async ({page})=>{
  await page.goto("/assessment/start"); await expect(page.getByRole("heading",{name:"Tell us a little about yourself"})).toBeVisible(); await page.getByRole("button",{name:"Continue"}).click(); await expect(page.getByLabel("First name")).toBeFocused(); await fillIntake(page); await page.getByRole("button",{name:"Continue"}).click(); await expect(page.getByRole("heading",{name:"Discover Your Franchise Ownership Profile"})).toBeVisible(); await expect(page.getByRole("button",{name:"Begin assessment"})).toBeDisabled(); await page.getByLabel("I understand and wish to continue.").check(); await page.getByRole("button",{name:"Begin assessment"}).click();
  await page.getByLabel("Build long-term wealth").check(); await page.getByLabel("Replace or exceed my current income").check(); await expect(page.getByRole("heading",{name:"Of the motivations you selected, which one matters most?"})).toBeVisible(); await page.getByLabel("I'm still figuring that out").check(); await expect(page.getByRole("checkbox",{name:/Build long-term wealth/})).not.toBeChecked(); await page.getByRole("checkbox",{name:/Build long-term wealth/}).check(); await expect(page.getByLabel("I'm still figuring that out")).not.toBeChecked(); await answerVisibleQuestions(page); await page.reload(); await expect(page.getByText("Step 1 of 6")).toBeVisible(); await expect(page.getByRole("checkbox",{name:/Build long-term wealth/})).toBeChecked(); await page.getByRole("button",{name:"Continue"}).click(); await expect(page.getByText("Step 2 of 6")).toBeVisible(); await page.getByRole("button",{name:"Back"}).click(); await expect(page.getByText("Step 1 of 6")).toBeVisible();
});

test("complete assessment creates deterministic candidate intelligence and cleanup preserves canonical demo", async ({page})=>{
  await page.goto("/assessment/start"); await fillIntake(page); await page.getByRole("button",{name:"Continue"}).click(); await page.getByLabel("I understand and wish to continue.").check(); await page.getByRole("button",{name:"Begin assessment"}).click();
  for(let section=1;section<=6;section++){await answerVisibleQuestions(page);await page.getByRole("button",{name:"Continue"}).click();}
  await expect(page.getByRole("heading",{name:/concerns you most/i})).toBeVisible(); await page.getByLabel("Losing financial security").check(); await page.getByLabel("Replacing my income").check(); await page.locator('fieldset').last().getByLabel("Losing financial security").check(); await page.getByRole("button",{name:"Build my profile"}).click(); await expect(page.getByText("Building your Franchise Ownership Profile")).toBeVisible(); await expect(page.getByRole("heading",{name:"Your Franchise Ownership Profile"})).toBeVisible({timeout:15_000}); await expect(page.getByText("Questions Worth Discussing With Your Consultant")).toBeVisible(); await expect(page.getByText(/not independently verified/i)).toBeVisible();
  await page.goto("/login"); await page.getByRole("button",{name:/Enter Conference Demo as/i}).click(); await expect(page).toHaveURL(/\/crm$/); await expect(page.getByText("New Candidate Intelligence Available")).toBeVisible(); await page.getByRole("link",{name:"Open Candidate Intelligence"}).click(); await expect(page.getByRole("heading",{name:"Lex Morgan"})).toBeVisible(); await expect(page.getByRole("heading",{name:"Discovery Priorities"})).toBeVisible(); await expect(page.getByRole("heading",{name:"Franchise Model Implications"})).toBeVisible(); await expect(page.getByText(/Capability evidence:/)).toBeVisible(); await expect(page.getByText(/Gmail activity.*have not been created/)).toBeVisible();
  page.on("dialog",dialog=>dialog.accept()); await page.getByRole("button",{name:"Clear Conference Assessments"}).click(); await expect(page).toHaveURL(/\/crm$/); await expect(page.getByText("New Candidate Intelligence Available")).toHaveCount(0); await expect(page.getByText("Jared",{exact:false}).first()).toBeVisible(); await expect(page.getByText("Sarah",{exact:false}).first()).toBeVisible();
});

test("candidate assessment has no horizontal overflow at IFPG device sizes",async({page})=>{for(const viewport of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1366,height:768}]){await page.setViewportSize(viewport);await page.goto("/assessment/start");const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow,`${viewport.width}x${viewport.height}`).toBeFalsy();}});
