import {test,expect} from '@playwright/test';
for(const width of [1440,768,390])test(`Pack 002 candidate-to-referral journey at ${width}px`,async({page},info)=>{
 test.setTimeout(180000);page.setDefaultTimeout(15000);await page.setViewportSize({width,height:1000});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/login');await page.getByLabel('Email address',{exact:true}).fill(process.env.IFPG_EMAIL!);await page.getByLabel('Password',{exact:true}).fill(process.env.IFPG_PASSWORD!);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/crm$/);
 await expect(page.getByRole('region',{name:'Tasks and meetings'})).toContainText('Household alignment');
 await page.getByRole('link',{name:'Open Tasks',exact:true}).click();await expect(page.getByRole('heading',{name:'Tasks',exact:true})).toBeVisible();await page.getByRole('button',{name:/^All /}).click();await page.getByRole('button',{name:'View Household alignment follow-up',exact:true}).click();await page.getByRole('link',{name:'Open Maya Bennett',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Consultant Brief'})).toBeVisible();await page.getByRole('link',{name:'Assessments & Documents',exact:true}).first().click();await expect(page.getByRole('heading',{name:'Assessments & Documents',exact:true})).toBeVisible();
 for(const [label,title] of [['Completed Assessment','Completed Assessment'],['Candidate Profile','Franchise Ownership Profile'],['Consultant Intelligence Report','Candidate Intelligence Report']]){await page.getByRole('link',{name:label,exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Download PDF',exact:true}).click();const download=await downloadPromise;await download.saveAs(info.outputPath(label.replaceAll(' ','-')+'.pdf'));expect(await download.failure()).toBeNull();}
 await page.getByRole('link',{name:'Discovery Copilot',exact:true}).last().click();await expect(page.getByRole('heading',{name:'What to learn before recommending brands'})).toBeVisible();
 const finding=page.getByRole('textbox',{name:'Finding',exact:true}).first();await finding.fill('Local Pack 002 proof: household priorities reviewed; follow-up remains required.');await page.getByRole('button',{name:'Save finding',exact:true}).first().click();await expect(page.getByText('Discovery finding saved.',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Candidate 360',exact:false}).first().click();await page.getByRole('navigation',{name:'Candidate journey'}).getByRole('link',{name:'Brand Referral Engine',exact:true}).click();
 const cards=page.locator('[data-brand-result]');await expect(cards).toHaveCount(6);await cards.nth(0).getByRole('button',{name:/^Compare /}).click();await cards.nth(1).getByRole('button',{name:/^Compare /}).click();await expect(page.locator('#brand-comparison')).toContainText('appears before');
 await cards.first().getByRole('button',{name:'Select for Referral',exact:true}).click();await expect(cards.first().getByRole('status')).toContainText('Brand selected');
 await cards.first().getByRole('link',{name:/Brand Intelligence$/}).click();await expect(page.getByRole('heading',{name:'Evidence & Confidence',exact:true})).toBeVisible();await page.getByText('Review detailed evidence and provenance',{exact:true}).click();await page.getByRole('navigation',{name:'Candidate context'}).getByRole('link',{name:/Return to .*Brand Referral Engine/}).click();
 await page.locator('[data-brand-result]').first().getByRole('link',{name:/^Prepare handoff/}).click();await expect(page.getByRole('heading',{name:'Referral Readiness & Preparation',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Prepare Referral',exact:true})).toBeVisible();await page.getByLabel('Consultant recommendation for the franchisor').fill('Synthetic local demonstration. Confirm household runway and territory before an introduction.');await page.getByRole('button',{name:'Save Referral Preparation',exact:true}).click();await expect(page.getByRole('status')).toContainText('Referral preparation saved');
 const packetPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Generate Referral Packet PDF',exact:true}).click();const packet=await packetPromise;await packet.saveAs(info.outputPath('Referral-Packet.pdf'));expect(await packet.failure()).toBeNull();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('referral.png'),fullPage:true});
 await page.getByRole('link',{name:'Calendar',exact:true}).last().click();await expect(page.getByRole('button',{name:'week',exact:true})).toBeVisible();await page.getByRole('button',{name:'month',exact:true}).click();await expect(page.getByRole('region',{name:'Calendar grid'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('calendar.png'),fullPage:true});
 await page.getByRole('navigation',{name:'Schedule navigation'}).getByRole('link',{name:'Mission Control',exact:true}).click();await expect(page.getByRole('heading',{name:'Mission Control',exact:true})).toBeVisible();expect(errors).toEqual([]);
});
test('Pack 002 normal task and meeting forms persist and protected documents deny foreign users',async({page,browser})=>{
 test.setTimeout(150000);page.setDefaultTimeout(15000);
 await page.goto('/login');await page.getByLabel('Email address',{exact:true}).fill(process.env.IFPG_EMAIL!);await page.getByLabel('Password',{exact:true}).fill(process.env.IFPG_PASSWORD!);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/crm$/);
 await page.getByRole('link',{name:'Open Tasks',exact:true}).click();await page.getByRole('button',{name:'New Task',exact:true}).click();await page.getByRole('textbox',{name:'Task title',exact:true}).fill('Browser proof follow-up');await page.getByLabel('Due date and time (Eastern)',{exact:true}).fill('2026-09-12T09:00');await page.getByRole('combobox',{name:'Candidate',exact:true}).selectOption({label:'Daniel Reed'});await page.getByRole('button',{name:'Save Task',exact:true}).click();await page.getByRole('button',{name:/^All /}).click();
 const task=page.locator('[data-task-id]').filter({hasText:'Browser proof follow-up'});await expect(task).toBeVisible();await task.getByRole('button',{name:'Complete',exact:true}).click();await expect(task.getByRole('button',{name:'Reopen',exact:true})).toBeVisible();await task.getByRole('button',{name:'Reopen',exact:true}).click();await task.getByRole('button',{name:'View Browser proof follow-up',exact:true}).click();await task.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('textbox',{name:'Task title',exact:true}).fill('Browser proof updated');await page.getByRole('button',{name:'Save Changes',exact:true}).click();const updated=page.locator('[data-task-id]').filter({hasText:'Browser proof updated'});await expect(updated).toBeVisible();await updated.getByRole('button',{name:'Delete',exact:true}).click();await expect(updated).toHaveCount(0);
 await page.getByRole('navigation',{name:'Schedule navigation'}).getByRole('link',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'Add Meeting',exact:true}).click();await page.getByRole('textbox',{name:'Title',exact:true}).fill('Browser proof meeting');await page.getByLabel('Start Date',{exact:true}).fill('2026-09-12');await page.getByLabel('Start Time',{exact:true}).selectOption('09:00');await page.getByRole('button',{name:'Schedule Meeting',exact:true}).click();await page.getByRole('button',{name:'upcoming',exact:true}).click();const meeting=page.locator('article').filter({has:page.getByRole('heading',{name:'Browser proof meeting',exact:true})});await expect(meeting).toBeVisible();await meeting.getByText('View Meeting',{exact:true}).click();await meeting.getByRole('radio',{name:'Cancelled',exact:true}).check();await meeting.getByRole('button',{name:'Save',exact:true}).first().click();await expect(meeting).toHaveCount(0);
 await page.getByRole('navigation',{name:'Schedule navigation'}).getByRole('link',{name:'Mission Control',exact:true}).click();await page.getByRole('region',{name:'Tasks and meetings'}).getByRole('link',{name:'Household alignment follow-up',exact:true}).click();await page.getByRole('link',{name:'Assessments & Documents',exact:true}).first().click();await page.getByRole('link',{name:'Consultant Intelligence Report',exact:true}).click();await expect(page.getByRole('heading',{name:'Candidate Intelligence Report',exact:true})).toBeVisible();const path=await page.getByRole('link',{name:'Download PDF',exact:true}).getAttribute('href');expect(path).toBeTruthy();
 const context=await browser.newContext({baseURL:'http://127.0.0.1:3100'}),foreign=await context.newPage();try{const anon=await context.request.get(path!);expect(anon.headers()['content-type']).not.toContain('application/pdf');await foreign.goto('/login');await foreign.getByLabel('Email address',{exact:true}).fill('assessment-other@example.test');await foreign.getByLabel('Password',{exact:true}).fill('Local-assessment-only-2026!');await foreign.getByRole('button',{name:'Sign in',exact:true}).click();await expect(foreign).toHaveURL(/\/crm$/);for(const route of [path!,path!.split('/documents/')[0]+'/documents',path!.split('/documents/')[0]+'/referral/packet']){const response=await context.request.get(route);expect(response.status()).toBe(404);expect(response.headers()['content-type']??'').not.toContain('application/pdf');}}finally{await context.close();}
});
