import {expect,test} from '@playwright/test';
import sharp from 'sharp';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,key=process.env.SUPABASE_SERVICE_ROLE_KEY!,email=process.env.PACK2A_TEST_EMAIL!,password=process.env.PACK2A_TEST_PASSWORD!;
test('hosted-composition media, frozen branding, image reuse and V2 round trip',async({page,request,context})=>{
 test.setTimeout(180000);
 const create=await request.post(`${url}/auth/v1/admin/users`,{headers:{apikey:key,Authorization:`Bearer ${key}`},data:{email,password,email_confirm:true}});expect(create.status()).toBe(200);
 await page.goto('/login');await page.getByLabel('Email address').fill(email);await page.getByLabel('Password').fill(password);await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/onboarding$/);await page.getByLabel('Organization name').fill('Synthetic Studio 001B');await page.getByLabel('Your display name').fill('Alex Synthetic');await page.getByRole('button',{name:'Create workspace'}).click();await expect(page).toHaveURL(/\/crm$/);
 await page.goto('/crm/campaigns/new');await page.getByLabel('Campaign name').fill('Synthetic media proof');await page.getByLabel('Subject line').fill('Your next chapter');await page.getByRole('textbox',{name:'Email canvas'}).fill('Ownership on your terms.');
 await page.getByRole('button',{name:'Media library',exact:true}).click();
 for(const [name,width,height,color] of [['../../synthetic-logo.png',120,120,'#0f766e'],['synthetic-campaign.png',800,400,'#2563eb']] as const){const bytes=await sharp({create:{width,height,channels:3,background:color}}).png().toBuffer();await page.getByLabel('Upload image',{exact:true}).setInputFiles({name,mimeType:'image/png',buffer:bytes});await expect(page.getByRole('button',{name:'Select image 1',exact:true})).toBeVisible();await expect(page.getByText('Preparing your image...')).toHaveCount(0);}
 await expect(page.getByRole('button',{name:/Select image/})).toHaveCount(2);await page.getByRole('button',{name:'Select image 1',exact:true}).click();const canvas=page.getByRole('textbox',{name:'Email canvas'});await expect(canvas.locator('img')).toBeVisible();await expect.poll(()=>canvas.locator('img').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBe(800);
 const publicOrigin=new URL(page.url()).origin;
 for(const [mime,body,status] of [['image/svg+xml',Buffer.from('<svg/>'),400],['image/jpeg',await sharp({create:{width:8,height:8,channels:3,background:'#fff'}}).png().toBuffer(),400],['image/png',Buffer.from('malformed'),400],['image/png',Buffer.alloc(3145729),413]] as const){const bad=await page.request.post('/api/marketing/media',{headers:{origin:publicOrigin,'content-type':mime},data:body});expect(bad.status()).toBe(status);}
 const foreignOrigin=await page.request.post('/api/marketing/media',{headers:{origin:'https://evil.test','content-type':'image/png'},data:Buffer.from('bad')});expect(foreignOrigin.status()).toBe(403);
 const library=await (await page.request.get('/api/marketing/media')).json();expect(library.assets).toHaveLength(2);
 const anonymous=await request.get('/api/marketing/media');expect(anonymous.status()).toBe(403);
 const otherContext=await context.browser()!.newContext(),other=await otherContext.newPage();
 const otherEmail='other-'+email;const otherUser=await request.post(`${url}/auth/v1/admin/users`,{headers:{apikey:key,Authorization:`Bearer ${key}`},data:{email:otherEmail,password,email_confirm:true}});expect(otherUser.status()).toBe(200);
 await other.goto(publicOrigin+'/login');await other.getByLabel('Email address').fill(otherEmail);await other.getByLabel('Password').fill(password);await other.getByRole('button',{name:'Sign in'}).click();await expect(other).toHaveURL(/\/onboarding$/);await other.getByLabel('Organization name').fill('Other synthetic tenant');await other.getByLabel('Your display name').fill('Other consultant');await other.getByRole('button',{name:'Create workspace'}).click();await expect(other).toHaveURL(/\/crm$/);
 expect((await other.request.get(publicOrigin+'/api/marketing/media/'+library.assets[0].public_id)).status()).toBe(404);expect((await (await other.request.get(publicOrigin+'/api/marketing/media')).json()).assets).toHaveLength(0);await otherContext.close();
 await page.getByText('Company branding & signature',{exact:true}).click();await page.getByLabel('Sender postal address').fill('100 Synthetic Lane, Example, NY 10001');await page.getByRole('button',{name:'Choose company logo'}).click();await page.getByRole('button',{name:'Select image 2',exact:true}).click();await page.getByRole('button',{name:'Save company branding'}).click();await expect(page.getByText('Settings saved.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Refresh campaign branding'}).click();await expect(page.getByText('Campaign branding refreshed.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Add signature',exact:true}).click();await expect(canvas).toContainText('Alex Synthetic');
 await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page).toHaveURL(/\/crm\/campaigns\/camp_/);const campaignUrl=page.url();await page.goto('/crm/campaigns');await page.goto(campaignUrl);await expect(canvas.locator('img')).toBeVisible();await expect(canvas).toContainText('Alex Synthetic');
 await page.getByRole('button',{name:'Preview email',exact:true}).click();const frame=page.frameLocator('iframe[title="Email preview"]');await expect(frame.locator('img')).toBeVisible();await expect(frame.getByText('100 Synthetic Lane, Example, NY 10001')).toBeVisible();await expect(frame.locator('a')).toHaveCount(0);
 await page.getByRole('button',{name:'Media library',exact:true}).click();await expect(page.getByRole('button',{name:/Select image/})).toHaveCount(2);await page.getByRole('button',{name:'Close library'}).click();
 await page.getByText('Company branding & signature',{exact:true}).click();await page.getByLabel('Sender postal address').fill('200 Changed Settings Lane, Example, NY 10001');await page.getByRole('button',{name:'Save company branding'}).click();await expect(page.getByText('Settings saved.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page.getByText('Draft saved',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Preview email',exact:true}).click();await expect(frame.getByText('100 Synthetic Lane, Example, NY 10001')).toBeVisible();
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Mobile preview',exact:true}).click();await expect(frame.locator('img')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
 await expect(page.getByText('Visual campaign delivery will be enabled after final delivery certification.')).toBeVisible();await expect(page.getByRole('button',{name:/Confirm.*send/i})).toHaveCount(0);
 const second=await context.newPage();await second.goto(campaignUrl);await expect(second.getByLabel('Campaign name')).toHaveValue('Synthetic media proof');await page.getByLabel('Campaign name').fill('New revision');await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page.getByText('Draft saved',{exact:true})).toBeVisible();await second.getByLabel('Campaign name').fill('Stale revision');await second.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(second.getByRole('alert').filter({hasText:'another tab'})).toBeVisible();
});
