import { expect, test, type Page } from "@playwright/test";
async function enter(page: Page) { await page.goto("/login"); await page.getByRole("button", { name: /Enter Conference Demo as/i }).click(); await expect(page).toHaveURL(/\/crm$/); await page.goto("/crm/campaigns/new?audience=list&id=list_demo_newsletter"); await expect(page.getByRole("textbox", { name: "Email canvas" })).toBeVisible(); }
async function metadata(page: Page) { await page.getByLabel("Campaign name").fill("Ownership starts with a conversation"); await page.getByLabel("Subject line").fill("A new chapter for {{first_name}}"); await page.getByLabel("Preheader", { exact: true }).fill("Explore business ownership on your terms."); await page.getByLabel("Sender display name").fill("Alex Morgan"); await page.getByLabel("Reply-to address").fill("alex@example.test"); }
test("visual composition, fonts, blocks, server preview and durable draft round trip", async ({ page }) => {
  const errors: string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await enter(page);await metadata(page);
  const canvas=page.getByRole('textbox',{name:'Email canvas'});
  await canvas.fill('Build a future that fits you.');await canvas.press('Control+a');
  await page.getByLabel('Font family').selectOption('georgia');await page.getByLabel('Font size').selectOption('24');await page.getByRole('button',{name:'Bold',exact:true}).click();await page.getByRole('button',{name:'Italic',exact:true}).click();await page.getByRole('button',{name:'Underline',exact:true}).click();
  await page.getByLabel('Text color').selectOption('#047857');await page.getByRole('button',{name:'Align center',exact:true}).click();
  await page.getByLabel('HTTPS link',{exact:true}).fill('javascript:alert(1)');await page.getByRole('button',{name:'Apply link',exact:true}).click();await expect(page.getByText('Enter a valid HTTPS link.')).toBeVisible();
  await page.getByLabel('HTTPS link',{exact:true}).fill('https://example.test/opportunities');await page.getByRole('button',{name:'Apply link',exact:true}).click();
  await canvas.press('Control+End');await canvas.press('Enter');await page.getByLabel('Insert merge field').selectOption('first_name');
  await page.getByRole('button',{name:'Add button',exact:true}).click();
  await page.getByRole('button',{name:'Add divider',exact:true}).click();await page.getByRole('button',{name:'Add spacer',exact:true}).click();await page.getByRole('button',{name:'Add signature',exact:true}).click();await page.getByRole('button',{name:'Image + text',exact:true}).click();
  for (const block of ['.studio-button', '.studio-divider', '.studio-spacer', '.studio-signature', '.studio-columns']) await expect(canvas.locator(block)).toHaveCount(1);
  await page.getByRole('button',{name:'Refresh counts',exact:true}).click();await expect(page.getByText('Sendable').locator('..')).toContainText('3');
  await page.getByRole('button',{name:'Preview email',exact:true}).click();await expect(page.locator('iframe[title="Email preview"]')).toBeVisible();
  const frame=page.frameLocator('iframe[title="Email preview"]');await expect(frame.getByText('Build a future that fits you.')).toBeVisible();await expect(frame.locator('strong')).toContainText('Build a future');await expect(frame.locator('a')).toHaveCount(0);await expect(frame.getByText('Unsubscribe',{exact:true})).toBeVisible();await expect(frame.getByText('Jordan',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page).toHaveURL(/\/crm\/campaigns\/camp_/);await expect(page.getByText('Draft saved',{exact:true})).toBeVisible();await page.reload();await expect(canvas).toContainText('Build a future');await expect(canvas.locator('span[style*="Georgia"]')).toBeVisible();
  for (const block of ['.studio-button', '.studio-divider', '.studio-spacer', '.studio-signature', '.studio-columns']) await expect(canvas.locator(block)).toHaveCount(1);
  await page.locator('.studio-editor').screenshot({path:'.next-dev/marketing-studio-001a/desktop.png'});
  await page.getByRole('button',{name:'Duplicate',exact:true}).click();await expect(page.getByLabel('Campaign name')).toHaveValue('Ownership starts with a conversation copy');
  expect(errors).toEqual([]);
});
test("390px editing, image properties, stacked server preview, and hostile paste",async({page})=>{
  await page.setViewportSize({width:390,height:844});await enter(page);await metadata(page);const canvas=page.getByRole('textbox',{name:'Email canvas'});await canvas.fill('Small steps. New possibilities.');
  await canvas.evaluate(element=>{const data=new DataTransfer();data.setData('text/html','<script>window.studioXss=1</script><p style="position:absolute" onclick="alert(1)">Safe pasted words</p><img src=x onerror="alert(1)">');element.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});
  await expect(canvas).toContainText('Safe pasted words');await expect(canvas.locator('script,img,[onclick]')).toHaveCount(0);
  await canvas.press('Control+End');await page.getByRole('button',{name:'Image + text',exact:true}).click();
  await page.getByRole('button',{name:'Preview email',exact:true}).click();await page.getByRole('button',{name:'Mobile preview',exact:true}).click();
  const columns=page.frameLocator('iframe').locator('.email-column');await expect(columns).toHaveCount(2);const bounds=await columns.evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width};}));expect(bounds[1].y).toBeGreaterThan(bounds[0].y);expect(Math.abs(bounds[1].x-bounds[0].x)).toBeLessThan(2);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);
  await page.locator('.studio-editor').screenshot({path:'.next-dev/marketing-studio-001a/mobile.png'});
  await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page).toHaveURL(/\/crm\/campaigns\/camp_/);
  await page.getByRole('textbox',{name:'Email canvas'}).press('Control+End');await page.getByRole('button',{name:'Image placeholder',exact:true}).click();await canvas.locator('.studio-image').last().click();await expect(page.getByLabel('Alt text',{exact:true})).toBeVisible();await page.getByLabel('Alt text',{exact:true}).fill('Consultant logo');await page.getByLabel('Image width',{exact:true}).fill('240');await expect(page.getByRole('button',{name:'Replace image — media library forthcoming'})).toBeDisabled();await page.getByRole('button',{name:'Remove block',exact:true}).click();
});
test('explicit V1 visual copy preserves the original campaign and envelope',async({page})=>{
 await enter(page);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Classic text campaign',exact:true}).click();await page.getByLabel('Campaign name').fill('Legacy original');await page.getByLabel('Subject line').fill('Legacy subject');await page.getByLabel('Preview text').fill('Legacy preview');await page.getByLabel('Sender display name').fill('Legacy sender');await page.getByLabel('Reply-to address').fill('legacy@example.test');await page.getByLabel('Email heading').fill('Legacy heading');await page.getByLabel('Body content').fill('First line\nSecond line');await page.getByLabel('CTA label').fill('Explore');await page.getByLabel('CTA URL').fill('https://example.test');await page.getByLabel('Footer content').fill('Original footer');await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page).toHaveURL(/\/crm\/campaigns\/camp_/);const original=page.url();await page.getByRole('button',{name:'Create visual-editor copy'}).click();await expect(page).not.toHaveURL(original);await expect(page.getByLabel('Subject line')).toHaveValue('Legacy subject');await expect(page.getByLabel('Preheader',{exact:true})).toHaveValue('Legacy preview');await expect(page.getByRole('textbox',{name:'Email canvas'})).toContainText('Original footer');await expect(page.getByLabel('Campaign audience')).toHaveValue('list_demo_newsletter');await page.goto(original);await expect(page.getByLabel('Body content')).toHaveValue('First line\nSecond line');await expect(page.getByLabel('Campaign name')).toHaveValue('Legacy original');
});
test('stale editor tab keeps its unsaved content and cannot overwrite a newer revision',async({page,context})=>{
 await enter(page);await metadata(page);await page.getByRole('textbox',{name:'Email canvas'}).fill('Original');await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page).toHaveURL(/\/crm\/campaigns\/camp_/);
 const second=await context.newPage();await second.goto(page.url());await expect(second.getByRole('textbox',{name:'Email canvas'})).toBeVisible();
 await page.getByLabel('Campaign name').fill('Newest saved revision');await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page.getByText('Draft saved',{exact:true})).toBeVisible();
 await second.getByLabel('Campaign name').fill('Stale unsaved revision');await second.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(second.getByRole('alert').filter({hasText:'another tab'})).toContainText('another tab');await expect(second.getByLabel('Campaign name')).toHaveValue('Stale unsaved revision');
 await page.reload();await expect(page.getByLabel('Campaign name')).toHaveValue('Newest saved revision');
});
test('list controls and undo/redo preserve structured editing',async({page})=>{
 await enter(page);const canvas=page.getByRole('textbox',{name:'Email canvas'});await canvas.fill('First opportunity');await page.getByRole('button',{name:'Bulleted list',exact:true}).click();await expect(canvas.locator('ul')).toContainText('First opportunity');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(canvas.locator('ul')).toHaveCount(0);await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(canvas.locator('ul')).toHaveCount(1);await page.getByRole('button',{name:'Numbered list',exact:true}).click();await expect(canvas.locator('ol')).toContainText('First opportunity');await page.getByRole('button',{name:'Preview email',exact:true}).click();await expect(page.frameLocator('iframe').locator('ol')).toContainText('First opportunity');
});
