"use server";
import {revalidatePath} from "next/cache";import {z} from "zod";import {resolveWorkspaceComposition} from "@/feature/platform/composition/resolveWorkspaceComposition";import {mappedInput,MAX_IMPORT_ROWS} from "../import/csv";import type {ContactBulkOperation,ContactImportMapping,ContactImportResult} from "../models/Contact";
async function repo(){const r=await resolveWorkspaceComposition();if(r.status!=="resolved")throw new Error("An active workspace is required.");return r.composition.dependencies.contacts;}
const nameSchema=z.string().trim().min(1).max(100);
export async function createTagAction(form:FormData){const name=nameSchema.parse(form.get("name"));await (await repo()).createTag(name);revalidatePath("/crm/contacts");revalidatePath("/crm/contacts/lists");}
export async function createListAction(form:FormData){const name=nameSchema.parse(form.get("name"));await (await repo()).createList(name);revalidatePath("/crm/contacts");revalidatePath("/crm/contacts/lists");}
export async function renameListAction(id:string,form:FormData){const name=nameSchema.parse(form.get("name"));await (await repo()).renameList(id,name);revalidatePath("/crm/contacts/lists");}
export async function bulkOrganizeAction(ids:string[],operation:ContactBulkOperation,target:string){if(!ids.length||ids.length>50)throw new Error("Select between 1 and 50 contacts on this page.");await (await repo()).bulkOrganize(ids,operation,target);revalidatePath("/crm/contacts");}
export async function importContactsAction(payload:{rows:Record<string,string>[];mapping:ContactImportMapping;tagIds:string[];listId?:string;defaultSource?:string}):Promise<ContactImportResult>{if(payload.rows.length>MAX_IMPORT_ROWS)throw new Error(`Import no more than ${MAX_IMPORT_ROWS} contacts at once.`);const inputs=payload.rows.map(r=>mappedInput(r,payload.mapping,payload.defaultSource)).filter(x=>x!==null);const result=await (await repo()).importContacts(inputs,{tagIds:payload.tagIds,listId:payload.listId,defaultSource:payload.defaultSource});result.invalid+=payload.rows.length-inputs.length;revalidatePath("/crm/contacts");revalidatePath("/crm/contacts/lists");return result;}
