"use client";

import { useActionState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, CircleDashed, ExternalLink, ListChecks, SkipForward, X } from "lucide-react";
import { createPlaybookTask, decidePlaybookStep, type PlaybookActionState } from "../actions/playbook-actions";
import type { CandidateEngagementPlaybook, CandidateEngagementStep } from "../models/CandidateEngagementPlaybook";

const initial: PlaybookActionState = { status: "idle" };

export function EngagementPlaybookPage({ playbook }: { playbook: CandidateEngagementPlaybook }) {
  const current = playbook.steps.find((item) => item.stepId === playbook.currentStepId);
  const upcoming = playbook.steps.filter((item) => item.status === "recommended" && item.stepId !== current?.stepId);
  const history = playbook.steps.filter((item) => ["completed", "skipped", "dismissed"].includes(item.status));
  return <main data-engagement-playbook className="space-y-6 p-5 lg:p-8"><Link href={`/crm/candidates/${playbook.candidateId}`} className="inline-flex items-center gap-2 text-sm font-black text-blue-700"><ArrowLeft size={16} />Back to {playbook.candidateName}</Link>
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.22em] text-teal-600">Consultant-controlled strategy</p><h1 className="mt-1 text-4xl font-black tracking-tight">Candidate Engagement Playbook</h1><p className="mt-2 text-slate-600">{playbook.candidateName} · {playbook.summary}</p></div><div className="rounded-xl border bg-white px-5 py-3 text-right"><p className="text-xs font-black uppercase text-slate-400">Progress</p><p className="text-2xl font-black">{playbook.progress.completed} of {playbook.progress.total}</p></div></header>
    {current ? <CurrentStep playbook={playbook} step={current} /> : <section className="rounded-2xl bg-emerald-50 p-8"><h2 className="text-2xl font-black text-emerald-950">Plan resolved</h2><p className="mt-2 text-emerald-800">Every current recommendation has a consultant decision.</p></section>}
    <div className="grid gap-6 xl:grid-cols-[1.35fr_.85fr]"><section aria-labelledby="upcoming-heading" className="rounded-2xl border bg-white p-6 shadow-sm"><h2 id="upcoming-heading" className="text-xl font-black">Upcoming steps</h2><ol className="mt-5 divide-y">{upcoming.map((step) => <li key={step.stepId} data-playbook-step={step.stepId} className="grid gap-3 py-5 sm:grid-cols-[36px_1fr_auto]"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 text-sm font-black">{step.order}</span><div><h3 className="font-black">{step.title}</h3><p className="mt-1 text-sm text-slate-600">{step.description}</p><p className="mt-2 text-xs font-bold text-blue-700">{step.recommendedTiming}</p></div>{step.actionHref && <Link href={step.actionHref} className="self-start rounded-lg border px-3 py-2 text-xs font-black">{step.actionLabel}<ExternalLink size={12} className="ml-1 inline" /></Link>}</li>)}{!upcoming.length && <li className="py-6 text-sm text-slate-500">No additional recommended steps.</li>}</ol></section>
      <section aria-labelledby="evidence-heading" className="rounded-2xl border bg-white p-6 shadow-sm"><h2 id="evidence-heading" className="text-xl font-black">Why this plan</h2><ul className="mt-4 space-y-3">{playbook.rationale.map((item) => <li key={item} className="rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{item}</li>)}</ul><p className="mt-5 text-xs text-slate-500">Evidence fingerprint keeps this plan stable during navigation. Meaningful evidence can revise it; consultant decisions remain recorded against the evidence they addressed.</p></section></div>
    {history.length > 0 && <section aria-labelledby="history-heading" className="rounded-2xl border bg-white p-6"><h2 id="history-heading" className="text-xl font-black">Completed and skipped</h2><div className="mt-4 divide-y">{history.map((step) => <div key={step.stepId} className="flex items-center justify-between gap-4 py-4"><div><p className="font-black">{step.title}</p><p className="mt-1 text-xs text-slate-500">{step.rationale}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black capitalize">{step.status}</span></div>)}</div></section>}
    <section className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-xs leading-5 text-blue-900"><strong>Advisory boundary:</strong> FranGroove recommends this plan. No step sends email, schedules meetings, changes lifecycle, or prepares referrals without an explicit consultant action. Future AI planning must cite evidence and preserve these decisions; future automation requires separate consultant approval and configuration.</section>
  </main>;
}

function CurrentStep({ playbook, step }: { playbook: CandidateEngagementPlaybook; step: CandidateEngagementStep }) {
  const [decisionState, decisionAction, deciding] = useActionState(decidePlaybookStep, initial);
  const [taskState, taskAction, tasking] = useActionState(createPlaybookTask, initial);
  return <section aria-labelledby="current-step-heading" className="overflow-hidden rounded-2xl bg-slate-950 text-white shadow-xl"><div className="grid xl:grid-cols-[1.35fr_.65fr]"><div className="p-7 lg:p-9"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-teal-300"><CircleDashed size={16} />Current recommended step · {step.recommendedTiming}</div><h2 id="current-step-heading" className="mt-4 text-3xl font-black">{step.title}</h2><p className="mt-3 max-w-3xl text-base leading-7 text-slate-300">{step.description}</p><div className="mt-6 rounded-xl bg-white/5 p-5"><h3 className="text-xs font-black uppercase tracking-[.16em] text-slate-400">Why it matters</h3><p className="mt-2 text-sm leading-6 text-slate-200">{step.rationale}</p><ul className="mt-3 space-y-2">{step.evidence.map((item) => <li key={`${item.source}:${item.referenceId}`} className="text-xs text-slate-400"><strong className="text-slate-200">{item.label}:</strong> {item.detail}</li>)}</ul></div></div><div className="border-t border-white/10 bg-white/5 p-7 xl:border-l xl:border-t-0"><h3 className="text-sm font-black">Consultant controls</h3><p className="mt-2 text-xs leading-5 text-slate-400">Choose deliberately. Recommendations do not execute themselves.</p><div className="mt-5 grid gap-2">{step.actionHref && <Link href={step.actionHref} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-black">{step.actionLabel}<ExternalLink size={14} /></Link>}<form action={taskAction}><Fields playbook={playbook} step={step} /><button disabled={tasking} className="w-full rounded-xl bg-white px-4 py-3 text-sm font-black text-slate-950"><ListChecks size={15} className="mr-2 inline" />{tasking ? "Creating…" : "Create Task"}</button></form><Decision playbook={playbook} step={step} decision="accepted" label="Accept Recommendation" icon={<Check size={14} />} action={decisionAction} disabled={deciding} /><Decision playbook={playbook} step={step} decision="completed" label="Mark Complete" icon={<Check size={14} />} action={decisionAction} disabled={deciding} /><Decision playbook={playbook} step={step} decision="skipped" label="Skip Step" icon={<SkipForward size={14} />} action={decisionAction} disabled={deciding} /><Decision playbook={playbook} step={step} decision="dismissed" label="Dismiss Recommendation" icon={<X size={14} />} action={decisionAction} disabled={deciding} /></div>{(decisionState.message || taskState.message) && <p role="status" className="mt-4 text-xs font-bold text-teal-200">{decisionState.message ?? taskState.message}</p>}</div></div></section>;
}

function Fields({ playbook, step }: { playbook: CandidateEngagementPlaybook; step: CandidateEngagementStep }) { return <><input type="hidden" name="candidateId" value={playbook.candidateId} /><input type="hidden" name="stepId" value={step.stepId} /></>; }
function Decision({ playbook, step, decision, label, icon, action, disabled }: { playbook: CandidateEngagementPlaybook; step: CandidateEngagementStep; decision: string; label: string; icon: React.ReactNode; action: (payload: FormData) => void; disabled: boolean }) { return <form action={action}><Fields playbook={playbook} step={step} /><input type="hidden" name="decision" value={decision} /><button disabled={disabled} className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-white/20 px-4 py-2.5 text-xs font-black hover:bg-white/10">{icon}{label}</button></form>; }
