import Link from "next/link";
import type { referralContext } from "../services/PersistedReferral";
import {buildReferralPacket} from "../services/ReferralPacket";
import {ConsiderationControls,ReferralPreparationForm} from "./ConsiderationControls";
export function PersistedReferralWorkspace({context:c}:{context:NonNullable<Awaited<ReturnType<typeof referralContext>>>}){
 const base=`/crm/candidates/${c.row.candidate.id}`,selected=c.consideration?.state==="selected";
 const packet=selected&&c.record&&c.brand?buildReferralPacket(c):null;
 return <main className="space-y-6"><nav className="flex flex-wrap gap-4 text-sm font-bold text-blue-700"><Link href={base}>Candidate 360</Link><Link href={`${base}/strategy`}>Brand Referral Engine</Link><Link href={`${base}/documents`}>Assessments &amp; Documents</Link><Link href="/crm/calendar">Calendar</Link><Link href="/crm">Mission Control</Link></nav><header className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-xs font-bold uppercase text-teal-300">Preparation only · Nothing transmitted</p><h1 className="mt-3 text-3xl font-black">Referral Readiness &amp; Preparation</h1><p className="mt-3 text-xl">{c.row.candidate.firstName} {c.row.candidate.lastName} · {c.brand?.name??"Select a brand"}</p></header>
 {c.brand&&<section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Brand consideration</h2><ConsiderationControls candidateId={c.row.candidate.id} brandId={c.brand.brandId} state={c.consideration?.state}/></section>}
 <section className="rounded-2xl border bg-white p-5"><h2 className="text-2xl font-black">{c.readiness.band}</h2><p className="mt-2 text-sm text-slate-500">A deterministic checklist of missing information and review obligations, not a fit score.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{c.readiness.items.map(i=><div key={i.label} className={`rounded-xl p-4 ${i.state==="complete"?"bg-teal-50":i.state==="missing"?"bg-rose-50":"bg-amber-50"}`}><h3 className="font-bold">{i.label} · {i.state}</h3><p className="mt-2 text-sm leading-6">{i.detail}</p></div>)}</div></section>
 {selected&&c.brand&&<section className="rounded-2xl border bg-white p-5"><h2 className="mb-4 text-2xl font-black">Prepare Referral</h2><ReferralPreparationForm candidateId={c.row.candidate.id} brandId={c.brand.brandId} note={c.consideration?.consultant_note??""}/></section>}
 {packet&&<section className="space-y-5 rounded-2xl border bg-white p-5"><h2 className="text-2xl font-black">Referral Packet Preview</h2><p className="text-sm text-slate-600">Review all missing and unverified information. Generating this packet does not authorize an introduction.</p><a href={`${base}/referral/packet`} className="inline-flex rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">Generate Referral Packet PDF</a>{packet.sections.map(s=><details key={s.heading} className="rounded-xl border p-4"><summary className="cursor-pointer font-bold">{s.heading}</summary>{[...s.paragraphs??[],...s.bullets??[]].map((p,i)=><p key={i} className="mt-3 break-words text-sm leading-6 text-slate-600">{p}</p>)}</details>)}</section>}
 {!c.brand&&<Link href={`${base}/strategy`} className="inline-flex rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">Choose a brand in the Referral Engine</Link>}
 </main>;
}
