"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { AlertTriangle, ArrowLeft, CheckCircle2, CircleDollarSign, Mail, Plus, Printer, Send, ShieldCheck } from "lucide-react";
import type { CandidateBrandReferral } from "../models/CandidateBrandReferral";
import type { ReferralStudioState } from "../models/ReferralStudioState";
import { approveReferral, markHandoffReady, prepareOtherBrand, prepareReferrals, refreshHandoffPackage, retryReferralDelivery, saveReferralDraft, saveReportAttachments, type ReferralActionState } from "../actions/referral-studio";

const initialState: ReferralActionState = { status: "idle" };
const cash = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const labels = { selected: "Selected", draft: "Draft", "ready-for-review": "Ready for Review", approved: "Approved", sent: "Sent", introduced: "Sent" } as const;
const badge = (status: CandidateBrandReferral["status"]) => status === "sent" || status === "introduced" ? "bg-teal-100 text-teal-800" : status === "approved" ? "bg-emerald-100 text-emerald-800" : "bg-blue-50 text-blue-700";

function UnavailableReferral({ state }: { state: Extract<ReferralStudioState, { available: false }> }) {
  return <main className="mx-auto max-w-5xl p-8"><Link href={`/crm/candidates/${state.candidateId}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} />Candidate 360</Link><section className="mt-8 rounded-3xl border border-amber-200 bg-white p-8"><p className="text-xs font-black uppercase tracking-wider text-amber-600">Referral Package · Not Found</p><h1 className="mt-2 text-2xl font-black">Referral package could not be resolved</h1><p className="mt-3 text-sm text-slate-600">{state.reason}</p></section></main>;
}

function Items({ values, concern = false }: { values: string[]; concern?: boolean }) {
  return values.length ? <ul className="space-y-2">{values.map((value, index) => <li key={`${index}:${value}`} className="flex gap-2 text-sm leading-6 text-slate-700">{concern ? <AlertTriangle size={15} className="mt-1 shrink-0 text-amber-600" /> : <CheckCircle2 size={15} className="mt-1 shrink-0 text-teal-600" />}{value}</li>)}</ul> : <p className="text-sm italic text-slate-400">Unavailable</p>;
}

function SupportingDocuments({referral}:{referral:CandidateBrandReferral}){
  const attachments=referral.referralPackage.reportAttachments??[];const [consultantSelected,setConsultantSelected]=useState(attachments.some(item=>item.reportType==="CONSULTANT_INTELLIGENCE_REPORT"&&item.selected));const [state,action,pending]=useActionState(saveReportAttachments,initialState);
  if(!attachments.length)return null;
  return <section className="handoff-controls mx-6 mt-6 rounded-2xl border border-slate-200 p-5"><h3 className="font-black">Attachments · Supporting Documents</h3><p className="mt-1 text-xs text-slate-500">Reports remain separate artifacts. Nothing is attached or sent automatically.</p><form action={action} className="mt-4 space-y-3"><input type="hidden" name="candidateId" value={referral.candidateId}/><input type="hidden" name="referralId" value={referral.referralId}/>{attachments.map(item=><label key={item.reportType} className="flex items-start gap-3 rounded-xl bg-slate-50 p-3 text-sm font-bold"><input type="checkbox" name="reportTypes" value={item.reportType} defaultChecked={item.selected} onChange={event=>item.reportType==="CONSULTANT_INTELLIGENCE_REPORT"&&setConsultantSelected(event.target.checked)} className="mt-0.5 h-4 w-4"/><span>{item.reportType==="CANDIDATE_ASSESSMENT_REPORT"?"Candidate Assessment Report":"Consultant Intelligence Report"}<small className="mt-1 block font-normal text-slate-500">{item.reportVersion} · Not selected by default</small></span></label>)}{consultantSelected&&<p role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">This report contains internal consultant intelligence and Discovery guidance. Confirm that you want to share it externally.</p>}<button disabled={pending} className="rounded-xl border px-4 py-2 text-sm font-black">{pending?"Saving…":"Save Attachments"}</button>{state.message&&<p role="status" className="text-xs font-bold">{state.message}</p>}</form></section>;
}

function PackageReview({ referral }: { referral: CandidateBrandReferral }) {
  const [editing, setEditing] = useState(false);
  const [saveState, saveAction, saving] = useActionState(saveReferralDraft, initialState);
  const [approvalState, approvalAction, approving] = useActionState(approveReferral, initialState);
  const [retryState, retryAction, retrying] = useActionState(retryReferralDelivery, initialState);
  const [readyState, readyAction, readying] = useActionState(markHandoffReady, initialState);
  const [refreshState, refreshAction, refreshing] = useActionState(refreshHandoffPackage, initialState);
  const pkg = referral.referralPackage;
  const draftHref = `/crm/communications?compose=1&candidate=${encodeURIComponent(referral.candidateId)}&subject=${encodeURIComponent(pkg.editable.subject)}&body=${encodeURIComponent(pkg.editable.introductionMessage)}&handoff=${encodeURIComponent(referral.referralId)}&brand=${encodeURIComponent(pkg.brand.name)}`;
  return <section className="handoff-shell mt-7 rounded-3xl border border-slate-200 bg-white shadow-sm" data-testid={`package-${referral.referralId}`}><div className="handoff-controls flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 p-6"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-teal-600">Candidate Handoff Package</p><h2 className="mt-1 text-2xl font-black text-slate-950">{referral.brandName} · {pkg.candidate.name}</h2><p className="mt-1 text-xs font-bold text-slate-500">Status: {pkg.handoffStatus ?? "ready"}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-black"><Printer size={14} />Print / Save PDF</button><Link href={draftHref} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-black"><Mail size={14} />Draft Introduction Email</Link><span className={`rounded-full px-3 py-2 text-xs font-black ${badge(referral.status)}`}>{labels[referral.status]}</span></div></div><SupportingDocuments referral={referral}/>
    <h2 className="sr-only">{referral.brandName} package</h2>
    {referral.source === "other-brand" && <p className="handoff-controls px-6 pt-4 text-xs font-black uppercase tracking-wider text-slate-600">Consultant-Selected Referral</p>}
    <article className="handoff-document mx-auto max-w-4xl space-y-7 bg-white p-6 lg:p-10" aria-label={`Candidate Handoff Package for ${pkg.candidate.name} and ${pkg.brand.name}`}>
      <div className="border-b-2 border-slate-950 pb-5"><p className="text-sm font-black tracking-[0.24em]">FRANGROOVE</p><p className="mt-2 text-xs font-bold uppercase tracking-[0.18em] text-teal-700">Candidate Introduction</p><h2 className="mt-3 text-3xl font-black">{pkg.candidate.name}</h2><p className="mt-1 text-sm text-slate-600">Prepared for {pkg.brand.name} · Consultant: {pkg.consultant.name}</p></div>
      <section><h3 className="text-sm font-black uppercase tracking-wider">Executive Overview</h3><p className="mt-2 text-sm leading-7 text-slate-700">{pkg.executiveSummary}</p><p className="mt-2 text-sm text-slate-600">{pkg.candidate.location ?? "Location not provided"} · Desired territory: {pkg.candidate.territory ?? "Not provided"}</p></section>
      <section className="handoff-avoid-break"><h3 className="text-sm font-black uppercase tracking-wider">Financial Profile</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Candidate-reported liquid capital</dt><dd className="font-black">{cash(pkg.financial.liquidCapital)}</dd></div><div><dt className="text-xs text-slate-500">Candidate-reported investable capital</dt><dd className="font-black">{cash(pkg.financial.investableCapital)}</dd></div>{pkg.financial.netWorth !== null && <div><dt className="text-xs text-slate-500">Candidate-reported net worth</dt><dd className="font-black">{cash(pkg.financial.netWorth)}</dd></div>}<div><dt className="text-xs text-slate-500">Stated investment range</dt><dd className="font-black">{pkg.financial.candidatePreferredInvestmentRange}</dd></div></dl><p className="mt-3 text-xs text-slate-500">Candidate-supplied information; not independently verified by FranGroove.</p></section>
      <div className="grid gap-7 md:grid-cols-2"><section><h3 className="text-sm font-black uppercase tracking-wider">What the Candidate Is Looking For</h3><Items values={pkg.candidateObjectives ?? pkg.motivations} /></section><section><h3 className="text-sm font-black uppercase tracking-wider">Discovery Highlights</h3><Items values={pkg.discoveryFindings} /></section></div>
      <section className="rounded-2xl bg-blue-50 p-5 handoff-avoid-break"><h3 className="text-sm font-black uppercase tracking-wider">Why This Brand</h3><p className="mt-2 text-sm leading-7 text-slate-700">{pkg.recommendation?.rationale ?? "This consultant-selected brand has not been scored by FranGroove; the package provides candidate context for consultant review."}</p></section>
      <div className="grid gap-7 md:grid-cols-2"><section><h3 className="text-sm font-black uppercase tracking-wider">Candidate Strengths</h3><Items values={pkg.strengths} /></section><section><h3 className="text-sm font-black uppercase tracking-wider">Areas to Validate</h3><Items values={pkg.concerns} concern /></section><section><h3 className="text-sm font-black uppercase tracking-wider">Candidate Questions</h3><Items values={pkg.candidateQuestions ?? []} /></section><section><h3 className="text-sm font-black uppercase tracking-wider">Suggested Focus for the First Conversation</h3><Items values={pkg.recommendedFranchisorFocus ?? pkg.conversationFocus} /></section></div>
      {pkg.editable.consultantNotes && <section className="handoff-avoid-break border-l-4 border-teal-600 pl-5"><h3 className="text-sm font-black uppercase tracking-wider">Franchisor-facing Consultant Note</h3><p className="mt-2 whitespace-pre-line text-sm leading-7 text-slate-700">{pkg.editable.consultantNotes}</p></section>}
      <details className="handoff-controls rounded-xl bg-slate-50 p-4"><summary className="cursor-pointer text-xs font-black">Based on supporting evidence</summary><ul className="mt-3 space-y-2 text-xs text-slate-600">{pkg.provenance?.map((item) => <li key={`${item.source}:${item.label}`}><strong>{item.source}:</strong> {item.label}</li>)}</ul></details>
    </article>
    {pkg.evidenceStale && <div role="status" className="handoff-controls mx-6 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-bold text-amber-900">Candidate information has changed since this package was prepared.</div>}
    <div className="handoff-controls flex flex-wrap items-center gap-3 border-y border-slate-200 p-6"><form action={readyAction}><input type="hidden" name="candidateId" value={referral.candidateId} /><input type="hidden" name="referralId" value={referral.referralId} /><button disabled={readying || pkg.handoffStatus === "ready"} className="rounded-xl bg-teal-700 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{pkg.handoffStatus === "ready" ? "Handoff Ready" : readying ? "Marking Ready…" : "Mark Package Ready"}</button></form><form action={refreshAction}><input type="hidden" name="candidateId" value={referral.candidateId} /><input type="hidden" name="referralId" value={referral.referralId} /><button disabled={refreshing} className="rounded-xl border px-5 py-3 text-sm font-black">{refreshing ? "Refreshing…" : "Refresh Package"}</button></form><p role="status" className="text-xs font-bold text-slate-600">{readyState.message ?? refreshState.message}</p></div>
    <div className="grid gap-7 p-6 xl:grid-cols-[1.25fr_0.75fr]"><div className="space-y-7"><div><h3 className="font-black text-slate-900">Executive Summary</h3><p className="mt-2 text-sm leading-7 text-slate-700">{pkg.executiveSummary}</p></div>{pkg.recommendation ? <div className="rounded-2xl bg-blue-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-blue-600">Why this candidate fits · {pkg.recommendation.score} Fit</p><p className="mt-2 text-sm leading-6 text-slate-700">{pkg.recommendation.rationale}</p></div> : <div className="rounded-2xl bg-slate-100 p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-600">Candidate intelligence package</p><p className="mt-2 text-sm text-slate-700">Consultant-selected opportunity. FranGroove has not evaluated or scored this brand match.</p></div>}
      <div className="grid gap-6 md:grid-cols-2"><div><h3 className="mb-3 font-black">Candidate Snapshot</h3><p className="text-sm text-slate-600">{pkg.candidate.location ?? "Location unavailable"}</p><p className="text-sm text-slate-600">Territory: {pkg.candidate.territory ?? "Unavailable"}</p><p className="text-sm text-slate-600">Ownership goals: {pkg.motivations.join(", ") || "Unavailable"}</p></div><div><h3 className="mb-3 flex items-center gap-2 font-black"><CircleDollarSign size={17} />Financial Qualification</h3><p className="text-sm text-slate-600">Liquid capital: <strong>{cash(pkg.financial.liquidCapital)}</strong></p><p className="text-sm text-slate-600">Investable capital: <strong>{cash(pkg.financial.investableCapital)}</strong></p><p className="text-sm text-slate-600">Net worth: <strong>Unavailable</strong></p><p className="text-sm text-slate-600">Candidate Preferred Investment Range: <strong>{pkg.financial.candidatePreferredInvestmentRange}</strong></p>{pkg.financial.brandInvestmentRange && <p className="text-sm text-slate-600">Brand Investment Range: <strong>{pkg.financial.brandInvestmentRange}</strong></p>}</div><div><h3 className="mb-3 font-black">Validated Strengths</h3><Items values={pkg.strengths} /></div><div><h3 className="mb-3 font-black">Discovery Intelligence</h3><Items values={pkg.discoveryFindings} /></div><div><h3 className="mb-3 font-black">Known Considerations</h3><Items values={pkg.concerns} concern /></div><div><h3 className="mb-3 font-black">Recommended Franchisor Focus</h3><Items values={pkg.conversationFocus} /></div></div>
      <div><h3 className="mb-3 font-black">Supporting Evidence</h3>{pkg.evidence.length ? <div className="grid gap-2 sm:grid-cols-2">{pkg.evidence.map((evidence) => <div key={evidence.id} className="rounded-xl bg-slate-50 p-3"><p className="text-sm font-bold">{evidence.title}</p><p className="mt-1 text-xs text-slate-500">{evidence.source} · {evidence.confidence}% confidence</p></div>)}</div> : <p className="text-sm text-slate-500">Candidate assessment and discovery intelligence; no brand-fit evidence was generated.</p>}</div></div>
      <aside className="space-y-5"><div className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 font-black"><Mail size={17} />Introduction Preview</h3><button type="button" onClick={() => setEditing((value) => !value)} className="text-xs font-black text-blue-600">{editing ? "Close Editor" : "Edit Introduction"}</button></div><div className="mt-4 rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase text-slate-400">To</p><p className="text-sm font-bold">{pkg.brand.contact?.email || pkg.brand.contact?.name || "Contact unavailable"}</p><p className="mt-3 text-[10px] font-black uppercase text-slate-400">Subject</p><p className="text-sm font-bold">{pkg.editable.subject}</p><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-700">{pkg.editable.introductionMessage}</p></div><p className="mt-3 text-xs font-bold text-slate-500">Nothing is sent without consultant approval.</p></div>
      {editing && <form action={saveAction} className="rounded-2xl border border-blue-200 bg-blue-50/40 p-5"><input type="hidden" name="candidateId" value={referral.candidateId} /><input type="hidden" name="referralId" value={referral.referralId} /><label className="text-xs font-black uppercase text-slate-500">Subject<input name="subject" defaultValue={pkg.editable.subject} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm" /></label><label className="mt-4 block text-xs font-black uppercase text-slate-500">Message<textarea name="introductionMessage" defaultValue={pkg.editable.introductionMessage} rows={9} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm" /></label><label className="mt-4 block text-xs font-black uppercase text-slate-500">Private consultant note<textarea name="consultantNotes" defaultValue={pkg.editable.consultantNotes} rows={3} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm" /></label><button disabled={saving} className="mt-4 w-full rounded-xl bg-blue-600 p-3 text-sm font-black text-white">{saving ? "Saving…" : "Save Introduction"}</button>{saveState.message && <p className="mt-2 text-xs font-bold">{saveState.message}</p>}</form>}
      <div className="rounded-2xl border border-slate-200 p-5"><h3 className="flex items-center gap-2 font-black"><ShieldCheck size={18} className="text-emerald-600" />Consultant Approval</h3>{referral.status === "ready-for-review" && <form action={approvalAction} className="mt-4"><input type="hidden" name="candidateId" value={referral.candidateId} /><input type="hidden" name="referralId" value={referral.referralId} /><button disabled={approving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 p-3 text-sm font-black text-white">{approving ? "Approving & Sending…" : "Approve & Send Referral"}<Send size={15} /></button></form>}{referral.delivery?.status === "failed" && <div className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-800"><p className="font-black">Delivery Failed</p><p className="mt-1 text-xs">{referral.delivery.failureReason}</p><form action={retryAction} className="mt-3"><input type="hidden" name="candidateId" value={referral.candidateId} /><input type="hidden" name="referralId" value={referral.referralId} /><button disabled={retrying} className="w-full rounded-xl bg-rose-700 p-3 text-sm font-black text-white">{retrying ? "Retrying…" : "Retry Delivery"}</button></form></div>}{(referral.status === "sent" || referral.status === "introduced") && <div className="mt-4 rounded-xl bg-teal-50 p-4 text-sm text-teal-800"><p className="font-black">Referral Sent</p><p className="mt-1">Sent to {referral.brandName} on behalf of {pkg.consultant.name}.</p><p className="mt-1 text-xs">{new Date(referral.delivery?.sentAt ?? referral.introducedAt ?? referral.updatedAt).toLocaleString()} · Delivery Status: Sent</p><p className="mt-2 text-xs">Demo delivery recorded; no external email was sent.</p></div>}{referral.delivery?.status === "pending" && <div className="mt-4 rounded-xl bg-blue-50 p-4 text-sm font-black text-blue-800">Delivery in progress…</div>}{approvalState.message && <p className="mt-2 text-xs font-bold">{approvalState.message}</p>}{retryState.message && <p className="mt-2 text-xs font-bold">{retryState.message}</p>}</div></aside></div></section>;
}

export function ReferralStudioPage({ state }: { state: ReferralStudioState }) {
  const [selectedBrands, setSelectedBrands] = useState<string[]>([]); const [activeId, setActiveId] = useState<string | null>(null); const [showOther, setShowOther] = useState(false);
  const [prepareState, prepareAction, preparing] = useActionState(prepareReferrals, initialState); const [otherState, otherAction, preparingOther] = useActionState(prepareOtherBrand, initialState);
  if (!state.available) return <UnavailableReferral state={state} />;
  const activeReferral = state.referrals.find((item) => item.referralId === activeId) ?? state.referrals.find((item) => item.referralId === state.activeReferralId) ?? state.referrals.find((item) => item.referralId === prepareState.selectedReferralId || item.referralId === otherState.selectedReferralId) ?? state.referrals[0];
  if (state.historical) return <main className="mx-auto max-w-6xl space-y-7 p-6 lg:p-10"><header><Link href={`/crm/candidates/${state.candidate.id}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} />Candidate 360</Link><p className="mt-6 text-xs font-black uppercase tracking-[0.22em] text-teal-600">Completed Referral History</p><h1 className="mt-2 text-3xl font-black text-slate-950">{state.candidate.name}</h1><p className="mt-2 text-sm text-slate-600">Placement awarded. Historical referral and introduction records remain available for review.</p></header><section className="grid gap-4 md:grid-cols-2">{state.referrals.map((referral) => <article key={referral.referralId} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-black">{referral.brandName}</h2><span className={`rounded-full px-3 py-1 text-xs font-black ${badge(referral.status)}`}>{labels[referral.status]}</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{referral.referralPackage.recommendation?.rationale ?? referral.referralPackage.executiveSummary}</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs font-bold uppercase text-slate-400">Approved</dt><dd className="mt-1 font-semibold">{referral.approvedAt ? new Date(referral.approvedAt).toLocaleDateString() : "Not recorded"}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">Introduced</dt><dd className="mt-1 font-semibold">{referral.introducedAt ? new Date(referral.introducedAt).toLocaleDateString() : "Not recorded"}</dd></div></dl></article>)}</section></main>;
  const prepareLabel = state.readinessAdvisory.recommended ? (selectedBrands.length === 1 ? "Prepare Referral" : `Prepare ${selectedBrands.length} Referrals`) : (selectedBrands.length === 1 ? "Prepare Referral Anyway" : `Prepare ${selectedBrands.length} Referrals Anyway`);
  return <main className="mx-auto max-w-7xl space-y-7 p-6 lg:p-10"><header><Link href={`/crm/candidates/${state.candidate.id}/strategy`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} />Brand Strategy</Link><p className="mt-6 text-xs font-black uppercase tracking-[0.22em] text-teal-600">Referral Studio</p><div className="mt-2 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-black text-slate-950">{state.candidate.name}</h1><p className="mt-2 text-sm text-slate-600">Select the franchise opportunities you and the candidate are ready to pursue.</p></div><div className="rounded-2xl border border-slate-200 bg-white px-5 py-4"><p className="text-xs font-black uppercase text-slate-400">Candidate readiness</p><p className="mt-1 text-2xl font-black">{state.candidate.readiness}%</p></div></div></header>
    <section aria-label="Referral Readiness" className={`rounded-2xl border p-5 ${state.readinessAdvisory.recommended ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}><p className={`text-xs font-black uppercase tracking-wider ${state.readinessAdvisory.recommended ? "text-emerald-700" : "text-amber-700"}`}>Referral Readiness: {state.readinessAdvisory.label}</p><p className="mt-2 text-sm text-slate-700">{state.readinessAdvisory.explanation}</p>{state.readinessAdvisory.considerations.length > 0 && <ul className="mt-3 space-y-1 text-xs text-amber-900">{state.readinessAdvisory.considerations.map((item, index) => <li key={`${index}:${item}`}>• {item}</li>)}</ul>}<p className="mt-3 text-xs font-black text-slate-600">AI recommendation → consultant judgment → consultant action</p></section>
    {activeReferral?.decision.consultantDirected && <section aria-label="Consultant-Directed Referral" className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-black uppercase text-amber-800">Consultant-Directed Referral · Earlier Than Recommended</p><p className="mt-1 text-xs text-amber-900">AI readiness at decision: {activeReferral.decision.aiReadinessStatus} ({activeReferral.decision.readinessPercentage}%). Lifecycle preserved: {activeReferral.decision.lifecycleStage}. {activeReferral.decision.unresolvedConsiderations.join(" ")}</p></section>}
    {state.reviewOnly && <p className="rounded-xl bg-slate-100 p-4 text-sm font-bold text-slate-600">Historical package review only. Current lifecycle rules prevent mutation.</p>}
    <fieldset disabled={state.reviewOnly} className="contents">
    {activeReferral && <PackageReview key={activeReferral.referralId} referral={activeReferral} />}
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["Recommended", state.summary.recommended], ["Prepared", state.summary.prepared], ["Approved", state.summary.approved], ["Sent", state.summary.introduced]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-2xl font-black">{value}</p><p className="text-xs font-bold text-slate-500">{label}</p></div>)}</section>
    <form action={prepareAction} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><input type="hidden" name="candidateId" value={state.candidate.id} /><h2 className="text-xl font-black">Recommended Opportunities</h2><div className="mt-5 space-y-3">{state.opportunities.map((item) => <label key={item.brandId} className={`flex cursor-pointer gap-4 rounded-2xl border p-5 ${item.selectable ? "border-slate-200 hover:border-blue-300" : "border-slate-200 bg-slate-50 opacity-70"}`}><input type="checkbox" name="brandIds" value={item.brandId} disabled={!item.selectable} checked={selectedBrands.includes(item.brandId)} onChange={(event) => setSelectedBrands((current) => event.target.checked ? [...current, item.brandId] : current.filter((id) => id !== item.brandId))} className="mt-1 h-5 w-5 accent-blue-600" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="text-xs font-black uppercase text-blue-600">#{item.rank} Recommendation</span><h3 className="text-lg font-black">{item.brandName}</h3></div><div className="text-right"><strong className="text-2xl">{item.recommendationScore}</strong><span className="ml-1 text-xs text-slate-500">Fit</span></div></div><p className="mt-2 text-sm leading-6 text-slate-600">{item.candidateBrandRationale}</p><div className="mt-3 flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.financialCompatibility.compatible ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{item.financialCompatibility.compatible ? "Financially Qualified" : "Not Financially Qualified"}</span>{item.knownConcerns[0] && <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">Consideration: {item.knownConcerns[0]}</span>}<span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.referral ? badge(item.referral.status) : "bg-slate-100 text-slate-600"}`}>{item.referral ? labels[item.referral.status] : "Not Selected"}</span></div></div></label>)}</div><button disabled={!selectedBrands.length || preparing} className="mt-5 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white disabled:opacity-40">{preparing ? "Preparing…" : prepareLabel}</button>{prepareState.message && <p className="mt-2 text-xs font-bold text-slate-600">{prepareState.message}</p>}</form>
    {state.referrals.length > 0 && <section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">Prepared Referrals</h2><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{state.referrals.map((referral) => <article key={referral.referralId} className={`rounded-2xl border p-4 ${activeReferral?.referralId === referral.referralId ? "border-blue-400 bg-blue-50" : "border-slate-200"}`}><div className="flex justify-between gap-2"><strong>{referral.brandName}</strong><span className={`rounded-full px-2 py-0.5 text-[10px] font-black ${badge(referral.status)}`}>{labels[referral.status]}</span></div><p className="mt-2 text-xs text-slate-500">{referral.source === "recommended" ? `${referral.recommendationScore} Fit · Recommended` : "Consultant-selected"}</p><Link href={`/crm/candidates/${referral.candidateId}/referral?referralId=${encodeURIComponent(referral.referralId)}`} onClick={() => setActiveId(referral.referralId)} className="mt-3 inline-flex text-xs font-black text-blue-600">Review Package</Link></article>)}</div></section>}
    <section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Other Brand</p><h2 className="mt-1 text-xl font-black">Refer to another franchise</h2></div><button type="button" onClick={() => setShowOther((value) => !value)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2 text-sm font-black"><Plus size={15} />Refer to Another Brand</button></div>{showOther && <form action={otherAction} className="mt-5 grid gap-4 rounded-2xl bg-slate-50 p-5 md:grid-cols-3"><input type="hidden" name="candidateId" value={state.candidate.id} /><label className="text-xs font-black text-slate-500">Brand name<input required name="brandName" className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm" /></label><label className="text-xs font-black text-slate-500">Referral contact name<input name="contactName" className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm" /></label><label className="text-xs font-black text-slate-500">Referral contact email<input type="email" name="contactEmail" className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm" /></label><button disabled={preparingOther} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white md:col-span-3">{preparingOther ? "Preparing…" : "Prepare Consultant-Selected Referral"}</button>{otherState.message && <p className="text-xs font-bold md:col-span-3">{otherState.message}</p>}</form>}</section>
    </fieldset>
  </main>;
}
