import type { AssessmentReport } from "../models/AssessmentReport";

const clean=(value:string)=>value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[\u2013\u2014]/g,"-").replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/[^\x20-\x7e]/g," ");
const escape=(value:string)=>clean(value).replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");
const wrap=(value:string,width:number)=>{const words=clean(value).split(/\s+/);const lines:string[]=[];let line="";for(const word of words){if((line+" "+word).trim().length>width&&line){lines.push(line);line=word}else line=(line+" "+word).trim()}if(line)lines.push(line);return lines};
type Line={text:string;size:number;bold?:boolean;space?:number;section?:string;heading?:boolean};

export function renderAssessmentReportPdf(report:AssessmentReport):ArrayBuffer {
  const lines:Line[]=[{text:"FRANGROOVE",size:11,bold:true,space:8},{text:report.title,size:22,bold:true,space:5},{text:report.privacyClassification,size:9,bold:true,space:10}];
  if(report.candidateName)lines.push({text:`Candidate: ${report.candidateName}`,size:11,space:3});
  lines.push({text:`Assessment: ${report.instrumentLabel}`,size:9},{text:`Analysis: Analysis v${report.analysisVersion}`,size:9},{text:`Assessment completed: ${new Date(report.assessmentCompletedAt).toLocaleDateString("en-US")}`,size:9},{text:`Report generated: ${new Date(report.generatedAt).toLocaleDateString("en-US")}`,size:9},{text:`Report template: ${report.templateVersion}`,size:8,space:12},{text:report.subtitle,size:16,bold:true,space:10});
  for(const section of report.sections){lines.push({text:section.heading.toUpperCase(),size:12,bold:true,space:5,section:section.heading,heading:true});for(const paragraph of section.paragraphs??[])for(const text of wrap(paragraph,92))lines.push({text,size:9.5,space:1,section:section.heading});for(const bullet of section.bullets??[]){const wrapped=wrap(bullet,88);wrapped.forEach((text,index)=>lines.push({text:`${index?"  ":"- "}${text}`,size:9.5,space:1,section:section.heading}))}lines.push({text:"",size:4,space:7})}lines.push({text:"DISCLAIMER",size:10,bold:true,space:4,heading:true});for(const text of wrap(report.disclaimer,92))lines.push({text,size:8.5,space:1});
  const pages:Line[][]=[];let page:Line[]=[];let y=742;for(let index=0;index<lines.length;index++){const line=lines[index];const height=line.size+2+(line.space??0);const reserve=line.heading?30:0;if(y-height-reserve<48){pages.push(page);page=[];y=742;if(line.section&&!line.heading){const continued:Line={text:`${line.section.toUpperCase()} (CONTINUED)`,size:11,bold:true,space:5,heading:true};page.push(continued);y-=continued.size+2+(continued.space??0)}}page.push(line);y-=height}if(page.length)pages.push(page);
  const objects:string[]=[];const add=(body:string)=>{objects.push(body);return objects.length};const font=add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");const bold=add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");const pageIds:number[]=[];const contentIds:number[]=[];
  for(const pageLines of pages){let cursor=742;let stream="BT\n";for(const line of pageLines){cursor-=line.size+2+(line.space??0);stream+=`/${line.bold?"F2":"F1"} ${line.size} Tf 1 0 0 1 54 ${cursor.toFixed(1)} Tm (${escape(line.text)}) Tj\n`;}stream+="ET";contentIds.push(add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`));pageIds.push(add("PENDING"));}
  const pagesId=objects.length+1;add(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`);const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);
  pageIds.forEach((id,index)=>objects[id-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${font} 0 R /F2 ${bold} 0 R >> >> /Contents ${contentIds[index]} 0 R >>`);
  let pdf="%PDF-1.4\n";const offsets=[0];objects.forEach((body,index)=>{offsets.push(pdf.length);pdf+=`${index+1} 0 obj\n${body}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(value=>String(value).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;
  const bytes=new TextEncoder().encode(pdf);return bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;
}

export function safeReportFilename(candidateName:string|undefined,type:AssessmentReport["reportType"]){const name=clean(candidateName??"").replace(/[^A-Za-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);const label=type==="CANDIDATE_ASSESSMENT_REPORT"?"FranGroove-Ownership-Profile":"FranGroove-Consultant-Intelligence";return `${name?`${name}-`:""}${label}.pdf`;}
