'use client';
import {useEffect,useState} from 'react';
import {getStudioBranding,saveStudioBranding} from './actions';
import type {BrandingSnapshot} from './model';
import {brandingDeliveryErrors} from './model';
import {colors,fontIds,fontNames} from '../studio/document';
import MediaLibrary from './MediaLibrary';
export default function BrandingPanel({snapshot,onInitial,onRefresh}:{snapshot?:BrandingSnapshot|null;onInitial:(value:BrandingSnapshot)=>void;onRefresh:(value:BrandingSnapshot)=>void}){
 const [current,setCurrent]=useState<BrandingSnapshot>(),[manage,setManage]=useState(false),[error,setError]=useState(''),[picker,setPicker]=useState<'logo'|'headshot'|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{void getStudioBranding().then(r=>{if(r.ok){setCurrent(r.branding);setManage(r.canManage);onInitial(r.branding);}});},[]); // eslint-disable-line react-hooks/exhaustive-deps
 if(!current)return null;
 const update=(key:keyof BrandingSnapshot,value:string|null)=>setCurrent(old=>({...old!,[key]:value}));
 const save=async(org:boolean)=>{setBusy(true);const r=await saveStudioBranding(current,org);if(r.ok){setCurrent(r.branding);setError('Settings saved. Refresh campaign branding to use these changes.');}else setError(r.error);setBusy(false);};
 return <details className="rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-bold">Company branding &amp; signature</summary><p className="my-3 text-sm">{(snapshot??current).name} · {(snapshot??current).company}. Saved campaigns retain their branding until you explicitly refresh it.</p><a className="text-sm underline" href="/settings/profile">Edit consultant name, title, email, phone, links and company identity</a><div className="my-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Sender postal address<textarea disabled={!manage||busy} aria-label="Sender postal address" value={current.postalAddress} onChange={e=>update('postalAddress',e.target.value)} className="mt-1 block w-full rounded-lg border p-2"/></label><label className="text-sm">Default email font<select disabled={!manage||busy} aria-label="Default email font" value={current.font} onChange={e=>update('font',e.target.value)} className="block rounded-lg border p-2">{fontIds.map(f=><option key={f} value={f}>{fontNames[f]}</option>)}</select></label>{(['primaryColor','accentColor'] as const).map(k=><label key={k} className="text-sm">{k==='primaryColor'?'Primary color':'Accent color'}<select disabled={!manage||busy} value={current[k]} onChange={e=>update(k,e.target.value)} className="block rounded-lg border p-2">{colors.map(c=><option key={c}>{c}</option>)}</select></label>)}</div><div className="flex flex-wrap gap-3"><button disabled={!manage||busy} type="button" onClick={()=>setPicker('logo')} className="rounded-lg border p-2">Choose company logo</button><button disabled={busy} type="button" onClick={()=>setPicker('headshot')} className="rounded-lg border p-2">Choose headshot</button><button disabled={!manage||busy} type="button" onClick={()=>void save(true)} className="rounded-lg border p-2">Save company branding</button><button disabled={busy} type="button" onClick={()=>void save(false)} className="rounded-lg border p-2">Save headshot</button><button disabled={busy} type="button" onClick={async()=>{const r=await getStudioBranding();if(r.ok){setCurrent(r.branding);onRefresh(r.branding);setError('Campaign branding refreshed. Save Draft to retain it.');}}} className="rounded-lg bg-teal-800 p-2 text-white">Refresh campaign branding</button></div>{current.logo&&<p className="mt-2 text-xs">Company logo selected</p>}{current.headshot&&<p className="mt-2 text-xs">Headshot selected</p>}{picker&&<MediaLibrary onClose={()=>setPicker(null)} onSelect={a=>{update(picker,a.public_id);setPicker(null);}}/>}{error&&<p role="status" className="mt-3 text-sm">{error}</p>}{brandingDeliveryErrors(snapshot??current).length>0&&<p className="mt-3 text-sm text-amber-800">Required before future delivery: {brandingDeliveryErrors(snapshot??current).join(', ')}.</p>}</details>;
}
