'use client';
/* eslint-disable @next/next/no-img-element -- Thumbnails are already normalized and resized by the upload boundary. */
import { useEffect,useState } from 'react';
import type { MediaAsset } from './model';
export default function MediaLibrary({onSelect,onClose}:{onSelect:(asset:MediaAsset)=>void;onClose:()=>void}) {
 const [assets,setAssets]=useState<MediaAsset[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/marketing/media').then(r=>r.json()).then(r=>r.error?setError(r.error):setAssets(r.assets)).catch(()=>setError('Media library unavailable.'));},[]);
 async function upload(file?:File){if(!file)return;setBusy(true);setError('');try{if(file.size>3145728)throw Error('Choose an image no larger than 3 MiB.');const response=await fetch('/api/marketing/media',{method:'POST',headers:{'Content-Type':file.type},body:file});const result=await response.json();if(!response.ok)throw Error(result.error);setAssets(old=>[result.asset,...old]);}catch(e){setError(e instanceof Error?e.message:'Upload failed.');}finally{setBusy(false);}}
 return <section role="dialog" aria-label="Media library" className="my-4 rounded-2xl border border-teal-300 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-black">Media library</h3><button type="button" onClick={onClose}>Close library</button></div><p className="my-3 text-sm text-slate-600">Reusable workspace images. JPEG, PNG or WebP, up to 3 MiB. Published image variants are publicly viewable by URL.</p><label className="block text-sm font-bold">Upload image<input disabled={busy} aria-label="Upload image" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}} className="my-2 block max-w-full" /></label>{busy&&<p role="status">Preparing your image...</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{assets.map((a,i)=><button type="button" key={a.public_id} onClick={()=>onSelect(a)} aria-label={`Select image ${i+1}`} className="rounded-xl border p-2 text-left"><img src={a.thumbnailUrl} alt={a.default_alt||'Workspace image'} className="h-28 w-full object-contain"/><span className="text-xs">{a.width} × {a.height}</span></button>)}</div></section>;
}
