import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database, Tables } from "@/types/database.generated";
import type { AuthenticatedWorkspaceContext } from "@/feature/identity/models/WorkspaceIdentity";
import type { ConsultantTask } from "../models/ConsultantTask";
import type { TaskRepository } from "./TaskRepository";
import type { CalendarRepository } from "@/feature/calendar/repositories/CalendarRepository";
import type { ConsultantCalendarEvent, ConsultantReminder } from "@/feature/calendar/models/ConsultantCalendarEvent";

export class SupabaseConsultantScheduleRepository implements TaskRepository, CalendarRepository {
  constructor(private readonly db:SupabaseClient<Database>,private readonly context:AuthenticatedWorkspaceContext){}
  private get org(){return this.context.organization.id}
  private get owner(){return this.context.membership.id}
  private assertOwner(id:string){if(id!==this.owner)throw new Error("Consultant unavailable.")}
  private fail(error:unknown){if(error)throw new Error("Schedule record could not be saved or loaded.")}
  async getAll(consultantId:string){this.assertOwner(consultantId);const{data,error}=await this.db.from("consultant_tasks").select("*").eq("organization_id",this.org).eq("consultant_membership_id",this.owner).order("due_at").limit(1000);this.fail(error);return(data??[]).map(r=>this.task(r))}
  async getById(id:string){const{data,error}=await this.db.from("consultant_tasks").select("*").eq("id",id).eq("organization_id",this.org).eq("consultant_membership_id",this.owner).maybeSingle();this.fail(error);return data?this.task(data):null}
  async save(t:ConsultantTask){this.assertOwner(t.consultantId);const{error}=await this.db.from("consultant_tasks").upsert({id:t.taskId,organization_id:this.org,consultant_membership_id:this.owner,candidate_public_id:t.candidateId??null,title:t.title,description:t.description??"",due_at:t.dueAt,status:t.status,priority:t.priority,completed_at:t.completedAt??null,source:t.source,source_reference_id:t.sourceReferenceId??null,recommended_reason:t.recommendedReason??null,created_at:t.createdAt});this.fail(error)}
  async delete(id:string){const record=await this.getById(id);if(!record)throw new Error("Task unavailable.");const{error}=await this.db.from("consultant_tasks").delete().eq("id",id).eq("organization_id",this.org).eq("consultant_membership_id",this.owner);this.fail(error);return record}
  async isRecommendationDismissed(id:string){const{data,error}=await this.db.from("consultant_task_dismissals").select("id").eq("id",id).eq("organization_id",this.org).eq("consultant_membership_id",this.owner).maybeSingle();this.fail(error);return!!data}
  async dismissRecommendation(id:string){const{error}=await this.db.from("consultant_task_dismissals").upsert({id,organization_id:this.org,consultant_membership_id:this.owner});this.fail(error)}
  async getEvents(consultantId:string){this.assertOwner(consultantId);const{data,error}=await this.db.from("consultant_calendar_events").select("*").eq("organization_id",this.org).eq("consultant_membership_id",this.owner).order("start_at").limit(1000);this.fail(error);return(data??[]).map(r=>this.event(r))}
  async getEvent(id:string){const{data,error}=await this.db.from("consultant_calendar_events").select("*").eq("id",id).eq("organization_id",this.org).eq("consultant_membership_id",this.owner).maybeSingle();this.fail(error);return data?this.event(data):null}
  async saveEvent(e:ConsultantCalendarEvent){this.assertOwner(e.consultantId);const{error}=await this.db.from("consultant_calendar_events").upsert({id:e.id,organization_id:this.org,consultant_membership_id:this.owner,candidate_public_id:e.candidateId??null,title:e.title,event_type:e.eventType??"Meeting",description:e.description??"",start_at:e.startAt,end_at:e.endAt,timezone:e.timezone,location:e.location??null,meeting_url:e.meetingUrl??null,status:e.status,notes:e.notes??null,source:e.source,created_at:e.createdAt});this.fail(error)}
  async deleteEvent(id:string){const record=await this.getEvent(id);if(!record)throw new Error("Meeting unavailable.");const{error}=await this.db.from("consultant_calendar_events").delete().eq("id",id).eq("organization_id",this.org).eq("consultant_membership_id",this.owner);this.fail(error);return record}
  async getReminders(consultantId:string):Promise<ConsultantReminder[]>{this.assertOwner(consultantId);const{data,error}=await this.db.from("consultant_reminders").select("*").eq("organization_id",this.org).eq("consultant_membership_id",this.owner);this.fail(error);return(data??[]).map(r=>({id:r.id,consultantId:this.owner,remindAt:r.remind_at,referenceType:r.reference_type as ConsultantReminder["referenceType"],referenceId:r.reference_id,status:r.status as ConsultantReminder["status"],createdBy:"consultant",createdAt:r.created_at}))}
  async saveReminder(r:ConsultantReminder){this.assertOwner(r.consultantId);if(r.referenceType==="calendar-event"&&!await this.getEvent(r.referenceId))throw new Error("Meeting unavailable.");if(r.referenceType==="task"&&!await this.getById(r.referenceId))throw new Error("Task unavailable.");const{error}=await this.db.from("consultant_reminders").upsert({id:r.id,organization_id:this.org,consultant_membership_id:this.owner,remind_at:r.remindAt,reference_type:r.referenceType,reference_id:r.referenceId,status:r.status});this.fail(error)}
  private task(r:Tables<"consultant_tasks">):ConsultantTask{return{taskId:r.id,consultantId:r.consultant_membership_id,createdByConsultantId:r.consultant_membership_id,assignedToConsultantId:r.consultant_membership_id,candidateId:r.candidate_public_id??undefined,title:r.title,description:r.description,status:r.status as ConsultantTask["status"],priority:r.priority as ConsultantTask["priority"],dueAt:r.due_at,completedAt:r.completed_at??undefined,source:r.source as ConsultantTask["source"],sourceReferenceId:r.source_reference_id??undefined,recommendedReason:r.recommended_reason??undefined,createdAt:r.created_at,updatedAt:r.updated_at}}
  private event(r:Tables<"consultant_calendar_events">):ConsultantCalendarEvent{return{id:r.id,consultantId:r.consultant_membership_id,candidateId:r.candidate_public_id??undefined,title:r.title,eventType:r.event_type,description:r.description,startAt:r.start_at,endAt:r.end_at,timezone:r.timezone,location:r.location??undefined,meetingUrl:r.meeting_url??undefined,status:r.status as ConsultantCalendarEvent["status"],notes:r.notes??undefined,source:r.source as ConsultantCalendarEvent["source"],relatedTaskIds:[],createdAt:r.created_at,updatedAt:r.updated_at}}
}
