"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { completeConferenceAssessment } from "../actions";
import { concernExclusive, concernOptions, conferenceQuestions, conferenceSectionTitles, geographyOptions, ownershipStageOptions, stakeholderOptions } from "../questions";
import type { ConferenceAnswers, ConferenceIntake, ConferenceQuestion } from "../types";
import { applyExclusiveSelection } from "../validation";

const STORAGE_KEY = "frangroove.conference-assessment.v1";
const emptyIntake: ConferenceIntake = { firstName:"",preferredName:"",lastName:"",email:"",mobilePhone:"",streetAddress:"",addressLine2:"",city:"",stateProvince:"",postalCode:"",country:"United States",occupationTitle:"",currentEmployer:"",linkedInProfile:"",ownedBusinessBefore:"no",ownershipExperience:"",exploredFranchiseBefore:"no",preferredContactMethod:"email",bestContactTime:"morning" };
type Stage = "intake" | "intro" | "assessment" | "concerns" | "analyzing";

function ChoiceGroup({ question, values, onChange }: { question: ConferenceQuestion; values: string[]; onChange: (values: string[]) => void }) {
  const actualOptions = question.options ?? [];
  return <fieldset className="space-y-3"><legend className="sr-only">{question.prompt}</legend>{actualOptions.map((option) => {
    const checked = values.includes(option); const multi = question.kind === "multi";
    return <label key={option} className={`flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border px-4 py-3 text-sm transition focus-within:ring-2 focus-within:ring-blue-500 ${checked ? "border-blue-600 bg-blue-50 text-blue-950" : "border-slate-200 bg-white hover:border-slate-400"}`}>
      <input type={multi ? "checkbox" : "radio"} name={question.id} checked={checked} onChange={() => onChange(multi ? applyExclusiveSelection(values, option, question.exclusive) : [option])} className="h-5 w-5" />
      <span>{option}</span>{checked && multi && <span className="ml-auto text-xs font-semibold">Selected</span>}
    </label>;
  })}</fieldset>;
}

export function ConferenceAssessmentExperience() {
  const router = useRouter();
  const [stage,setStage] = useState<Stage>("intake"); const [section,setSection] = useState(1); const [intake,setIntake] = useState(emptyIntake); const [answers,setAnswers] = useState<ConferenceAnswers>({}); const [consent,setConsent] = useState(false); const [startedAt,setStartedAt] = useState(new Date().toISOString()); const [error,setError] = useState(""); const [hydrated,setHydrated]=useState(false); const [pending,startTransition] = useTransition();
  useEffect(() => { const timer=window.setTimeout(()=>{ try { const saved = sessionStorage.getItem(STORAGE_KEY); if (saved) { const value = JSON.parse(saved); setStage(value.stage === "analyzing" ? "concerns" : value.stage); setSection(value.section); setIntake(value.intake); setAnswers(value.answers); setConsent(value.consent); setStartedAt(value.startedAt); } } catch {} finally { setHydrated(true); } },0);return()=>window.clearTimeout(timer); }, []);
  useEffect(() => { if (hydrated && stage !== "analyzing") sessionStorage.setItem(STORAGE_KEY, JSON.stringify({stage,section,intake,answers,consent,startedAt})); }, [hydrated,stage,section,intake,answers,consent,startedAt]);
  const questions = useMemo(() => conferenceQuestions.filter((q) => q.section === section), [section]);
  const setValue = (id: string, values: string[]) => setAnswers((current) => ({...current,[id]:values}));
  const sectionComplete = () => questions.every((q) => q.kind === "context" || (q.primaryOf && answers[q.primaryOf]?.length === 1 && answers[q.primaryOf]?.[0] === "I'm still figuring that out") || Boolean(answers[q.id]?.length)) && (section !== 6 || ["q36-geography","q36-stakeholders","q36-stage"].every((id) => answers[id]?.length));
  const next = () => { if (!sectionComplete()) { setError("Please answer each question in this section before continuing."); return; } setError(""); if(section < 6) {setSection(section+1); window.scrollTo(0,0);} else setStage("concerns"); };
  const submit = () => { const concernDone = answers.concerns?.length && ((answers.concerns.length === 1 && answers.concerns[0] === concernExclusive) || answers["primary-concern"]?.length); if(!concernDone){setError("Please select your concerns and primary concern.");return;} setError(""); setStage("analyzing"); startTransition(async()=>{ const minimumDelay = new Promise((resolve)=>setTimeout(resolve,2200)); const result = await completeConferenceAssessment({intake,answers,consent,startedAt}); await minimumDelay; if(!result.ok){setStage("concerns");setError(result.errors.join(". "));return;} sessionStorage.removeItem(STORAGE_KEY); router.push(`/assessment/start/results/${result.id}`); }); };

  if(stage === "intake") return <Shell><p className="text-sm font-semibold text-blue-700">Franchise Ownership Assessment</p><h1 className="mt-2 text-3xl font-semibold text-slate-950">Tell us a little about yourself</h1><p className="mt-3 text-slate-600">This information helps your consultant prepare for a useful discovery conversation. It does not affect your assessment profile.</p><form className="mt-8 grid gap-5 sm:grid-cols-2" onSubmit={(event)=>{event.preventDefault();setStartedAt(new Date().toISOString());setStage("intro");window.scrollTo(0,0);}}>
    <Input label="First name" value={intake.firstName} required onChange={(v)=>setIntake({...intake,firstName:v})}/><Input label="Preferred name (optional)" value={intake.preferredName??""} onChange={(v)=>setIntake({...intake,preferredName:v})}/><Input label="Last name" value={intake.lastName} required onChange={(v)=>setIntake({...intake,lastName:v})}/><Input label="Email" type="email" value={intake.email} required onChange={(v)=>setIntake({...intake,email:v})}/><Input label="Mobile phone" type="tel" value={intake.mobilePhone} required onChange={(v)=>setIntake({...intake,mobilePhone:v})}/><Input label="Street address" value={intake.streetAddress} required onChange={(v)=>setIntake({...intake,streetAddress:v})}/><Input label="Address line 2 (optional)" value={intake.addressLine2??""} onChange={(v)=>setIntake({...intake,addressLine2:v})}/><Input label="City" value={intake.city} required onChange={(v)=>setIntake({...intake,city:v})}/><Input label="State/Province" value={intake.stateProvince} required onChange={(v)=>setIntake({...intake,stateProvince:v})}/><Input label="ZIP/Postal code" value={intake.postalCode} required onChange={(v)=>setIntake({...intake,postalCode:v})}/><Input label="Country" value={intake.country} required onChange={(v)=>setIntake({...intake,country:v})}/><Input label="Current occupation/title" value={intake.occupationTitle} required onChange={(v)=>setIntake({...intake,occupationTitle:v})}/><Input label="Current employer (optional)" value={intake.currentEmployer??""} onChange={(v)=>setIntake({...intake,currentEmployer:v})}/><Input label="LinkedIn profile (optional)" type="url" value={intake.linkedInProfile??""} onChange={(v)=>setIntake({...intake,linkedInProfile:v})}/>
    <Select label="Have you owned a business before?" value={intake.ownedBusinessBefore} onChange={(v)=>setIntake({...intake,ownedBusinessBefore:v as "yes"|"no"})} options={[["no","No"],["yes","Yes"]]}/>{intake.ownedBusinessBefore === "yes" && <Input label="Briefly describe your business ownership experience (optional)" value={intake.ownershipExperience??""} onChange={(v)=>setIntake({...intake,ownershipExperience:v})}/>}<Select label="Have you previously explored franchise ownership?" value={intake.exploredFranchiseBefore} onChange={(v)=>setIntake({...intake,exploredFranchiseBefore:v as "yes"|"no"})} options={[["no","No"],["yes","Yes"]]}/><Select label="Preferred contact method" value={intake.preferredContactMethod} onChange={(v)=>setIntake({...intake,preferredContactMethod:v as ConferenceIntake["preferredContactMethod"]})} options={[["phone","Phone"],["text","Text"],["email","Email"]]}/><Select label="Best general contact time" value={intake.bestContactTime} onChange={(v)=>setIntake({...intake,bestContactTime:v as ConferenceIntake["bestContactTime"]})} options={[["morning","Morning"],["afternoon","Afternoon"],["evening","Evening"]]}/><div className="sm:col-span-2"><Primary>Continue</Primary></div>
  </form></Shell>;
  if(stage === "intro") return <Shell><p className="text-sm font-semibold text-blue-700">About 10–15 minutes</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Discover Your Franchise Ownership Profile</h1><p className="mt-5 text-lg text-slate-600">This assessment helps identify what you&apos;re looking for in business ownership, how you prefer to operate, and the characteristics of a franchise opportunity that may fit you best.</p><p className="mt-4 text-slate-600">There are no right or wrong answers. Answer based on what you genuinely want—not what you think a business owner is supposed to say.</p><p className="mt-6 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Your responses will be used to create your Franchise Ownership Profile and help your consultant guide franchise discovery. Financial information is candidate-reported and is not independently verified by FranGroove.</p><label className="mt-6 flex min-h-12 items-center gap-3"><input type="checkbox" className="h-5 w-5" checked={consent} onChange={(e)=>setConsent(e.target.checked)}/><span>I understand and wish to continue.</span></label>{error&&<ErrorText text={error}/>}<div className="mt-8 flex gap-3"><Secondary onClick={()=>setStage("intake")}>Back</Secondary><Primary type="button" disabled={!consent} onClick={()=>{if(!consent){setError("Please confirm that you understand and wish to continue.");return;}setStage("assessment");}}>Begin assessment</Primary></div></Shell>;
  if(stage === "analyzing") return <Shell><div className="py-16 text-center" aria-live="polite"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-blue-100 border-t-blue-600"/><h1 className="mt-8 text-3xl font-semibold">Building your Franchise Ownership Profile</h1><p className="mt-4 text-slate-600">{pending ? "Evaluating how you prefer to lead and grow" : "Considering your financial and operating preferences"}</p><p className="mt-2 text-sm text-slate-500">Identifying priorities worth exploring with your consultant</p></div></Shell>;
  if(stage === "concerns") { const selected=answers.concerns??[]; return <Shell><Progress step={6}/><h1 className="mt-6 text-3xl font-semibold">What concerns you most about business ownership?</h1><p className="mt-2 text-slate-500">Select all that apply.</p><div className="mt-6"><ChoiceGroup question={{id:"concerns",section:6,kind:"multi",prompt:"Ownership concerns",options:concernOptions,exclusive:[concernExclusive],evidence:"primary concern"}} values={selected} onChange={(values)=>{setValue("concerns",values);if(values.includes(concernExclusive))setValue("primary-concern",[]);}}/></div>{selected.length>0&&!selected.includes(concernExclusive)&&<div className="mt-8"><h2 className="text-xl font-semibold">Which concern is primary?</h2><div className="mt-4"><ChoiceGroup question={{id:"primary-concern",section:6,kind:"single",prompt:"Primary concern",options:selected,evidence:"primary concern"}} values={answers["primary-concern"]??[]} onChange={(v)=>setValue("primary-concern",v)}/></div></div>}{error&&<ErrorText text={error}/>}<div className="mt-8 flex gap-3"><Secondary onClick={()=>{setStage("assessment");setSection(6)}}>Back</Secondary><Primary type="button" onClick={submit}>Build my profile</Primary></div></Shell>; }
  return <Shell><Progress step={section}/><p className="mt-5 text-sm font-semibold uppercase tracking-wider text-blue-700">Step {section} of 6</p><h1 className="mt-2 text-3xl font-semibold">{conferenceSectionTitles[section-1]}</h1><div className="mt-8 space-y-10">{questions.map((question)=> question.kind === "context" ? <ContextQuestion key={question.id} answers={answers} setValue={setValue}/> : <section key={question.id}><h2 className="text-xl font-semibold leading-snug">{question.prompt}</h2>{question.kind==="multi"&&<p className="mt-1 text-sm text-slate-500">Select all that apply.</p>}<div className="mt-4"><ChoiceGroup question={question.primaryOf ? {...question,options:answers[question.primaryOf]??[]} : question} values={answers[question.id]??[]} onChange={(v)=>setValue(question.id,v)}/></div></section>)}</div>{error&&<ErrorText text={error}/>}<div className="mt-10 flex justify-between"><Secondary onClick={()=>section===1?setStage("intro"):setSection(section-1)}>Back</Secondary><Primary type="button" onClick={next}>Continue</Primary></div></Shell>;
}

function ContextQuestion({answers,setValue}:{answers:ConferenceAnswers;setValue:(id:string,v:string[])=>void}) { return <section><h2 className="text-xl font-semibold">Final Discovery Context</h2><div className="mt-5 space-y-8"><div><h3 className="font-medium">What best describes your geographic flexibility?</h3><div className="mt-3"><ChoiceGroup question={{id:"q36-geography",section:6,kind:"single",prompt:"Geographic flexibility",options:geographyOptions,evidence:"geography"}} values={answers["q36-geography"]??[]} onChange={(v)=>setValue("q36-geography",v)}/></div></div><div><h3 className="font-medium">Who else is likely to be involved in this decision?</h3><p className="text-sm text-slate-500">Select all that apply.</p><div className="mt-3"><ChoiceGroup question={{id:"q36-stakeholders",section:6,kind:"multi",prompt:"Decision stakeholders",options:stakeholderOptions,exclusive:["Decision is primarily mine"],evidence:"stakeholders"}} values={answers["q36-stakeholders"]??[]} onChange={(v)=>setValue("q36-stakeholders",v)}/></div></div><div><h3 className="font-medium">Where are you in your ownership exploration?</h3><div className="mt-3"><ChoiceGroup question={{id:"q36-stage",section:6,kind:"single",prompt:"Ownership stage",options:ownershipStageOptions,evidence:"stage"}} values={answers["q36-stage"]??[]} onChange={(v)=>setValue("q36-stage",v)}/></div></div></div></section> }
function Shell({children}:{children:React.ReactNode}) { return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:py-12"><div className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><div className="mb-8 text-lg font-semibold tracking-tight">FranGroove <span className="text-blue-600">AI</span></div>{children}<p className="mt-10 border-t pt-5 text-xs text-slate-400">Conference assessment data is temporary and is not durable production storage.</p></div></main> }
function Input({label,value,onChange,required=false,type="text"}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean;type?:string}) { return <label className="grid gap-2 text-sm font-medium">{label}<input className="min-h-12 rounded-lg border border-slate-300 px-3 focus:ring-2 focus:ring-blue-500" value={value} onChange={(e)=>onChange(e.target.value)} required={required} type={type}/></label> }
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}) { return <label className="grid gap-2 text-sm font-medium">{label}<select className="min-h-12 rounded-lg border border-slate-300 px-3" value={value} onChange={(e)=>onChange(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label> }
function Primary({children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button {...props} className="min-h-12 rounded-xl bg-blue-700 px-6 font-semibold text-white hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50">{children}</button> }
function Secondary({children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button type="button" {...props} className="min-h-12 rounded-xl border border-slate-300 px-6 font-semibold hover:bg-slate-50">{children}</button> }
function ErrorText({text}:{text:string}) { return <p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-800">{text}</p> }
function Progress({step}:{step:number}) { return <div aria-label={`Assessment progress: step ${step} of 6`} role="progressbar" aria-valuemin={1} aria-valuemax={6} aria-valuenow={step} className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600 transition-all" style={{width:`${step/6*100}%`}}/></div> }
