'use client';
import { useMemo, useState, useSyncExternalStore } from 'react';
import Link from 'next/link';
import type { BrandIntelligenceProfile } from '../../brand-library/models/BrandIntelligenceProfile';
import PresentationMediaPicker from './PresentationMediaPicker';
import { colors, fontIds, fontNames } from '../../marketing/studio/document';
import { buildPresentation } from '../buildPresentation';
import { mediaSlots, slideTitles, type MediaSlot, type PresentationOptions, type AssetMap } from '../model';
import SlidePreview from './SlidePreview';
const slotLabels:Record<MediaSlot,string>={brandLogo:'Brand logo',hero:'Hero image',image2:'Business model image',image3:'Additional brand image',location:'Location image',productService:'Product/service image',operations:'Operations image',customerExperience:'Customer experience image',team:'Team image',marketing:'Marketing/general image',companyLogo:'Consultant/company logo'};
const subscribe=()=>()=>{};

export default function PresentationStudio({profile,options:initial,assets:initialAssets,mediaAvailable,demoAssets}:{profile:BrandIntelligenceProfile;options:PresentationOptions;assets:AssetMap;mediaAvailable:boolean;demoAssets?:AssetMap}) {
  const [options,setOptions]=useState(initial),[assets,setAssets]=useState(initialAssets),[index,setIndex]=useState(0),[picker,setPicker]=useState<MediaSlot|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const ready=useSyncExternalStore(subscribe,()=>true,()=>false);
  const presentation=useMemo(()=>buildPresentation(profile,options),[profile,options]);
  const update=<K extends keyof PresentationOptions>(key:K,value:PresentationOptions[K])=>setOptions(o=>({...o,[key]:value}));
  async function download(){setBusy(true);setError('');try{
    const response=await fetch(`/crm/brands/${profile.id}/presentation/download`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(options)});
    if(!response.ok){const data=await response.json();throw Error(data.error||'Download unavailable.');}
    const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`${profile.name} presentation.pptx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }catch(e){setError(e instanceof Error?e.message:'Download unavailable.');}finally{setBusy(false);}}
  return <main data-studio-ready={ready} className="min-h-[85vh] space-y-5" aria-label="Brand Presentation Studio">
    <header className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-slate-950 p-5 text-white"><div><Link href={`/crm/brands/${profile.id}`} className="text-sm text-slate-300">← Brand Intelligence</Link><p className="mt-3 text-xs font-bold uppercase tracking-[.2em] text-teal-300">Brand Presentation Studio</p><h1 className="mt-1 text-2xl font-bold">{profile.name}</h1></div><button onClick={()=>void download()} disabled={busy} className="min-h-11 rounded-xl bg-teal-300 px-5 py-3 font-bold text-slate-950 disabled:opacity-50">{busy?'Preparing PowerPoint…':'Download PowerPoint'}</button></header>
    {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>}
    <div className="grid items-start gap-5 xl:grid-cols-[280px_minmax(0,1fr)]">
      <fieldset disabled={!ready} className="space-y-4 rounded-2xl border bg-white p-4 xl:max-h-[78vh] xl:overflow-auto">
        <nav aria-label="Presentation slides" className="space-y-1">{slideTitles.map((title,i)=><button key={title} onClick={()=>setIndex(i)} aria-current={index===i?'step':undefined} className={`flex min-h-11 w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm ${index===i?'bg-slate-950 font-bold text-white':'text-slate-600 hover:bg-slate-100'}`}><span className="opacity-60">0{i+1}</span>{title}</button>)}</nav>
        <fieldset className="space-y-3 border-t pt-4"><legend className="font-bold">Presentation</legend><label className="block text-sm">Cover title<input maxLength={70} value={options.title} placeholder={profile.name} onChange={e=>update('title',e.target.value)} className="mt-1 w-full rounded-lg border p-2"/></label><label className="block text-sm">Cover subtitle<input maxLength={140} value={options.subtitle} placeholder="Use approved brand description" onChange={e=>update('subtitle',e.target.value)} className="mt-1 w-full rounded-lg border p-2"/></label><p className="text-xs text-slate-500">Titles are your presentation wording, not verified brand facts. Keep claims grounded in the approved profile.</p>{([['showSupport','Include support'],['showFees','Include fees'],['showConsiderations','Include considerations']] as const).map(([key,label])=><label key={key} className="flex min-h-9 items-center gap-2 text-sm"><input type="checkbox" checked={options[key]} onChange={e=>update(key,e.target.checked)}/>{label}</label>)}</fieldset>
        <fieldset className="space-y-3 border-t pt-4"><legend className="font-bold">Images</legend><p className="text-xs text-slate-500">Your selections are presentation-only. Image identity is not independently verified.</p>{!mediaAvailable&&<p className="text-xs text-amber-800">Workspace media is unavailable in conference demo mode. Image selection uses the existing media library in an authenticated persisted workspace.</p>}{mediaSlots.map(slot=><div key={slot} className="flex flex-wrap gap-2"><button disabled={!mediaAvailable} onClick={()=>setPicker(slot)} className="min-h-10 rounded-lg border px-3 text-left text-sm disabled:opacity-50">{options.assets[slot]?'Change':'Choose'} {slotLabels[slot]}</button>{options.assets[slot]&&<button aria-label={`Remove ${slotLabels[slot]}`} onClick={()=>update('assets',{...options.assets,[slot]:null})} className="text-xs underline">Remove</button>}</div>)}<label className="block text-sm">Photo fit<select value={options.imageFit} onChange={e=>update('imageFit',e.target.value as 'cover'|'contain')} className="ml-2 rounded border p-1"><option value="cover">Crop to fill</option><option value="contain">Show whole image</option></select></label><p className="text-xs text-slate-500">Logos always retain their proportions.</p></fieldset>
        <fieldset className="space-y-2 border-t pt-4"><legend className="font-bold">Brand presentation palette</legend><p className="text-xs text-slate-500">Presentation-only colors, not verified franchise brand standards.</p>{(['primaryColor','secondaryColor','accentColor'] as const).map(key=><label key={key} className="block text-sm">{{primaryColor:'Primary color',secondaryColor:'Secondary color',accentColor:'Accent color'}[key]}<select value={options.visualIdentity[key]} onChange={e=>update('visualIdentity',{...options.visualIdentity,[key]:e.target.value as PresentationOptions['visualIdentity']['primaryColor']})} className="ml-2 rounded border p-1">{colors.map(c=><option key={c}>{c}</option>)}</select></label>)}</fieldset>
        <details className="border-t pt-4"><summary className="cursor-pointer py-2 font-bold">Consultant branding</summary><p className="mb-3 text-xs text-slate-500">Changes apply only to this presentation.</p>{(['name','company','title','email','phone','website'] as const).map(key=><label key={key} className="mb-2 block text-sm capitalize">{key}<input value={options.branding[key]} maxLength={{name:70,company:80,title:90,email:100,phone:40,website:140}[key]} onChange={e=>update('branding',{...options.branding,[key]:e.target.value})} className="mt-1 w-full rounded-lg border p-2"/></label>)}<label className="mt-2 block text-sm">Font<select value={options.branding.font} onChange={e=>update('branding',{...options.branding,font:e.target.value as PresentationOptions['branding']['font']})} className="ml-2 rounded border p-1">{fontIds.map(f=><option key={f} value={f}>{fontNames[f]}</option>)}</select></label></details>
      </fieldset>
      <section className="min-w-0 space-y-4 xl:sticky xl:top-5" aria-label="Presentation preview"><div className="flex items-center justify-between gap-3"><p className="text-sm font-bold text-slate-600">Slide {index+1} of 5</p><div className="flex gap-2"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)} className="min-h-10 rounded-lg border bg-white px-3 disabled:opacity-40">Previous</button><button disabled={index===4} onClick={()=>setIndex(i=>i+1)} className="min-h-10 rounded-lg border bg-white px-3 disabled:opacity-40">Next</button></div></div><SlidePreview presentation={presentation} index={index} assets={assets}/><p className="text-xs text-slate-500">Editable PowerPoint · 16:9 · Five slides · Source details in slide notes</p><details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer text-sm font-bold">Sources & qualifications for this slide</summary><pre className="mt-3 whitespace-pre-wrap break-words text-xs leading-6 text-slate-600">{presentation.slides[index].notes}</pre></details></section>
    </div>
    {picker&&<div className="fixed inset-0 z-50 overflow-auto bg-slate-950/60 p-6"><div className="mx-auto max-w-4xl"><PresentationMediaPicker demoAssets={demoAssets} onClose={()=>setPicker(null)} onSelect={asset=>{setAssets(a=>({...a,[asset.public_id]:asset}));update('assets',{...options.assets,[picker]:asset.public_id});setPicker(null);}}/></div></div>}
  </main>;
}
