"use server";
import { revalidatePath } from "next/cache";
import { CalendarValidationError } from "../services/CalendarService";
import { DEMO_CONSULTANT_TIMEZONE, localDateTimeToIso } from "../time/ConsultantTime";
import { resolveWorkspaceComposition } from "@/feature/platform/composition/resolveWorkspaceComposition";
import type { DemoWorkspaceComposition } from "@/feature/platform/composition/DemoWorkspaceComposition";
export type CalendarActionState = { status: "idle" | "success" | "error"; message?: string; eventId?: string };
const refresh = (candidateId?: string) => { revalidatePath("/crm/calendar"); revalidatePath("/crm"); if (candidateId) revalidatePath(`/crm/candidates/${candidateId}`); };
async function demo():Promise<DemoWorkspaceComposition|null>{const value=await resolveWorkspaceComposition();return value.status==="resolved"&&"runtimes" in value.composition?value.composition:null;}
const unavailable=():CalendarActionState=>({status:"error",message:"Calendar is not available in this workspace."});
export async function createMeetingAction(_previous: CalendarActionState, formData: FormData): Promise<CalendarActionState> { const c=await demo();if(!c)return unavailable();try { const timezone=String(formData.get("timezone")??DEMO_CONSULTANT_TIMEZONE);const input={title:String(formData.get("title")??""),candidateId:String(formData.get("candidateId")??"")||undefined,startAt:localDateTimeToIso(String(formData.get("startAt")??""),timezone),endAt:localDateTimeToIso(String(formData.get("endAt")??""),timezone),timezone,location:String(formData.get("location")??""),meetingUrl:String(formData.get("meetingUrl")??""),description:String(formData.get("description")??"")};const eventId=String(formData.get("eventId")??"");const service=c.runtimes.createCalendarService();const event=eventId?await service.update(c.runtimes.consultant.id,eventId,input):await service.create(c.runtimes.consultant.id,input);refresh(event.candidateId);return {status:"success",message:eventId?"Meeting updated.":"Meeting scheduled.",eventId:event.id};}catch(error){return {status:"error",message:error instanceof CalendarValidationError?error.message:"Meeting could not be saved."};}}
export async function transitionMeetingAction(_previous:CalendarActionState,formData:FormData):Promise<CalendarActionState>{const c=await demo();if(!c)return unavailable();try{const status=String(formData.get("status")) as "completed"|"cancelled"|"no-show";if(!["completed","cancelled","no-show"].includes(status))throw new CalendarValidationError("Choose a valid meeting status.");const event=await c.runtimes.createCalendarService().transition(c.runtimes.consultant.id,String(formData.get("eventId")),status,String(formData.get("notes")??""));refresh(event.candidateId);return {status:"success",message:`Meeting marked ${status}.`,eventId:event.id};}catch(error){return {status:"error",message:error instanceof CalendarValidationError?error.message:"Meeting could not be updated."};}}
export async function createReminderAction(_previous:CalendarActionState,formData:FormData):Promise<CalendarActionState>{const c=await demo();if(!c)return unavailable();try{const reminder=await c.runtimes.createCalendarService().remind(c.runtimes.consultant.id,String(formData.get("referenceType")) as "task"|"calendar-event"|"candidate",String(formData.get("referenceId")),String(formData.get("remindAt")));refresh();return {status:"success",message:"Reminder created.",eventId:reminder.referenceId};}catch(error){return {status:"error",message:error instanceof CalendarValidationError?error.message:"Reminder could not be created."};}}
export async function createMeetingFollowUpTaskAction(_previous:CalendarActionState,formData:FormData):Promise<CalendarActionState>{const c=await demo();if(!c)return unavailable();const event=await c.dependencies.calendar.getEvent(String(formData.get("eventId")));if(!event||event.consultantId!==c.runtimes.consultant.id||!event.candidateId||event.status!=="completed")return {status:"error",message:"Completed meeting not found."};const task=await c.runtimes.createTaskService().create(c.runtimes.consultant.id,{title:`Follow up: ${event.title}`,description:event.notes,dueAt:String(formData.get("dueAt")),priority:"high",candidateId:event.candidateId},{source:"system",sourceReferenceId:`meeting-followup:${event.id}`,recommendedReason:"Consultant accepted the post-meeting follow-up recommendation."});refresh(event.candidateId);revalidatePath("/crm/tasks");return {status:"success",message:"Follow-up task created.",eventId:task.taskId};}
