"use server";
import { revalidatePath } from "next/cache";
import { CalendarValidationError } from "../services/CalendarService";
import { DEMO_CONSULTANT_TIMEZONE, localDateTimeToIso } from "../time/ConsultantTime";

import { resolveConsultantSchedule } from "@/feature/tasks/runtime/resolveConsultantSchedule";

export type CalendarActionState = { status: "idle" | "success" | "error"; message?: string; eventId?: string };
const refresh = (candidateId?: string) => { revalidatePath("/crm/calendar"); revalidatePath("/crm"); if (candidateId) revalidatePath(`/crm/candidates/${candidateId}`); };
const demo = resolveConsultantSchedule;
const unavailable=():CalendarActionState=>({status:"error",message:"Calendar is not available in this workspace."});
export async function createMeetingAction(_previous: CalendarActionState, formData: FormData): Promise<CalendarActionState> { const c=await demo();if(!c)return unavailable();try { const timezone=String(formData.get("timezone")??DEMO_CONSULTANT_TIMEZONE);const input={title:String(formData.get("title")??""),eventType:String(formData.get("eventType")??"Meeting"),candidateId:String(formData.get("candidateId")??"")||undefined,startAt:localDateTimeToIso(String(formData.get("startAt")??""),timezone),endAt:localDateTimeToIso(String(formData.get("endAt")??""),timezone),timezone,location:String(formData.get("location")??""),meetingUrl:String(formData.get("meetingUrl")??""),description:String(formData.get("description")??"")};const eventId=String(formData.get("eventId")??"");const service=c.calendarService;const event=eventId?await service.update(c.consultantId,eventId,input):await service.create(c.consultantId,input);refresh(event.candidateId);return {status:"success",message:eventId?"Meeting updated.":"Meeting scheduled.",eventId:event.id};}catch(error){return {status:"error",message:error instanceof CalendarValidationError?error.message:"Meeting could not be saved."};}}
export async function transitionMeetingAction(_previous:CalendarActionState,formData:FormData):Promise<CalendarActionState>{const c=await demo();if(!c)return unavailable();try{const status=String(formData.get("status")) as "completed"|"cancelled"|"no-show";if(!["completed","cancelled","no-show"].includes(status))throw new CalendarValidationError("Choose a valid meeting status.");const event=await c.calendarService.transition(c.consultantId,String(formData.get("eventId")),status,String(formData.get("notes")??""));refresh(event.candidateId);return {status:"success",message:`Meeting marked ${status}.`,eventId:event.id};}catch(error){return {status:"error",message:error instanceof CalendarValidationError?error.message:"Meeting could not be updated."};}}
export async function createReminderAction(_previous:CalendarActionState,formData:FormData):Promise<CalendarActionState>{const c=await demo();if(!c)return unavailable();try{const reminder=await c.calendarService.remind(c.consultantId,String(formData.get("referenceType")) as "task"|"calendar-event"|"candidate",String(formData.get("referenceId")),String(formData.get("remindAt")));refresh();return {status:"success",message:"Reminder created.",eventId:reminder.referenceId};}catch(error){return {status:"error",message:error instanceof CalendarValidationError?error.message:"Reminder could not be created."};}}
export async function createMeetingFollowUpTaskAction(_previous:CalendarActionState,formData:FormData):Promise<CalendarActionState>{const c=await demo();if(!c)return unavailable();const event=await c.calendar.getEvent(String(formData.get("eventId")));if(!event||event.consultantId!==c.consultantId||!event.candidateId||event.status!=="completed")return {status:"error",message:"Completed meeting not found."};const task=await c.taskService.create(c.consultantId,{title:`Follow up: ${event.title}`,description:event.notes,dueAt:String(formData.get("dueAt")),priority:"high",candidateId:event.candidateId},{source:"system",sourceReferenceId:`meeting-followup:${event.id}`,recommendedReason:"Consultant accepted the post-meeting follow-up recommendation."});refresh(event.candidateId);revalidatePath("/crm/tasks");return {status:"success",message:"Follow-up task created.",eventId:task.taskId};}
