"use client";

import { useActionState, useEffect, useState } from "react";
import Link from "next/link";
import { ChevronDown, CircleAlert, Plus, Sparkles, X } from "lucide-react";
import { useRouter } from "next/navigation";
import type { TaskFilter, TaskView, TaskWorkspaceState } from "../models/TaskWorkspaceState";
import { acceptRecommendationAction, dismissRecommendationAction, transitionTaskAction, type TaskActionState } from "../actions/task-actions";
import { TaskForm } from "./TaskForm";

const initial: TaskActionState = { status: "idle" };
const filters: Array<{ id: TaskFilter; label: string }> = [{ id: "today", label: "Today" }, { id: "upcoming", label: "Upcoming" }, { id: "overdue", label: "Overdue" }, { id: "completed", label: "Completed" }, { id: "all", label: "All" }];

function Transition({ task, operation, label }: { task: TaskView; operation: "complete" | "cancel" | "reopen"; label: string }) {
  const router = useRouter(); const [state, action, pending] = useActionState(transitionTaskAction, initial);
  useEffect(() => { if (state.status === "success") router.refresh(); }, [state.status, router]);
  return <form action={action}><input type="hidden" name="taskId" value={task.taskId} /><input type="hidden" name="operation" value={operation} /><button disabled={pending} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-black text-slate-700 hover:border-blue-400 hover:text-blue-700 disabled:opacity-50">{pending ? "Working…" : label}</button></form>;
}

function RecommendationAction({ id, kind, accepted }: { id: string; kind: "accept" | "dismiss"; accepted?: string }) {
  const router = useRouter(); const actionFn = kind === "accept" ? acceptRecommendationAction : dismissRecommendationAction; const [state, action, pending] = useActionState(actionFn, initial);
  useEffect(() => { if (state.status === "success") router.refresh(); }, [state.status, router]);
  if (accepted && kind === "accept") return <span className="text-xs font-black text-emerald-700">Task created</span>;
  return <form action={action}><input type="hidden" name="recommendationId" value={id} /><button disabled={pending || Boolean(accepted)} className={kind === "accept" ? "rounded-lg bg-blue-600 px-3 py-2 text-xs font-black text-white disabled:opacity-50" : "rounded-lg px-3 py-2 text-xs font-black text-slate-500 hover:bg-slate-100"}>{pending ? "Working…" : kind === "accept" ? "Create Task" : "Dismiss"}</button></form>;
}

export function TaskWorkspacePage({ state }: { state: TaskWorkspaceState }) {
  const [filter, setFilter] = useState<TaskFilter>("today"); const [search, setSearch] = useState(""); const [creating, setCreating] = useState(false); const [expanded, setExpanded] = useState<string | null>(null); const [editing, setEditing] = useState<string | null>(null);
  const visible = state.tasks.filter((task) => { const matches = !search || `${task.title} ${task.candidateName ?? ""}`.toLowerCase().includes(search.toLowerCase()); if (!matches) return false; if (filter === "today") return task.dueToday; if (filter === "upcoming") return task.status === "open" && !task.overdue && !task.dueToday; if (filter === "overdue") return task.overdue; if (filter === "completed") return task.status === "completed"; return true; });
  return <main className="space-y-6 p-6 lg:p-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">Daily execution</p><h1 className="mt-1 text-4xl font-black text-slate-950">Tasks</h1><p className="mt-2 text-slate-600">The work you have accepted, ordered by urgency and due date.</p></div><button onClick={() => setCreating(true)} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-black text-white"><Plus size={16} />New Task</button></header>
    {creating && <section className="rounded-2xl border border-blue-200 bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><h2 className="text-xl font-black">New Task</h2><button aria-label="Close new task form" onClick={() => setCreating(false)}><X /></button></div><TaskForm candidates={state.candidates} defaultDueAt={state.defaultDueAt} onDone={() => setCreating(false)} /></section>}
    {state.recommendations.some((item) => !item.acceptedTaskId) && <section aria-label="AI follow-up recommendations" className="rounded-2xl border border-indigo-200 bg-indigo-50/60 p-5"><div className="flex items-center gap-2"><Sparkles className="text-indigo-600" size={18} /><h2 className="font-black text-indigo-950">FranGroove Follow-Up Recommendations</h2></div><p className="mt-1 text-sm text-indigo-800">Recommendations stay advisory until you create a task.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{state.recommendations.filter((item) => !item.acceptedTaskId).map((item) => <article key={item.recommendationId} data-recommendation-id={item.recommendationId} className="rounded-xl border border-indigo-100 bg-white p-4"><p className="font-black text-slate-900">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.reason}</p><p className="mt-2 text-xs font-bold uppercase text-indigo-600">AI recommendation · {item.source.replaceAll("-", " ")}</p><div className="mt-3 flex gap-2"><RecommendationAction id={item.recommendationId} kind="accept" /><RecommendationAction id={item.recommendationId} kind="dismiss" /></div></article>)}</div></section>}
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap gap-3 border-b border-slate-200 p-4">{filters.map((item) => <button key={item.id} aria-pressed={filter === item.id} onClick={() => setFilter(item.id)} className={`rounded-xl px-4 py-2 text-sm font-black ${filter === item.id ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-600"}`}>{item.label} <span className="ml-1 opacity-70">{state.counts[item.id]}</span></button>)}<label className="ml-auto"><span className="sr-only">Search tasks</span><input aria-label="Search tasks" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search tasks or candidates" className="rounded-xl border border-slate-300 px-3 py-2 text-sm" /></label></div>
      <div className="divide-y divide-slate-100">{visible.map((task) => <article key={task.taskId} data-task-id={task.taskId} className="p-4"><div className="flex flex-wrap items-center gap-4"><button aria-label={`View ${task.title}`} onClick={() => setExpanded(expanded === task.taskId ? null : task.taskId)} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span className={`h-3 w-3 shrink-0 rounded-full ${task.overdue ? "bg-red-600" : task.priority === "urgent" ? "bg-orange-500" : task.priority === "high" ? "bg-amber-500" : "bg-slate-300"}`} /><span className="min-w-0"><span className="block truncate font-black text-slate-900">{task.title}</span><span className="mt-1 block text-xs text-slate-500">{task.candidateName ?? "General task"} · {task.sourceLabel}</span></span><ChevronDown size={16} className="text-slate-400" /></button><span className={`text-sm font-black ${task.overdue ? "text-red-700" : "text-slate-700"}`}>{task.overdue && <CircleAlert aria-label="Overdue" className="mr-1 inline" size={15} />}{task.overdue ? "Overdue · " : ""}{task.dueLabel}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase text-slate-600">{task.priority}</span>{task.status === "open" ? <Transition task={task} operation="complete" label="Complete" /> : task.status === "completed" ? <Transition task={task} operation="reopen" label="Reopen" /> : <Transition task={task} operation="reopen" label="Reopen" />}</div>
        {expanded === task.taskId && <div className="ml-6 mt-4 rounded-xl bg-slate-50 p-4 text-sm"><p>{task.description || "No notes."}</p>{task.recommendedReason && <p className="mt-2"><strong>Why:</strong> {task.recommendedReason}</p>}{task.candidateHref && <Link href={task.candidateHref} className="mt-3 inline-block font-black text-blue-700">Open {task.candidateName}</Link>}<div className="mt-4 flex gap-2"><button onClick={() => setEditing(editing === task.taskId ? null : task.taskId)} className="rounded-lg border px-3 py-1.5 text-xs font-black">Edit</button>{task.status === "open" && <Transition task={task} operation="cancel" label="Cancel" />}</div>{editing === task.taskId && <div className="mt-4"><TaskForm task={task} candidates={state.candidates} defaultDueAt={state.defaultDueAt} onDone={() => setEditing(null)} /></div>}</div>}
      </article>)}{visible.length === 0 && <p className="p-10 text-center text-sm font-bold text-slate-500">No tasks in this view.</p>}</div>
    </section>
  </main>;
}
