import Link from "next/link";
import type { ContactRecord } from "../models/Contact";
import { PromoteContact } from "./PromoteContact";

const value=(input:string)=>input||"Not provided";
export function ContactDetail({ contact }: { contact:ContactRecord }) {
  const location=[contact.addressLine1,contact.addressLine2,[contact.city,contact.stateProvince].filter(Boolean).join(", "),contact.postalCode,contact.country].filter(Boolean);
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/crm/contacts" className="text-sm font-bold text-slate-500">Back to Contacts</Link><p className="mt-5 text-xs font-black uppercase tracking-[.2em] text-teal-600">Contact Detail</p><h1 className="mt-1 text-3xl font-black">{contact.displayName}</h1><p className="mt-2 text-slate-600">{contact.titleOccupation}{contact.titleOccupation&&contact.company?" at ":""}{contact.company}</p></div><Link href={`/crm/contacts/${contact.id}/edit`} className="rounded-xl border bg-white px-5 py-3 text-center font-bold">Edit Contact</Link></header>
    <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="space-y-5 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Identity and contact</h2><dl className="grid gap-5 sm:grid-cols-2"><Item label="Email" value={value(contact.primaryEmail)}/><Item label="Phone" value={value(contact.primaryPhone)}/><Item label="Preferred name" value={value(contact.preferredName)}/><Item label="Source" value={contact.source}/><Item label="Assigned consultant" value={contact.assignedConsultantName}/><Item label="Date added" value={new Intl.DateTimeFormat("en-US",{dateStyle:"medium"}).format(new Date(contact.createdAt))}/></dl><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Address / location</p><p className="mt-2 whitespace-pre-line text-sm font-semibold text-slate-700">{location.length?location.join("\n"):"Not provided"}</p></div></div>
      <aside className="space-y-5"><section className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-wide text-teal-300">Relationship</p><h2 className="mt-2 text-2xl font-black">{contact.lifecycleStatus.replaceAll("-"," ")}</h2><p className="mt-3 text-sm text-slate-300">A contact exists independently of candidate participation.</p>{contact.candidate?<Link href={`/crm/candidates/${contact.candidate.publicId}`} className="mt-5 inline-flex rounded-xl bg-white px-5 py-3 font-bold text-slate-950">Open Candidate 360</Link>:<div className="mt-5"><PromoteContact contactId={contact.id} eligible={Boolean(contact.primaryEmail)}/></div>}</section><section className="rounded-2xl border bg-white p-6"><h2 className="font-black">Communication eligibility</h2><dl className="mt-4 grid grid-cols-2 gap-3"><Item label="Marketing email" value={contact.marketingEmailStatus}/><Item label="Marketing SMS" value={contact.marketingSmsStatus}/></dl><p className="mt-4 text-xs leading-5 text-slate-500">Operational candidate communication remains separate from marketing consent and suppression.</p></section></aside></section>
  </div>;
}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 break-words text-sm font-bold text-slate-800">{value}</dd></div>}
