import Link from "next/link";
import { Search, UserPlus } from "lucide-react";
import type { ContactListPage, ContactLifecycleStatus } from "../models/Contact";

const labels: Record<ContactLifecycleStatus,string> = { prospect:"Prospect", engaged:"Engaged", "active-candidate":"Active Candidate", nurture:"Nurture", "closed-placed":"Closed / Placed", historical:"Historical" };
const formatDate = (value:string) => new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value));

export function ContactsWorkspace({ page, search, lifecycle }: { page:ContactListPage; search:string; lifecycle:string }) {
  const next = page.nextCursor ? Buffer.from(JSON.stringify(page.nextCursor)).toString("base64url") : null;
  const query = new URLSearchParams(); if(search)query.set("q",search);if(lifecycle)query.set("lifecycle",lifecycle);if(next)query.set("cursor",next);
  return <div className="space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-teal-600">Permanent people directory</p><h1 className="mt-1 text-3xl font-black">Contacts</h1><p className="mt-2 text-sm text-slate-600">One human record across prospect, candidate, and historical relationships.</p></div><Link href="/crm/contacts/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white"><UserPlus size={17}/>Add Contact</Link></header>
    <form role="search" className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm sm:grid-cols-[1fr_220px_auto]"><label className="relative"><span className="sr-only">Search contacts</span><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input name="q" defaultValue={search} placeholder="Search name, email, phone, or company" className="w-full rounded-xl border bg-slate-50 py-2.5 pl-10 pr-3 text-sm"/></label><label><span className="sr-only">Filter by lifecycle</span><select name="lifecycle" defaultValue={lifecycle} className="w-full rounded-xl border bg-white px-3 py-2.5 text-sm font-semibold"><option value="">All lifecycle statuses</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white">Apply</button></form>
    {page.contacts.length === 0 ? <section className="rounded-2xl border border-dashed bg-white p-12 text-center"><h2 className="font-black">{search||lifecycle?"No contacts match these filters":"No contacts yet"}</h2><p className="mt-2 text-sm text-slate-500">{search||lifecycle?"Try a broader search or clear the lifecycle filter.":"Add a person without starting a candidate workflow."}</p></section> : <>
      <section className="hidden overflow-hidden rounded-2xl border bg-white shadow-sm md:block"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Name","Email / phone","Lifecycle","Source","Assigned consultant","Candidate","Date added",""].map((x)=><th key={x||"open"} className="border-b px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{page.contacts.map((contact)=><tr key={contact.id} className="hover:bg-blue-50/40"><td className="px-4 py-3"><Link className="font-black text-slate-900 hover:text-blue-700" href={`/crm/contacts/${contact.id}`}>{contact.displayName}</Link>{contact.company&&<span className="block text-xs text-slate-500">{contact.company}</span>}</td><td className="px-4 py-3 text-slate-600"><span className="block">{contact.primaryEmail||"No email"}</span><span className="text-xs">{contact.primaryPhone||"No phone"}</span></td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{labels[contact.lifecycleStatus]}</span></td><td className="px-4 py-3">{contact.source}</td><td className="px-4 py-3">{contact.assignedConsultantName}</td><td className="px-4 py-3">{contact.candidate?<Link className="font-bold text-blue-700" href={`/crm/candidates/${contact.candidate.publicId}`}>{contact.candidate.pipelineStageId}</Link>:"Not a candidate"}</td><td className="px-4 py-3 whitespace-nowrap">{formatDate(contact.createdAt)}</td><td className="px-4 py-3"><Link aria-label={`Open ${contact.displayName}`} href={`/crm/contacts/${contact.id}`} className="font-bold text-blue-700">Open</Link></td></tr>)}</tbody></table></div></section>
      <section className="grid gap-3 md:hidden">{page.contacts.map((contact)=><article key={contact.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><Link href={`/crm/contacts/${contact.id}`} className="font-black text-slate-900">{contact.displayName}</Link><p className="mt-1 break-all text-sm text-slate-600">{contact.primaryEmail||"No email"}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold">{labels[contact.lifecycleStatus]}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-400">Source</dt><dd className="font-bold">{contact.source}</dd></div><div><dt className="text-slate-400">Candidate</dt><dd className="font-bold">{contact.candidate?"Linked":"No"}</dd></div></dl></article>)}</section>
      {next&&<div className="flex justify-center"><Link href={`/crm/contacts?${query}`} className="rounded-xl border bg-white px-5 py-3 text-sm font-bold">Next contacts</Link></div>}
    </>}
  </div>;
}
