import type { CandidateRepository } from "@/feature/crm/repositories/CandidateRepository";
import type { CandidateActivityRepository } from "@/feature/crm/repositories/CandidateActivityRepository";
import type { CalendarEventStatus, ConsultantCalendarEvent, ConsultantReminder } from "../models/ConsultantCalendarEvent";
import type { CalendarRepository } from "../repositories/CalendarRepository";

export class CalendarValidationError extends Error {}
export interface MeetingInput { title: string; candidateId?: string; startAt: string; endAt: string; timezone: string; location?: string; meetingUrl?: string; description?: string; }
export class CalendarService {
  constructor(private readonly repository: CalendarRepository, private readonly candidates: CandidateRepository, private readonly activities: CandidateActivityRepository) {}
  async create(consultantId: string, input: MeetingInput) { await this.validate(consultantId, input); const duplicate = (await this.repository.getEvents(consultantId)).find((item) => item.status === "scheduled" && item.title.trim().toLowerCase() === input.title.trim().toLowerCase() && item.startAt === new Date(input.startAt).toISOString()); if (duplicate) return duplicate; const now = new Date().toISOString(); const event: ConsultantCalendarEvent = { id: `meeting-${crypto.randomUUID()}`, consultantId, title: input.title.trim(), candidateId: input.candidateId || undefined, startAt: new Date(input.startAt).toISOString(), endAt: new Date(input.endAt).toISOString(), timezone: input.timezone, location: input.location?.trim() || undefined, meetingUrl: input.meetingUrl?.trim() || undefined, description: input.description?.trim() || undefined, relatedTaskIds: [], source: "consultant-created", status: "scheduled", createdAt: now, updatedAt: now }; await this.repository.saveEvent(event); await this.activity(event, "meeting-scheduled", "Meeting Scheduled"); return event; }
  async update(consultantId: string, id: string, input: MeetingInput) { const current = await this.owned(consultantId, id); await this.validate(consultantId, input); const updated: ConsultantCalendarEvent = { ...current, title: input.title.trim(), candidateId: input.candidateId || undefined, startAt: new Date(input.startAt).toISOString(), endAt: new Date(input.endAt).toISOString(), timezone: input.timezone, location: input.location?.trim() || undefined, meetingUrl: input.meetingUrl?.trim() || undefined, description: input.description?.trim() || undefined, updatedAt: new Date().toISOString() }; await this.repository.saveEvent(updated); return updated; }
  async transition(consultantId: string, id: string, status: Exclude<CalendarEventStatus, "scheduled">, notes?: string) { const event = await this.owned(consultantId, id); const updated = { ...event, status, notes: notes?.trim() || event.notes, updatedAt: new Date().toISOString() }; await this.repository.saveEvent(updated); await this.activity(updated, status === "completed" ? "meeting-completed" : status === "cancelled" ? "meeting-cancelled" : "meeting-no-show", status === "completed" ? "Meeting Completed" : status === "cancelled" ? "Meeting Cancelled" : "Meeting No Show"); return updated; }
  async remind(consultantId: string, referenceType: ConsultantReminder["referenceType"], referenceId: string, remindAt: string) { if (!referenceId || Number.isNaN(Date.parse(remindAt))) throw new CalendarValidationError("Choose a valid reminder time."); const existing = (await this.repository.getReminders(consultantId)).find((item) => item.referenceType === referenceType && item.referenceId === referenceId && item.remindAt === new Date(remindAt).toISOString() && item.status === "pending"); if (existing) return existing; const createdAt = new Date().toISOString(); const reminder: ConsultantReminder = { id: `reminder-${crypto.randomUUID()}`, consultantId, referenceType, referenceId, remindAt: new Date(remindAt).toISOString(), status: "pending", createdBy: "consultant", createdAt }; await this.repository.saveReminder(reminder); return reminder; }
  private async owned(consultantId: string, id: string) { const event = await this.repository.getEvent(id); if (!event || event.consultantId !== consultantId) throw new CalendarValidationError("Meeting not found."); return event; }
  private async validate(consultantId: string, input: MeetingInput) { if (!input.title.trim()) throw new CalendarValidationError("Meeting title is required."); if (Number.isNaN(Date.parse(input.startAt)) || Number.isNaN(Date.parse(input.endAt)) || Date.parse(input.endAt) <= Date.parse(input.startAt)) throw new CalendarValidationError("End time must be after start time."); if (!input.timezone) throw new CalendarValidationError("Timezone is required."); if (input.meetingUrl) { try { new URL(input.meetingUrl); } catch { throw new CalendarValidationError("Enter a valid meeting URL."); } } if (input.candidateId) { const candidate = await this.candidates.getById(input.candidateId); if (!candidate || candidate.consultantId !== consultantId) throw new CalendarValidationError("Candidate not found for this consultant."); } }
  private async activity(event: ConsultantCalendarEvent, type: "meeting-scheduled" | "meeting-completed" | "meeting-cancelled" | "meeting-no-show", title: string) { if (!event.candidateId) return; await this.activities.add({ id: `${type}:${event.id}:${event.updatedAt}`, candidateId: event.candidateId, consultantId: event.consultantId, type, title, description: event.title, createdAt: event.updatedAt, metadata: { calendarEventId: event.id } }); }
}
