import 'server-only';import type{SupabaseClient}from'@supabase/supabase-js';import type{Database}from'@/types/database.generated';import type{AuthenticatedWorkspaceContext}from'@/feature/identity/models/WorkspaceIdentity';import type{Campaign,MarketingOptions,Segment,SegmentCriteria}from'../models/Marketing';import{asCriteria,contentSchema}from'../models/validation';import type{MarketingRepository}from'./MarketingRepository';
type Client=SupabaseClient<Database>;
export class SupabaseMarketingRepository implements MarketingRepository{constructor(private db:Client,private ctx:AuthenticatedWorkspaceContext){}
 async options():Promise<MarketingOptions>{const[s,l,t,a]=await Promise.all([this.listSegments(),this.db.from('contact_lists').select('public_id,name').eq('organization_id',this.ctx.organization.id).order('name'),this.db.from('contact_tags').select('public_id,name').eq('organization_id',this.ctx.organization.id).order('name'),this.db.from('consultant_profiles').select('membership_id,display_name').eq('organization_id',this.ctx.organization.id)]);return{segments:s.map(x=>({id:x.id,name:x.name})),lists:(l.data??[]).map(x=>({id:x.public_id,name:x.name})),tags:(t.data??[]).map(x=>({id:x.public_id,name:x.name})),assignees:(a.data??[]).map(x=>({id:x.membership_id,name:x.display_name??'Consultant'}))};}
 async listSegments(){const{data,error}=await this.db.from('contact_segments').select('*').eq('organization_id',this.ctx.organization.id).order('updated_at',{ascending:false}).limit(100);if(error)throw new Error('Segments are temporarily unavailable.');return(data??[]).map(segment);}
 async getSegment(id:string){const{data,error}=await this.db.from('contact_segments').select('*').eq('organization_id',this.ctx.organization.id).eq('public_id',id).maybeSingle();if(error)throw new Error('Segment is temporarily unavailable.');return data?segment(data):undefined;}
 async saveSegment(input:{id?:string;name:string;description:string;criteria:SegmentCriteria}){const mutable={name:input.name.trim(),description:input.description.trim()||null,criteria_version:1,criteria:input.criteria};const q=input.id?this.db.from('contact_segments').update(mutable).eq('organization_id',this.ctx.organization.id).eq('public_id',input.id):this.db.from('contact_segments').insert({...mutable,organization_id:this.ctx.organization.id,created_by_membership_id:this.ctx.membership.id});const{data,error}=await q.select().single();if(error)throw new Error('Segment could not be saved.');return segment(data);}
 async duplicateSegment(id:string){const x=await this.getSegment(id);if(!x)throw new Error('Segment not found.');return this.saveSegment({name:`${x.name} copy`,description:x.description,criteria:x.criteria});}
 async previewCriteria(criteria:SegmentCriteria){const{data,error}=await this.db.rpc('resolve_segment',{target_criteria:criteria,page_limit:25,page_offset:0});if(error)throw new Error('Segment preview could not be resolved.');const rows=data??[];return{contacts:rows.map(x=>({id:x.contact_public_id,displayName:x.display_name,email:x.primary_email??'',emailStatus:x.email_status})),matching:Number(rows[0]?.total_count??0),eligible:rows.filter(x=>x.primary_email&&x.email_status==='opted-in').length,unknown:rows.filter(x=>x.email_status==='unknown').length,optedOut:rows.filter(x=>x.email_status==='opted-out').length,suppressed:rows.filter(x=>x.email_status==='suppressed').length,missingEmail:rows.filter(x=>!x.primary_email).length};}
 async listCampaigns(){const{data,error}=await this.db.from('marketing_campaigns').select('*').eq('organization_id',this.ctx.organization.id).order('updated_at',{ascending:false}).limit(100);if(error)throw new Error('Campaigns are temporarily unavailable.');return(data??[]).map(campaign);}
 async getCampaign(id:string){const{data,error}=await this.db.from('marketing_campaigns').select('*').eq('organization_id',this.ctx.organization.id).eq('public_id',id).maybeSingle();if(error)throw new Error('Campaign is temporarily unavailable.');return data?campaign(data):undefined;}
 async saveCampaign(input:Omit<Campaign,'updatedAt'>){const mutable={name:input.name.trim(),description:input.description.trim()||null,subject:input.subject.trim(),preview_text:input.previewText.trim(),sender_name:input.senderName.trim(),reply_to:input.replyTo.trim(),audience_type:input.audienceType,audience_public_id:input.audienceId||null,content_version:1,content:input.content,status:input.status};const q=input.id?this.db.from('marketing_campaigns').update(mutable).eq('organization_id',this.ctx.organization.id).eq('public_id',input.id):this.db.from('marketing_campaigns').insert({...mutable,organization_id:this.ctx.organization.id,created_by_membership_id:this.ctx.membership.id});const{data,error}=await q.select().single();if(error)throw new Error('Campaign could not be saved.');return campaign(data);}
 async duplicateCampaign(id:string){const x=await this.getCampaign(id);if(!x)throw new Error('Campaign not found.');return this.saveCampaign({...x,id:'',name:`${x.name} copy`,status:'draft'});}
 async previewAudience(type:'segment'|'list',id:string){const{data,error}=await this.db.rpc('resolve_campaign_audience',{source_kind:type,source_id:id,page_limit:25,page_offset:0});if(error)throw new Error('Campaign audience could not be resolved.');const r=data??[],n=r[0];return{contacts:r.map(x=>({id:x.contact_public_id,displayName:x.display_name,email:x.primary_email??'',emailStatus:x.email_status})),matching:Number(n?.matching_count??0),eligible:Number(n?.eligible_count??0),unknown:Number(n?.unknown_count??0),optedOut:Number(n?.opted_out_count??0),suppressed:Number(n?.suppressed_count??0),missingEmail:Number(n?.missing_email_count??0)};}}
function segment(x:Database['public']['Tables']['contact_segments']['Row']):Segment{return{id:x.public_id,name:x.name,description:x.description??'',criteria:asCriteria(x.criteria),updatedAt:x.updated_at}}function campaign(x:Database['public']['Tables']['marketing_campaigns']['Row']):Campaign{return{id:x.public_id,name:x.name,description:x.description??'',subject:x.subject,previewText:x.preview_text,senderName:x.sender_name,replyTo:x.reply_to,audienceType:x.audience_type,audienceId:x.audience_public_id??'',content:contentSchema.parse(x.content),status:x.status,updatedAt:x.updated_at}}
