import type { ContactImportMapping, ContactImportPreview, ContactInput, ImportableContactField } from "../models/Contact";

export const MAX_CSV_BYTES=5*1024*1024;export const MAX_IMPORT_ROWS=5000;
const aliases:Record<ImportableContactField,string[]>={firstName:["first name","firstname","first"],lastName:["last name","lastname","last","surname"],preferredName:["preferred name","display name","nickname"],primaryEmail:["email","email address","primary email"],primaryPhone:["phone","phone number","mobile"],addressLine1:["address","street","address 1"],city:["city"],stateProvince:["state","province","state province"],postalCode:["zip","zipcode","postal code"],country:["country"],company:["company","organization"],titleOccupation:["title","occupation","job title"],source:["source","lead source"]};
const normalize=(v:string)=>v.trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");
export function suggestMappings(headers:string[]):ContactImportMapping{const result:ContactImportMapping={};for(const field of Object.keys(aliases) as ImportableContactField[]){const found=headers.find(h=>aliases[field].includes(normalize(h)));if(found)result[field]=found;}return result;}
export function parseCsv(text:string):{headers:string[];rows:Record<string,string>[]}{
  const matrix:string[][]=[];let row:string[]=[],cell="",quoted=false;
  for(let i=0;i<text.length;i++){const c=text[i]!;if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===","&&!quoted){row.push(cell);cell="";}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(x=>x.trim()))matrix.push(row);row=[];cell="";}else cell+=c;}
  row.push(cell);if(row.some(x=>x.trim()))matrix.push(row);const headers=(matrix.shift()??[]).map(x=>x.trim());if(!headers.length||new Set(headers).size!==headers.length)throw new Error("CSV headers must be present and unique.");
  return {headers,rows:matrix.slice(0,MAX_IMPORT_ROWS+1).map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]?.trim()??""])))};
}
export function previewImport(headers:string[],rows:Record<string,string>[],mapping:ContactImportMapping):ContactImportPreview{const warnings:string[]=[];if(!mapping.firstName)warnings.push("Map a first-name column.");if(!mapping.lastName)warnings.push("Map a last-name column.");if(rows.length>MAX_IMPORT_ROWS)warnings.push(`Imports are limited to ${MAX_IMPORT_ROWS.toLocaleString()} rows.`);let valid=0;for(const r of rows.slice(0,MAX_IMPORT_ROWS)){if(value(r,mapping.firstName)&&value(r,mapping.lastName))valid++;}return {rows:rows.slice(0,MAX_IMPORT_ROWS).map((values,i)=>({rowNumber:i+2,values})),valid,invalid:Math.min(rows.length,MAX_IMPORT_ROWS)-valid,warnings};}
export function mappedInput(row:Record<string,string>,mapping:ContactImportMapping,defaultSource="CSV Import"):ContactInput|null{const firstName=value(row,mapping.firstName),lastName=value(row,mapping.lastName);if(!firstName||!lastName)return null;const country=value(row,mapping.country).toUpperCase();return {firstName,lastName,preferredName:value(row,mapping.preferredName),primaryEmail:value(row,mapping.primaryEmail),primaryPhone:value(row,mapping.primaryPhone),addressLine1:value(row,mapping.addressLine1),addressLine2:"",city:value(row,mapping.city),stateProvince:value(row,mapping.stateProvince),postalCode:value(row,mapping.postalCode),country:country==="CA"?"CA":"US",company:value(row,mapping.company),titleOccupation:value(row,mapping.titleOccupation),source:value(row,mapping.source)||defaultSource,lifecycleStatus:"prospect"};}
const value=(row:Record<string,string>,header?:string)=>header?row[header]?.trim()??"":"";
