"use client";
import dynamic from "next/dynamic";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { Campaign, CampaignContent, MarketingOptions } from "../models/Marketing";
import { createVisualCopyAction, duplicateCampaignAction } from "../actions/marketing-actions";
import { LegacyCampaignEditor } from "./LegacyCampaignEditor";

const Studio = dynamic(() => import("../studio/MarketingStudio"), { ssr: false, loading: () => <p className="p-8">Opening Marketing Studio…</p> });
export function CampaignEditor({ campaign, options, initialAudience }: { campaign?: Campaign; options: MarketingOptions; initialAudience?: { type: "segment" | "list"; id: string } }) {
  const [classic, setClassic] = useState(false), [error, setError] = useState("");
  const [pending, start] = useTransition(), router = useRouter();
  const copy = (visual: boolean) => start(async () => { try { const id = await (visual ? createVisualCopyAction(campaign!.id) : duplicateCampaignAction(campaign!.id)); router.push(`/crm/campaigns/${id}`); } catch (e) { setError(e instanceof Error ? e.message : "Copy unavailable."); } });
  if (campaign?.content.version === -1) return <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">This document needs a compatible editor</h2><p className="mt-2">Its original content has been preserved. This campaign is read-only; no content was removed.</p><details className="mt-4"><summary>View original document for recovery</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(campaign.content.original, null, 2)}</pre></details></section>;
  if (campaign && ["sent", "sending"].includes(campaign.status)) return <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Campaign history · Read-only</h2><p className="mt-2 text-sm text-slate-600">Sent and sending content cannot be edited. Create a new draft to reuse this message.</p><button disabled={pending} onClick={() => copy(false)} className="mt-4 rounded-xl border px-4 py-2 font-bold">Duplicate as draft</button>{error && <p role="alert">{error}</p>}{campaign.content.version === 1 && <div className="mt-6 whitespace-pre-wrap"><h3 className="text-2xl font-bold">{campaign.content.heading}</h3><p className="mt-4">{campaign.content.body}</p><p className="mt-4">{campaign.content.ctaLabel} {campaign.content.ctaUrl}</p><p className="mt-6 text-sm">{campaign.content.footer}</p></div>}</section>;
  if (campaign?.content.version === 1 || classic) return <div className="space-y-4">{campaign && <section className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-teal-200 bg-teal-50 p-5"><div><h2 className="font-black">Classic text campaign</h2><p className="text-sm">Keep this original or create a separate visual-editor draft.</p></div><button disabled={pending} onClick={() => copy(true)} className="rounded-xl bg-teal-800 px-4 py-3 font-bold text-white">Create visual-editor copy</button>{error && <p role="alert">{error}</p>}</section>}<LegacyCampaignEditor key={campaign?.updatedAt} campaign={campaign as (Campaign & { content: CampaignContent }) | undefined} options={options} initialAudience={initialAudience} /></div>;
  return <><Studio key={campaign?.updatedAt ?? "new"} campaign={campaign} options={options} initialAudience={initialAudience} />{!campaign && <button className="mt-5 text-sm text-slate-500 underline" onClick={() => { if(window.confirm("Open a classic campaign? Any unsaved visual content will be discarded.")) setClassic(true); }}>Classic text campaign</button>}</>;
}
