"use client";

import Link from "next/link";
import { useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2, Play, SkipForward, Square } from "lucide-react";
import type { DiscoveryExperienceState, DiscoveryObjectiveState, DiscoveryQuestionState, DiscoveryWorkflowPhase } from "../models/DiscoveryExperienceState";
import { CandidateLifecycleAction } from "@/feature/crm/components/CandidateLifecycleAction";

const statusLabel: Record<DiscoveryObjectiveState["status"], string> = { validated: "Validated", partial: "Partial", "needs-validation": "Needs Validation", unknown: "Unknown" };
const statusClass: Record<DiscoveryObjectiveState["status"], string> = { validated: "bg-teal-50 text-teal-700", partial: "bg-blue-50 text-blue-700", "needs-validation": "bg-amber-50 text-amber-700", unknown: "bg-slate-100 text-slate-600" };

export function DiscoveryExperiencePage({ state }: { state: DiscoveryExperienceState }) {
  const [phase, setPhase] = useState<DiscoveryWorkflowPhase>(state.phase);
  const [questions, setQuestions] = useState<DiscoveryQuestionState[]>([state.primaryQuestion, ...state.secondaryQuestions]);
  const [skipped, setSkipped] = useState<DiscoveryQuestionState[]>([]);
  const [asked, setAsked] = useState<string[]>([]);
  const primary = questions[0];
  const secondary = [...questions.slice(1), ...skipped];
  const validated = state.objectives.filter((item) => item.status === "validated").length;
  const progressQuestion = (action: "asked" | "skipped") => {
    if (!primary) return;
    if (action === "asked") setAsked((current) => [...current, primary.id]);
    else setSkipped((current) => [...current, primary]);
    setQuestions((current) => current.slice(1));
  };

  return <main className="mx-auto max-w-7xl space-y-6 p-6 lg:p-10">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 pb-5">
      <div><Link href={`/crm/candidates/${state.candidate.id}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-900"><ArrowLeft size={16} />{state.candidate.name} Candidate 360</Link><p className="mt-4 text-xs font-black uppercase tracking-[0.22em] text-teal-600">Discovery Copilot · {phase.replace("-", " ")}</p><h1 className="mt-1 text-3xl font-black text-slate-950">{state.candidate.name}</h1></div>
      <div className="flex gap-3"><Metric label="Candidate Readiness" value={`${state.candidate.readiness}%`} /><Metric label="Buying Confidence" value={`${state.candidate.buyingConfidence}%`} /></div>
    </header>
    {phase === "pre-meeting" && <PreMeeting state={state} onStart={() => setPhase("live")} />}
    {phase === "live" && <LiveMeeting state={state} primary={primary} secondary={secondary} asked={asked.length} validated={validated} onAsked={() => progressQuestion("asked")} onSkip={() => progressQuestion("skipped")} onEnd={() => setPhase("post-meeting")} />}
    {phase === "post-meeting" && <PostMeeting state={state} asked={asked.length} />}
  </main>;
}

function PreMeeting({ state, onStart }: { state: DiscoveryExperienceState; onStart: () => void }) {
  return <div className="grid gap-6 lg:grid-cols-[1.15fr_0.85fr]"><section className="space-y-6"><Panel title="60-second candidate brief"><p className="text-base leading-7 text-slate-700">{state.summary}</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><Small label="Lifecycle" value={state.candidate.stageLabel} /><Small label="Momentum" value={state.candidate.momentum} /><Small label="Investment context" value={state.candidate.financialContext} /></div></Panel><Objectives objectives={state.objectives} /><Panel title="Recent relationship activity"><div className="space-y-3">{state.recentActivity.map((item) => <div key={`${item.title}-${item.occurredAt}`} className="border-l-2 border-slate-200 pl-4"><p className="text-sm font-black text-slate-800">{item.title}</p><p className="text-xs text-slate-500">{item.detail}</p></div>)}</div></Panel></section><aside className="space-y-6"><Panel title="Known strengths"><List items={state.strengths} tone="positive" /></Panel><Panel title="Risks and evidence gaps"><List items={state.objectives.filter((item) => item.status !== "validated").map((item) => `${item.label}: ${item.evidenceSummary}`)} tone="risk" /></Panel><Panel title="Suggested opening"><p className="text-lg font-black leading-7 text-slate-900">“{state.primaryQuestion.question}”</p><p className="mt-3 text-sm leading-6 text-slate-600">{state.primaryQuestion.reason}</p></Panel>{state.candidate.stage === "assessment-completed" ? <CandidateLifecycleAction candidateId={state.candidate.id} label="Start Discovery" /> : <button type="button" onClick={onStart} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-black text-white hover:bg-blue-700 focus:outline-none focus:ring-4 focus:ring-blue-200"><Play size={17} />Start Discovery</button>}</aside></div>;
}

function LiveMeeting({ state, primary, secondary, asked, validated, onAsked, onSkip, onEnd }: { state: DiscoveryExperienceState; primary?: DiscoveryQuestionState; secondary: DiscoveryQuestionState[]; asked: number; validated: number; onAsked: () => void; onSkip: () => void; onEnd: () => void }) {
  return <div className="grid gap-6 xl:grid-cols-[1.7fr_0.9fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-blue-600">Demo meeting workspace</p><h2 className="mt-1 text-xl font-black">Meeting notes</h2></div><button type="button" onClick={onEnd} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white focus:outline-none focus:ring-4 focus:ring-slate-200"><Square size={14} />End Discovery</button></div><p className="mt-3 text-xs text-slate-500">Deterministic conference notes—no microphone or external transcription is connected.</p><textarea aria-label="Consultant meeting notes" defaultValue={state.notes} className="mt-5 min-h-[480px] w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-5 leading-7 outline-none focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-100" /></section><aside className="space-y-4"><Panel title="Objective progress"><p className="text-2xl font-black text-slate-950">{validated} of {state.objectives.length}</p><p className="text-sm text-slate-500">objectives sufficiently validated</p><div className="mt-4 space-y-2">{state.objectives.map((item) => <div key={item.id} className="flex items-center justify-between gap-2 text-sm"><span className="font-semibold">{item.label}</span><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${statusClass[item.status]}`}>{statusLabel[item.status]}</span></div>)}</div></Panel>{primary ? <Panel title="Next Best Question"><p className="text-lg font-black leading-7">“{primary.question}”</p><p className="mt-3 text-sm leading-6 text-slate-600"><strong>Why this matters:</strong> {primary.reason}</p><div className="mt-4 flex gap-2"><button aria-label="Mark next best question asked" type="button" onClick={onAsked} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-black text-white"><CheckCircle2 size={15} />Asked</button><button aria-label="Skip next best question" type="button" onClick={onSkip} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-black"><SkipForward size={15} />Skip</button></div></Panel> : <Panel title="Next Best Question"><p className="text-sm text-slate-600">All suggested questions have been addressed or deferred.</p></Panel>}<details className="rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-black">Other Suggested Questions ({secondary.length})</summary><ul className="mt-3 space-y-2">{secondary.map((item) => <li key={item.id} className="text-sm leading-6 text-slate-600">{item.question}</li>)}</ul></details><Signals state={state} /><p className="text-xs text-slate-400">{asked} question{asked === 1 ? "" : "s"} marked asked. Asking alone does not validate evidence.</p></aside></div>;
}

function PostMeeting({ state, asked }: { state: DiscoveryExperienceState; asked: number }) {
  const validated = state.objectives.filter((item) => item.status === "validated");
  return <div className="space-y-6"><section className="rounded-2xl border border-blue-100 bg-blue-50/60 p-6"><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">Post-Meeting Intelligence</p><h2 className="mt-2 text-2xl font-black">Executive Summary</h2><p className="mt-3 max-w-4xl leading-7 text-slate-700">{state.summary}</p></section><div className="grid gap-6 lg:grid-cols-2"><Panel title="What Changed">{state.changes.length ? state.changes.map((item) => <p key={item.label} className="text-sm"><strong>{item.label}</strong>: {item.before} → {item.after}</p>) : <p className="text-sm text-slate-600">{asked ? `${asked} question${asked === 1 ? " was" : "s were"} addressed; no new answer evidence was recorded, so Candidate Intelligence was not changed.` : "No material Candidate Intelligence changes recorded."}</p>}</Panel><Panel title="Validated Strengths"><List items={[...state.strengths, ...validated.map((item) => item.evidenceSummary)].slice(0, 5)} tone="positive" /></Panel><Panel title="Remaining Risks / Open Questions"><List items={state.objectives.filter((item) => item.status !== "validated").map((item) => `${item.label}: ${item.evidenceSummary}`)} tone="risk" /></Panel><Panel title="Evidence and Objective Status"><Objectives objectives={state.objectives} compact /></Panel><Panel title="Buying Signals"><List items={state.buyingSignals.map((item) => `${item.label} — ${item.reason} (${item.confidence}% confidence)`)} tone="positive" /></Panel><Panel title="Consultant Notes"><p className="text-sm leading-7 text-slate-600">{state.notes}</p></Panel></div><section aria-label="Discovery recommendation" className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-xs font-black uppercase tracking-[0.2em] text-teal-300">Recommended Next Step</p><h2 className="mt-2 text-2xl font-black">{state.completion.heading}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">{state.completion.explanation}</p>{!state.historical && <div className="mt-5 w-fit"><CandidateLifecycleAction candidateId={state.candidate.id} label={state.completion.actionLabel} /></div>}{state.historical && <Link href={`/crm/candidates/${state.candidate.id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-black text-blue-300">Return to Candidate 360<ArrowRight size={15} /></Link>}</section></div>;
}

function Signals({ state }: { state: DiscoveryExperienceState }) { return <Panel title="Live signals and risks"><div className="space-y-3">{state.buyingSignals.slice(0, 2).map((item) => <div key={item.label} className="rounded-xl bg-teal-50 p-3"><p className="text-sm font-black text-teal-800">{item.label}</p><p className="text-xs text-teal-700">{item.reason} · {item.confidence}% confidence</p></div>)}{state.risks.slice(0, 2).map((item) => <div key={item.label} className={`rounded-xl p-3 ${item.severity === "critical" ? "bg-red-50" : "bg-amber-50"}`}><p className="text-sm font-black text-slate-800">{item.label}</p><p className="text-xs text-slate-600">{item.reason} · {item.confidence}% confidence</p></div>)}</div></Panel>; }
function Objectives({ objectives, compact = false }: { objectives: DiscoveryObjectiveState[]; compact?: boolean }) { return <Panel title={compact ? "Objectives" : "Discovery evidence requirements"}><div className="space-y-3">{objectives.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{item.label}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${statusClass[item.status]}`}>{statusLabel[item.status]}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{item.evidenceSummary}</p><p className="mt-2 text-[10px] font-bold uppercase text-slate-400">{item.priority} priority · {item.sources.join(", ")}</p></article>)}</div></Panel>; }
function Panel({ title, children }: React.PropsWithChildren<{ title: string }>) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black text-slate-950">{title}</h2><div className="mt-4">{children}</div></section>; }
function List({ items, tone }: { items: string[]; tone: "positive" | "risk" }) { return items.length ? <ul className="space-y-2">{items.map((item) => <li key={item} className="flex gap-2 text-sm leading-6 text-slate-700">{tone === "positive" ? <CheckCircle2 size={15} className="mt-1 shrink-0 text-teal-600" /> : <AlertTriangle size={15} className="mt-1 shrink-0 text-amber-600" />}{item}</li>)}</ul> : <p className="text-sm text-slate-500">No items recorded.</p>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white px-4 py-3"><p className="text-[10px] font-black uppercase text-slate-400">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div>; }
function Small({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase text-slate-400">{label}</p><p className="mt-1 text-sm font-bold capitalize">{value}</p></div>; }
