import { notFound } from "next/navigation";
import { resolveWorkspaceComposition } from "@/feature/platform/composition/resolveWorkspaceComposition";
import { ClearConferenceAssessmentsButton } from "@/feature/assessment-engine/conference/components/ClearConferenceAssessmentsButton";
import type { ConferenceAnalysis, SynthesisStatement } from "@/feature/assessment-engine/conference/types";

const priorityLabel = (priority: "high" | "normal") => priority === "high" ? "Key Priority" : "Priority";

export default async function ConferenceCandidatePage({params}:{params:Promise<{candidateId:string}>}) {
  const {candidateId}=await params;
  const resolution=await resolveWorkspaceComposition();if(resolution.status!=="resolved" || !("runtimes" in resolution.composition))notFound();
  const loaded=resolution.composition.dependencies.conferenceAssessments.loadByCandidateId(candidateId);
  if(!loaded)notFound();
  if(!loaded.ok)return <RecoveryState reason={loaded.reason}/>;
  const record=loaded.record;
  const {analysis,intake,answers}=record;
  const brief=analysis.consultantBrief;
  return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
    <header className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-amber-700">Temporary conference candidate · Assessment complete</p><h1 className="mt-1 text-3xl font-semibold">{intake.preferredName||intake.firstName} {intake.lastName}</h1><p className="mt-2 text-sm text-slate-600">{intake.email} · {intake.mobilePhone} · {intake.city}, {intake.stateProvince}</p><p className="mt-1 text-sm text-slate-500">{intake.occupationTitle}{intake.currentEmployer?` at ${intake.currentEmployer}`:""}</p><a href={`/crm/candidates/conference/${candidateId}/report`} className="mt-4 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Download Consultant Report (PDF)</a></div><ClearConferenceAssessmentsButton/></div></header>
    <section aria-labelledby="consultant-brief-heading" className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="grid lg:grid-cols-[0.8fr_1.2fr]"><div className="bg-slate-950 p-6 text-white"><p className="text-sm font-semibold text-blue-300">Ownership Profile · {analysis.ownershipProfile.confidenceState}</p><h2 className="mt-2 text-3xl font-semibold">{analysis.ownershipProfile.primary}</h2><p className="mt-4 text-sm leading-6 text-slate-300">{brief.ownershipOrientation.text}</p><div className="mt-6 rounded-xl bg-blue-600 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-blue-100">Start Discovery Here</p><p className="mt-2 font-medium leading-6">{brief.startDiscoveryHere.text}</p></div></div><div className="p-6"><p className="text-xs font-semibold uppercase tracking-wider text-blue-700">30-second preparation</p><h2 id="consultant-brief-heading" className="mt-1 text-2xl font-semibold">Consultant Brief</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><BriefArea title="What Stands Out" items={brief.whatStandsOut}/><BriefArea title="Validate During Discovery" items={brief.validateDuringDiscovery}/><BriefArea title="Decision Dynamics" items={[brief.decisionDynamics]}/><BriefArea title="Financial Context" items={[brief.financialContext]}/></div></div></div></section>
    <div className="grid gap-6 lg:grid-cols-2"><Panel title="Motivation & Goals" values={analysis.ownershipProfile.motivations}/><Panel title="Preferred Owner Role & Growth" values={[answers.q5?.[0]??"Explore during Discovery",answers.q18?.[0]??""]}/><Panel title="Business Development" values={[`Capability evidence: ${answers.q13?.[0]}`,`Launch-stage appetite: ${answers.q14?.[0]}`,`Preferred approach: ${(answers.q15??[]).join(", ")}`,`Mature-stage preference: ${answers.q30?.[0]}`]}/><Panel title="Leadership & Staffing" values={[answers.q7?.[0]??"",answers.q8?.[0]??"",answers.q27?.[0]??"",...(answers.q28??[])]}/><Panel title="Operations & Franchise-System Alignment" values={[answers.q11?.[0]??"",answers.q12?.[0]??""]}/><Panel title="Decision & Risk Profile" values={[answers.q19?.[0]??"",answers.q21?.[0]??"",answers.q24?.[0]??""]}/><Panel title="Lifestyle & Operating Preferences" values={[...(answers.q26??[]),...(answers.q29??[])]}/><Panel title="Decision Ecosystem" values={answers["q36-stakeholders"]??[]}/></div>
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Financial Readiness</h2><dl className="mt-4 grid gap-4 sm:grid-cols-3"><Metric label="Candidate-reported net worth" value={analysis.financial.netWorth}/><Metric label="Candidate-reported liquid capital" value={analysis.financial.liquidCapital}/><Metric label="Stated investment range" value={analysis.financial.investmentRange}/></dl><p className="mt-4 text-xs text-slate-500">{analysis.financial.disclaimer}</p></section>
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Primary Concern</h2><p className="mt-2 text-slate-600">{answers["primary-concern"]?.[0]??answers.concerns?.[0]??"No major concern reported"}</p></section>
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Potential Tensions</h2><p className="mt-1 text-sm text-slate-500">Priority reflects Discovery importance, not a candidate defect.</p><div className="mt-4 space-y-4">{analysis.tensions.length?analysis.tensions.map((item)=><div key={item.title} className="rounded-xl bg-amber-50 p-4"><p className="font-semibold">{item.title} · {priorityLabel(item.priority)}</p><p className="mt-1 text-sm text-slate-600">{item.explanation}</p><EvidenceTopics refs={item.evidenceRefs} analysis={analysis}/></div>):<p className="text-slate-500">No strong tensions surfaced. Continue validating during Discovery.</p>}</div></section>
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Discovery Priorities</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{analysis.discoveryPriorities.map((item)=><article key={item.title} className="rounded-xl border p-4"><p className="font-semibold">{item.title} · {priorityLabel(item.priority)}</p><p className="mt-2 text-sm text-slate-600">{item.whyItMatters}</p><p className="mt-3 text-sm font-medium">Ask: {item.suggestedQuestion}</p><EvidenceTopics refs={item.evidenceRefs} analysis={analysis}/></article>)}</div></section>
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Franchise Model Implications</h2><p className="mt-1 text-sm text-slate-500">Opportunity Characteristics Profile for later Brand Strategy use. “Attractive” reflects expressed openness or a supported preference—not a brand recommendation. Brand recommendations begin after consultant Discovery.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{analysis.opportunityCharacteristics.map((item)=><div key={item.characteristic} className="rounded-lg bg-slate-50 p-4"><p className="font-semibold capitalize">{item.characteristic} · {item.disposition}</p><p className="mt-1 text-sm text-slate-600">{item.reason}</p></div>)}</div></section>
    <details className="rounded-2xl border bg-white"><summary className="cursor-pointer p-6 text-xl font-semibold">Supporting Evidence</summary>{analysis.evidenceDetails.length?<div className="grid gap-3 px-6 pb-6 sm:grid-cols-2">{analysis.evidenceDetails.map((item)=><div key={`${item.questionId}-${item.topic}`} className="rounded-lg bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{item.topic}</p><p className="mt-1 text-sm font-medium text-slate-800">{item.response}</p><p className="mt-1 text-xs text-slate-500">{item.interpretation}</p></div>)}</div>:<p className="px-6 pb-6 text-sm text-slate-500">No supporting assessment evidence is available.</p>}</details>
    <section className="rounded-2xl border border-dashed bg-white p-6"><h2 className="text-xl font-semibold">Not yet started</h2><p className="mt-2 text-slate-600">Communications, meetings, referrals, presentations, Gmail activity, and downstream history have not been created for this candidate.</p></section>
  </main>;
}

function BriefArea({title,items}:{title:string;items:SynthesisStatement[]}){return <section><h3 className="text-sm font-semibold text-slate-950">{title}</h3><ul className="mt-2 list-disc space-y-2 pl-4 text-sm leading-5 text-slate-600">{items.map((item)=><li key={item.text}>{item.text}</li>)}</ul></section>}
function Panel({title,values}:{title:string;values:string[]}){return <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">{title}</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-600">{values.filter(Boolean).map((value,index)=><li key={`${value}-${index}`}>{value}</li>)}</ul></section>}
function Metric({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>}
function EvidenceTopics({refs,analysis}:{refs:string[];analysis:ConferenceAnalysis}){const topics=[...new Set(refs.map(ref=>analysis.evidenceDetails.find(item=>item.questionId===ref)?.topic).filter((topic):topic is string=>Boolean(topic)))];return topics.length?<p className="mt-2 text-xs text-slate-500">Supporting evidence: {topics.join(" · ")}</p>:null}
function RecoveryState({reason}:{reason:string}){return <main className="mx-auto max-w-3xl p-6"><section className="rounded-2xl border bg-white p-8"><p className="text-sm font-semibold text-amber-700">Assessment intelligence unavailable</p><h1 className="mt-2 text-3xl font-semibold">This assessment could not be safely regenerated</h1><p className="mt-4 text-slate-600">{reason}</p><p className="mt-3 text-sm text-slate-500">The original assessment record remains intact. No responses or intelligence were fabricated.</p></section></main>}
