import { notFound } from "next/navigation";
import { conferenceAssessmentStore } from "@/feature/assessment-engine/conference/ConferenceAssessmentStore";
import { ClearConferenceAssessmentsButton } from "@/feature/assessment-engine/conference/components/ClearConferenceAssessmentsButton";

export default async function ConferenceCandidatePage({params}:{params:Promise<{candidateId:string}>}) { const {candidateId}=await params;const record=conferenceAssessmentStore.getByCandidateId(candidateId);if(!record)notFound();const {analysis,intake,answers}=record;
 return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-8"><header className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-amber-700">Temporary conference candidate · Assessment complete</p><h1 className="mt-1 text-3xl font-semibold">{intake.preferredName||intake.firstName} {intake.lastName}</h1><p className="mt-2 text-sm text-slate-600">{intake.email} · {intake.mobilePhone} · {intake.city}, {intake.stateProvince}</p><p className="mt-1 text-sm text-slate-500">{intake.occupationTitle}{intake.currentEmployer?` at ${intake.currentEmployer}`:""}</p></div><ClearConferenceAssessmentsButton/></div></header>
 <section className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-sm text-blue-300">Ownership Profile</p><h2 className="mt-2 text-3xl font-semibold">{analysis.ownershipProfile.primary}</h2><p className="mt-3 text-slate-300">{analysis.executiveSummary}</p></section>
 <div className="grid gap-6 lg:grid-cols-2"><Panel title="Motivation & Goals" values={analysis.ownershipProfile.motivations}/><Panel title="Preferred Owner Role" values={[answers.q5?.[0]??"Explore during Discovery",answers.q18?.[0]??""]}/><Panel title="Business Development" values={[`Capability evidence: ${answers.q13?.[0]}`,`Appetite: ${answers.q14?.[0]}`,`Style: ${(answers.q15??[]).join(", ")}`,`Mature preference: ${answers.q30?.[0]}`]}/><Panel title="Leadership & Staffing" values={[answers.q7?.[0]??"",answers.q8?.[0]??"",answers.q27?.[0]??"",...(answers.q28??[])]}/><Panel title="Operations & Franchise-System Alignment" values={[answers.q11?.[0]??"",answers.q12?.[0]??""]}/><Panel title="Decision & Risk Profile" values={[answers.q19?.[0]??"",answers.q21?.[0]??"",answers.q24?.[0]??""]}/><Panel title="Lifestyle & Operating Preferences" values={[...(answers.q26??[]),...(answers.q29??[])]}/><Panel title="Decision Ecosystem" values={answers["q36-stakeholders"]??[]}/></div>
 <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Financial Readiness</h2><dl className="mt-4 grid gap-4 sm:grid-cols-3"><Metric label="Candidate-reported net worth" value={analysis.financial.netWorth}/><Metric label="Candidate-reported liquid capital" value={analysis.financial.liquidCapital}/><Metric label="Stated investment range" value={analysis.financial.investmentRange}/></dl><p className="mt-4 text-xs text-slate-500">{analysis.financial.disclaimer}</p></section>
 <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Primary Concern</h2><p className="mt-2 text-slate-600">{answers["primary-concern"]?.[0]??answers.concerns?.[0]??"No major concern reported"}</p></section>
 <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Potential Tensions</h2><p className="mt-1 text-sm text-slate-500">Severity reflects Discovery importance, not a candidate defect.</p><div className="mt-4 space-y-4">{analysis.tensions.length?analysis.tensions.map((item)=><div key={item.title} className="rounded-xl bg-amber-50 p-4"><p className="font-semibold">{item.title} · {item.priority}</p><p className="mt-1 text-sm text-slate-600">{item.explanation}</p><p className="mt-2 text-xs text-slate-500">Evidence: {item.evidenceRefs.join(", ")}</p></div>):<p className="text-slate-500">No strong tensions surfaced. Continue validating during Discovery.</p>}</div></section>
 <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Discovery Priorities</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{analysis.discoveryPriorities.map((item)=><article key={item.title} className="rounded-xl border p-4"><p className="font-semibold">{item.title} · {item.priority}</p><p className="mt-2 text-sm text-slate-600">{item.whyItMatters}</p><p className="mt-3 text-sm font-medium">Ask: {item.suggestedQuestion}</p></article>)}</div></section>
 <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Franchise Model Implications</h2><p className="mt-1 text-sm text-slate-500">Opportunity Characteristics Profile for later Brand Strategy use. Brand recommendations begin after consultant Discovery.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{analysis.opportunityCharacteristics.map((item)=><div key={item.characteristic} className="rounded-lg bg-slate-50 p-4"><p className="font-semibold capitalize">{item.characteristic} · {item.disposition}</p><p className="mt-1 text-sm text-slate-600">{item.reason}</p></div>)}</div></section>
 <section className="rounded-2xl border border-dashed bg-white p-6"><h2 className="text-xl font-semibold">Not yet started</h2><p className="mt-2 text-slate-600">Communications, meetings, referrals, presentations, Gmail activity, and downstream history have not been created for this candidate.</p></section></main> }
function Panel({title,values}:{title:string;values:string[]}){return <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">{title}</h2><ul className="mt-3 space-y-2 text-sm text-slate-600">{values.filter(Boolean).map((v,i)=><li key={`${v}-${i}`}>• {v}</li>)}</ul></section>}
function Metric({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>}
