'use client';
import {useEffect,useRef,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {reviewStudioSendResultAction,confirmStudioSendResultAction,sendStudioTestAction} from '../actions/marketing-actions';
import type {FinalAudienceReview} from './MarketingDelivery';

export default function StudioDeliveryPanel({campaignId,revision,dirty}:{campaignId:string;revision:string;dirty:boolean}) {
 const [pending,start]=useTransition(),[review,setReview]=useState<FinalAudienceReview>(),[recipient,setRecipient]=useState(''),[activePanel,setActivePanel]=useState<'test'|'review'|null>(null),[message,setMessage]=useState(''),[error,setError]=useState('');
 const key=useRef(crypto.randomUUID()+crypto.randomUUID()),testKey=useRef(crypto.randomUUID()+crypto.randomUUID()),router=useRouter();
 const testTrigger=useRef<HTMLButtonElement>(null),reviewTrigger=useRef<HTMLButtonElement>(null);
 const testClose=useRef<HTMLButtonElement>(null),reviewClose=useRef<HTMLButtonElement>(null);
 const visiblePanel=activePanel==='review' ? (review&&!dirty?'review':null) : activePanel;
 useEffect(()=>{if(pending)return;if(visiblePanel==='test')testClose.current?.focus();else if(visiblePanel==='review')reviewClose.current?.focus();},[visiblePanel,pending]);
 const closePanel=(panel:'test'|'review')=>{setActivePanel(null);(panel==='test'?testTrigger:reviewTrigger).current?.focus();};
 const reviewAudience=()=>{setActivePanel('review');start(async()=>{setError('');setMessage('');const r=await reviewStudioSendResultAction(campaignId);if(r.ok)setReview(r.review);else setError(r.error);});};
 const confirm=()=>start(async()=>{if(!review?.reviewToken)return;setError('');const r=await confirmStudioSendResultAction(campaignId,key.current,review.reviewToken);if(r.ok){setReview(undefined);router.refresh();}else{setError(r.error);setReview(undefined);}});
 const test=()=>start(async()=>{setError('');setMessage('');const r=await sendStudioTestAction({id:campaignId,revision,recipient,key:testKey.current});if(r.ok){setMessage(r.result.status==='accepted'?'Test email accepted by the provider. This does not launch the campaign.':r.result.status==='failed'?'Test email failed. No campaign was launched.':'This test is already being processed.');setActivePanel(null);}else setError(r.error);});
 return <section aria-label="Visual campaign delivery" className="space-y-4 rounded-2xl border bg-white p-4 sm:p-6"><h3 className="text-xl font-black">Send your campaign</h3><p className="text-sm text-slate-600">Save your changes, then send a test or review the audience before sending immediately.</p>{dirty&&<p className="text-sm font-bold text-amber-800">Save Draft before testing or reviewing delivery.</p>}<div className="flex flex-wrap gap-3"><button ref={testTrigger} aria-expanded={visiblePanel==='test'} aria-controls="studio-test-panel" disabled={dirty||pending} onClick={()=>{if(activePanel==='test')closePanel('test');else{setActivePanel('test');setReview(undefined);}}} className="rounded-xl border px-4 py-3 font-bold disabled:opacity-50">Send Test Email</button><button ref={reviewTrigger} aria-expanded={visiblePanel==='review'} aria-controls="studio-review-panel" disabled={dirty||pending} onClick={reviewAudience} className="rounded-xl bg-slate-950 px-4 py-3 font-bold text-white disabled:opacity-50">Review Audience</button></div>
 <div id="studio-test-panel" data-delivery-panel hidden={activePanel!=='test'} className="space-y-3 rounded-xl bg-sky-50 p-4"><div className="delivery-panel-heading"><p className="font-bold">Send one test email</p><button ref={testClose} type="button" disabled={pending} onClick={()=>closePanel('test')} aria-label="Close test email panel" className="rounded-lg border bg-white px-3 py-2">Close</button></div><p className="text-sm">Uses the saved campaign with sample personalization. The subject is marked TEST. Audience membership, campaign analytics and contact consent stay unchanged.</p><label className="grid gap-1 text-sm font-bold">Test recipient<input aria-label="Test recipient" type="email" value={recipient} onChange={e=>{setRecipient(e.target.value);testKey.current=crypto.randomUUID()+crypto.randomUUID();}} className="min-w-0 rounded-lg border p-3 font-normal"/></label><button disabled={pending||!recipient.trim()} onClick={test} className="rounded-lg bg-sky-800 px-4 py-3 font-bold text-white">Send this test email</button></div>
 {review&&!dirty&&<div id="studio-review-panel" data-delivery-panel hidden={activePanel!=='review'} className="space-y-3 rounded-xl bg-amber-50 p-4"><div className="delivery-panel-heading"><h4 className="font-black">Confirm campaign send</h4><button ref={reviewClose} type="button" disabled={pending} onClick={()=>closePanel('review')} aria-label="Close audience review panel" className="rounded-lg border bg-white px-3 py-2">Close</button></div><p>{review.campaignName}</p><p>Subject: {review.subject}</p><p>Sender: {review.senderName}</p><p className="break-words">Audience: {review.audienceLabel}</p><p><strong>{review.eligible} eligible recipients</strong> of {review.matching} matched contacts.</p><p>Compliance: {review.complianceReady?'Sender, company, postal address, media and unsubscribe are ready.':'Not ready.'}</p><p className="text-sm">This sends immediately. Confirmation freezes the message and recipients. Later edits cannot alter this send.</p><button disabled={pending||review.eligible<1||!review.complianceReady} onClick={confirm} className="rounded-lg bg-emerald-800 px-4 py-3 font-bold text-white">Confirm and send now</button><button disabled={pending} onClick={()=>{setReview(undefined);closePanel('review');}} className="ml-3 rounded-lg border px-4 py-3">Cancel</button></div>}
 {pending&&<p role="status">Preparing delivery...</p>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}</section>;
}
