import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { isAuthorizedCampaignDeliveryWorker } from "../../feature/marketing/delivery/worker-authorization.ts";
import { getCampaignDeliveryWorkerEnvironment } from "../../lib/env.ts";

const secret="worker-secret-that-is-at-least-thirty-two-characters";
test("worker authorization accepts only the dedicated bearer secret",()=>{assert.equal(isAuthorizedCampaignDeliveryWorker(new Request("https://app.test",{headers:{authorization:`Bearer ${secret}`}}),secret),true);assert.equal(isAuthorizedCampaignDeliveryWorker(new Request("https://app.test"),secret),false);assert.equal(isAuthorizedCampaignDeliveryWorker(new Request("https://app.test",{headers:{authorization:"Bearer wrong"}}),secret),false)});
test("worker configuration fails closed when absent or short",()=>{assert.equal(getCampaignDeliveryWorkerEnvironment({}),null);assert.equal(getCampaignDeliveryWorkerEnvironment({CAMPAIGN_DELIVERY_WORKER_SECRET:"short"}),null);assert.deepEqual(getCampaignDeliveryWorkerEnvironment({CAMPAIGN_DELIVERY_WORKER_SECRET:secret}),{CAMPAIGN_DELIVERY_WORKER_SECRET:secret})});
test("hosted worker is bounded, uses durable run input, admin persistence, and production provider only",async()=>{const route=await readFile(new URL("../../app/api/internal/campaign-delivery/route.ts",import.meta.url),"utf8");assert.match(route,/sendRunId/);assert.match(route,/processBatch\([\s\S]*APP_URL, 10\)/);assert.match(route,/createAdminSupabaseClient/);assert.match(route,/createProductionMarketingDeliveryProvider/);assert.doesNotMatch(route,/LocalMarketingDeliveryProvider|senderName|subject|recipient|email/)});
test("repository preserves logical recipient idempotency and consent-aware database claim",async()=>{const source=await readFile(new URL("../../feature/marketing/delivery/SupabaseMarketingDeliveryRepository.ts",import.meta.url),"utf8");assert.match(source,/deliveryKey:r\.public_id/);assert.match(source,/claim_campaign_recipients/);assert.match(source,/Math\.min\(Math\.max\(Math\.trunc\(batchSize\),1\),50\)/)});
test("lease migration documents provider acceptance boundary and uses atomic stale reclaim",async()=>{const sql=await readFile(new URL("../../supabase/migrations/20260903191230_durable_campaign_delivery_leases.sql",import.meta.url),"utf8");assert.match(sql,/after 15 minutes/i);assert.match(sql,/provider may accept/i);assert.match(sql,/status='processing' and r\.claimed_at < now\(\)-interval '15 minutes'/);assert.match(sql,/for update skip locked/i);assert.match(sql,/claim_token=claim_id/)});
