import assert from "node:assert/strict";
import test from "node:test";
import { ConferenceAssessmentAnalysisService } from "../../feature/assessment-engine/conference/ConferenceAssessmentAnalysisService.ts";
import { conferenceQuestions, concernExclusive } from "../../feature/assessment-engine/conference/questions.ts";
import { applyExclusiveSelection, validateConferenceSubmission } from "../../feature/assessment-engine/conference/validation.ts";
import { conferenceAssessmentPersonas, personaIntake } from "../fixtures/conference-assessment-personas.mjs";

const intake = { firstName:"Alex",lastName:"Morgan",email:"alex@example.com",mobilePhone:"555-0100",streetAddress:"1 Main St",city:"Orlando",stateProvince:"FL",postalCode:"32801",country:"United States",occupationTitle:"VP Operations",ownedBusinessBefore:"no",exploredFranchiseBefore:"yes",preferredContactMethod:"email",bestContactTime:"morning" };
function validAnswers() { const answers = {}; for (const q of conferenceQuestions) { if(q.kind !== "context" && !q.primaryOf) answers[q.id]=[q.options[0]]; } answers.q2=[answers.q1[0]];answers.q21=[answers.q20[0]];answers["q36-geography"]=["Need to remain near my current location"];answers["q36-stakeholders"]=["Decision is primarily mine"];answers["q36-stage"]=["Actively researching franchises"];answers.concerns=[concernExclusive];return answers; }
const analyze = (answers=validAnswers()) => new ConferenceAssessmentAnalysisService().analyze(intake,answers);

test("frozen assessment contains 36 questions in six sections",()=>{assert.equal(conferenceQuestions.length,36);assert.deepEqual([...new Set(conferenceQuestions.map(q=>q.section))],[1,2,3,4,5,6]);});
test("exclusive choice clears incompatible values and toggles ordinary values",()=>{assert.deepEqual(applyExclusiveSelection(["Build wealth"],"I'm still figuring that out",["I'm still figuring that out"]),["I'm still figuring that out"]);assert.deepEqual(applyExclusiveSelection(["I'm still figuring that out"],"Build wealth",["I'm still figuring that out"]),["Build wealth"]);});
test("validation requires consent, intake, all questions and context",()=>{const errors=validateConferenceSubmission({...intake,email:"bad"}, {}, false);assert.ok(errors.includes("Consent is required"));assert.ok(errors.includes("Enter a valid email address"));assert.ok(errors.includes("Missing q1"));assert.ok(errors.includes("Missing q36-stage"));});
test("valid complete response passes validation",()=>assert.deepEqual(validateConferenceSubmission(intake,validAnswers(),true),[]));
test("conditional primary response must come from parent selections",()=>{const a=validAnswers();a.q2=["not selected"];assert.ok(validateConferenceSubmission(intake,a,true).includes("q2 must use a prior selection"));});
test("evidence preserves capability preference motivation and constraint categories",()=>{const categories=new Set(analyze().evidence.map(e=>e.category));assert.deepEqual([...categories].sort(),["capability","constraint","motivation","preference"]);});
test("analysis is deterministic",()=>assert.deepEqual(analyze(),analyze()));
test("high sales capability and low appetite remain separate and create tension",()=>{const a=validAnswers();a.q13=["Very comfortable"];a.q15=["Consultative/solution selling"];a.q16=["Ask questions to understand what's holding them back"];a.q14=["I'd strongly prefer a business that doesn't depend on me doing that"];a.q30=["Strongly prefer little owner selling"];const result=analyze(a);assert.ok(result.dimensions.businessDevelopmentCapability>result.dimensions.businessDevelopmentAppetite);assert.ok(result.tensions.some(t=>t.title==="Sales Capability vs Sales Appetite"));});
test("leadership and low employee appetite create a Discovery tension",()=>{const a=validAnswers();a.q7=["I naturally organize people and resources around the objective"];a.q8=["Clarify expectations and coach them toward improvement"];a.q27=["Prefer as few employees as practical"];assert.ok(analyze(a).tensions.some(t=>t.title==="Leadership Capability vs Workforce Appetite"));});
test("income urgency and short runway creates high-priority Discovery",()=>{const a=validAnswers();a.q4=["Essential"];a.q35=["Less than 3 months"];const result=analyze(a);assert.ok(result.tensions.some(t=>t.title==="Income Urgency vs Ramp Capacity"&&t.priority==="high"));assert.ok(result.discoveryPriorities.some(p=>p.title==="Income Ramp"&&p.priority==="high"));});
test("autonomy and system alignment are preserved as distinct dimensions",()=>{const a=validAnswers();a.q11=["Resist changing something I believe is already working"];a.q12=["Use my approach if I'm confident it will perform better"];const result=analyze(a);assert.ok(result.dimensions.systemAlignment<=35);assert.ok(result.dimensions.independentJudgment>=70);assert.ok(result.tensions.some(t=>t.title==="Autonomy vs Franchise-System Alignment"));});
test("investment guidance creates validation rather than qualification",()=>{const a=validAnswers();a.q34=["I need more guidance before setting an investment range"];const result=analyze(a);assert.equal(result.opportunityCharacteristics.find(c=>c.characteristic==="stated investment range").disposition,"Validate");assert.ok(!JSON.stringify(result).match(/qualified|approved|pass|fail/i));});
test("not-sure motivation produces exploratory Discovery work",()=>{const a=validAnswers();a.q1=["I'm still figuring that out"];delete a.q2;assert.deepEqual(validateConferenceSubmission(intake,a,true),[]);assert.ok(analyze(a).discoveryPriorities.some(p=>p.title==="Ownership Direction"));});
test("candidate profile is filtered while consultant analysis retains evidence and tensions",()=>{const result=analyze();assert.ok(result.ownershipProfile.primary);assert.ok(!("dimensions" in result.ownershipProfile));assert.ok(result.evidence.length>=7);assert.ok(Array.isArray(result.tensions));});
test("ten materially different personas produce differentiated intelligence",()=>{const results=conferenceAssessmentPersonas.map(persona=>new ConferenceAssessmentAnalysisService().analyze(personaIntake,persona.answers));assert.ok(new Set(results.map(result=>result.ownershipProfile.primary)).size>=4);assert.ok(new Set(results.map(result=>JSON.stringify(result.opportunityCharacteristics))).size>=8);assert.ok(new Set(results.map(result=>`${result.executiveSummary}|${result.tensions.map(t=>t.title).join()}`)).size>=8);});
test("persona-specific tensions and priorities follow their evidence",()=>{const byName=new Map(conferenceAssessmentPersonas.map(persona=>[persona.name,new ConferenceAssessmentAnalysisService().analyze(personaIntake,persona.answers)]));assert.ok(byName.get("Sales-Capable Sales-Averse").tensions.some(t=>t.title==="Sales Capability vs Sales Appetite"));assert.ok(byName.get("High Capital Low Investment Comfort").tensions.some(t=>t.title==="Financial Capacity vs Investment Comfort"));assert.ok(byName.get("Multi-Unit Ambition Low Delegation").discoveryPriorities.some(p=>p.title==="Scale and Delegation"));});
test("Discovery priorities are unique, actionable questions",()=>{for(const persona of conferenceAssessmentPersonas){const priorities=new ConferenceAssessmentAnalysisService().analyze(personaIntake,persona.answers).discoveryPriorities;assert.equal(new Set(priorities.map(item=>item.title)).size,priorities.length);assert.ok(priorities.every(item=>item.suggestedQuestion.endsWith("?")&&item.evidenceRefs.length>=2));}});
test("uncertain profile is not forced and financial uncertainty is not penalized",()=>{const persona=conferenceAssessmentPersonas.find(item=>item.name==="Undecided Exploratory");const result=new ConferenceAssessmentAnalysisService().analyze(personaIntake,persona.answers);assert.equal(result.ownershipProfile.primary,"Your ownership profile is still taking shape.");assert.equal(result.ownershipProfile.confidenceState,"Explore During Discovery");assert.equal(result.opportunityCharacteristics.find(item=>item.characteristic==="stated investment range").disposition,"Validate");});
