import assert from "node:assert/strict";
import test from "node:test";
import { ConferenceAssessmentAnalysisService } from "../../feature/assessment-engine/conference/ConferenceAssessmentAnalysisService.ts";
import { conferenceQuestions, concernExclusive } from "../../feature/assessment-engine/conference/questions.ts";
import { applyExclusiveSelection, validateConferenceSubmission } from "../../feature/assessment-engine/conference/validation.ts";

const intake = { firstName:"Alex",lastName:"Morgan",email:"alex@example.com",mobilePhone:"555-0100",streetAddress:"1 Main St",city:"Orlando",stateProvince:"FL",postalCode:"32801",country:"United States",occupationTitle:"VP Operations",ownedBusinessBefore:"no",exploredFranchiseBefore:"yes",preferredContactMethod:"email",bestContactTime:"morning" };
function validAnswers() { const answers = {}; for (const q of conferenceQuestions) { if(q.kind !== "context" && !q.primaryOf) answers[q.id]=[q.options[0]]; } answers.q2=[answers.q1[0]];answers.q21=[answers.q20[0]];answers["q36-geography"]=["Need to remain near my current location"];answers["q36-stakeholders"]=["Decision is primarily mine"];answers["q36-stage"]=["Actively researching franchises"];answers.concerns=[concernExclusive];return answers; }
const analyze = (answers=validAnswers()) => new ConferenceAssessmentAnalysisService().analyze(intake,answers);

test("frozen assessment contains 36 questions in six sections",()=>{assert.equal(conferenceQuestions.length,36);assert.deepEqual([...new Set(conferenceQuestions.map(q=>q.section))],[1,2,3,4,5,6]);});
test("exclusive choice clears incompatible values and toggles ordinary values",()=>{assert.deepEqual(applyExclusiveSelection(["Build wealth"],"I'm still figuring that out",["I'm still figuring that out"]),["I'm still figuring that out"]);assert.deepEqual(applyExclusiveSelection(["I'm still figuring that out"],"Build wealth",["I'm still figuring that out"]),["Build wealth"]);});
test("validation requires consent, intake, all questions and context",()=>{const errors=validateConferenceSubmission({...intake,email:"bad"}, {}, false);assert.ok(errors.includes("Consent is required"));assert.ok(errors.includes("Enter a valid email address"));assert.ok(errors.includes("Missing q1"));assert.ok(errors.includes("Missing q36-stage"));});
test("valid complete response passes validation",()=>assert.deepEqual(validateConferenceSubmission(intake,validAnswers(),true),[]));
test("conditional primary response must come from parent selections",()=>{const a=validAnswers();a.q2=["not selected"];assert.ok(validateConferenceSubmission(intake,a,true).includes("q2 must use a prior selection"));});
test("evidence preserves capability preference motivation and constraint categories",()=>{const categories=new Set(analyze().evidence.map(e=>e.category));assert.deepEqual([...categories].sort(),["capability","constraint","motivation","preference"]);});
test("analysis is deterministic",()=>assert.deepEqual(analyze(),analyze()));
test("high sales capability and low appetite remain separate and create tension",()=>{const a=validAnswers();a.q13=["Very comfortable"];a.q15=["Consultative/solution selling"];a.q16=["Ask questions to understand what's holding them back"];a.q14=["I'd strongly prefer a business that doesn't depend on me doing that"];a.q30=["Strongly prefer little owner selling"];const result=analyze(a);assert.ok(result.dimensions.businessDevelopmentCapability>result.dimensions.businessDevelopmentAppetite);assert.ok(result.tensions.some(t=>t.title==="Sales Capability vs Sales Appetite"));});
test("leadership and low employee appetite create a Discovery tension",()=>{const a=validAnswers();a.q7=["I naturally organize people and resources around the objective"];a.q27=["Prefer as few employees as practical"];assert.ok(analyze(a).tensions.some(t=>t.title==="Leadership Capability vs Employee Appetite"));});
test("income urgency and short runway creates high-priority Discovery",()=>{const a=validAnswers();a.q4=["Essential"];a.q35=["Less than 3 months"];const result=analyze(a);assert.ok(result.tensions.some(t=>t.title==="Income Urgency vs Household Runway"&&t.priority==="high"));assert.ok(result.discoveryPriorities.some(p=>p.title==="Income Ramp"&&p.priority==="high"));});
test("system alignment and independent judgment are preserved as distinct dimensions",()=>{const a=validAnswers();a.q11=["Resist changing something I believe is already working"];a.q12=["Follow the system as designed until I understand it thoroughly"];const result=analyze(a);assert.ok(result.dimensions.systemAlignment>=65);assert.ok(result.dimensions.independentJudgment>=70);assert.ok(result.tensions.some(t=>t.title==="System Alignment vs Independent Judgment"));});
test("investment guidance creates validation rather than qualification",()=>{const a=validAnswers();a.q34=["I need more guidance before setting an investment range"];const result=analyze(a);assert.equal(result.opportunityCharacteristics.find(c=>c.characteristic==="moderate investment").disposition,"Validate");assert.ok(!JSON.stringify(result).match(/qualified|approved|pass|fail/i));});
test("not-sure motivation produces exploratory Discovery work",()=>{const a=validAnswers();a.q1=["I'm still figuring that out"];delete a.q2;assert.deepEqual(validateConferenceSubmission(intake,a,true),[]);assert.ok(analyze(a).discoveryPriorities.some(p=>p.title==="Ownership Direction"));});
test("candidate profile is filtered while consultant analysis retains evidence and tensions",()=>{const result=analyze();assert.ok(result.ownershipProfile.primary);assert.ok(!("dimensions" in result.ownershipProfile));assert.ok(result.evidence.length>=7);assert.ok(Array.isArray(result.tensions));});
