import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyEmailDocument} from '../../feature/marketing/studio/document.ts';
import {renderStudioDelivery,studioPersonalization,validateStudioSend,deliveryAddress} from '../../feature/marketing/delivery/studio-snapshot.ts';
import {renderStudioEmail} from '../../feature/marketing/studio/render.ts';
import {oneClickUnsubscribe} from '../../feature/marketing/delivery/unsubscribe-http.ts';
import {ResendMarketingDeliveryProvider} from '../../feature/marketing/delivery/resend/ResendMarketingDeliveryProvider.ts';
const branding={version:1,company:'Synthetic Company',website:'',postalAddress:'100 Synthetic Lane, Example City, NY 10001',primaryColor:'#172033',accentColor:'#2563EB',font:'arial',logo:null,headshot:null,name:'Alex Morgan',title:'Consultant',email:'alex@example.test',phone:'555-0100',linkedIn:'',scheduling:''};
const source=()=>({content:{...emptyEmailDocument(),document:{type:'doc',content:[{type:'heading',attrs:{level:1,textAlign:'left'},content:[{type:'text',text:'Hello {{preferred_name}}'}]},{type:'paragraph',attrs:{textAlign:'left'},content:[{type:'mergeField',attrs:{field:'first_name'}},{type:'text',text:' / '},{type:'mergeField',attrs:{field:'consultant_name'}}]},{type:'button',attrs:{label:'Meet {{preferred_name}}',href:'https://example.test/meet',alignment:'left'}}]}},subject:'Hello {{preferred_name}}',preview_text:'For {{first_name}}',sender_name:'Alex Morgan',reply_to:'alex@example.test',studio_snapshot:{version:1,rendererVersion:'studio-001c-1',personalizationVersion:1,branding:{...branding},assets:{},mediaOrigin:'https://example.supabase.co',publicOrigin:'https://demo.example.test',audienceFingerprint:'a'.repeat(64)}});
const token='a'.repeat(64);
test('published image delivery uses only the frozen asset path and public origin',()=>{const s=source(),id='asset_'+'a'.repeat(32),path='a1000000-0000-0000-0000-000000000001/'+id+'/1/email.png';s.content.document.content.push({type:'emailImage',attrs:{assetId:id,alt:'Frozen banner',width:100,alignment:'left',href:null}});s.studio_snapshot.assets[id]={deliveryPath:path,checksum:'b'.repeat(64),width:100,height:100,version:1};const output=renderStudioDelivery(s,{},token);assert.ok(output.html.includes('https://example.supabase.co/storage/v1/object/public/studio-delivery/'+path));assert.ok(output.text.includes('Frozen banner'));});
test('sender identity cannot override governed campaign branding',()=>{for(const field of ['sender_name','reply_to']){const s=source();s[field]=field==='sender_name'?'Another consultant':'other@example.test';assert.throws(()=>validateStudioSend(s),/saved campaign branding/);}});
test('preferred-name delivery uses preferred name and deterministic fallbacks',()=>{assert.deepEqual(studioPersonalization({firstName:'James',preferredName:'Jim'},'Alex'),{first_name:'James',preferred_name:'Jim',consultant_name:'Alex'});assert.equal(studioPersonalization({firstName:'James'},'').preferred_name,'James');assert.equal(studioPersonalization({},'').first_name,'there');assert.equal(studioPersonalization({preferredName:'Jim'},'Alex').first_name,'Jim');});
test('V2 HTML and independent text personalize subject, preheader, text and merge nodes',()=>{const r=renderStudioDelivery(source(),{firstName:'James',preferredName:'Jim'},token);assert.equal(r.subject,'Hello Jim');assert.match(r.html,/For James/);assert.match(r.html,/Hello Jim/);assert.match(r.text,/James \/ Alex Morgan/);assert.match(r.text,/Meet Jim: https:\/\/example.test\/meet/);assert.doesNotMatch(r.text,/<table|<a /);});
test('personalization is escaped as text and cannot become attributes or URLs',()=>{const r=renderStudioDelivery(source(),{firstName:'<script>bad()</script>',preferredName:'"><img src=x onerror=bad()>'},token);assert.doesNotMatch(r.html,/<script>|onerror=bad\(\)>/);assert.match(r.html,/&lt;img/);assert.match(r.html,/href="https:\/\/example.test\/meet"/);assert.match(r.text,/<script>bad\(\)<\/script>/);});
test('governed HTML and text compliance is appended outside editable content',()=>{const r=renderStudioDelivery(source(),{},token);for(const x of [r.html,r.text]){assert.ok(x.includes(branding.postalAddress));assert.ok(x.includes(branding.company));assert.ok(x.includes('/unsubscribe/'+token));}assert.match(r.headers['List-Unsubscribe'],/\/api\/marketing\/unsubscribe\//);assert.equal(r.headers['List-Unsubscribe-Post'],'List-Unsubscribe=One-Click');});
test('test email has isolated unsubscribe, explicit markers and same document',()=>{const r=renderStudioDelivery(source(),{},token,true);assert.match(r.subject,/^\[TEST\]/);assert.match(r.html,/TEST EMAIL/);assert.match(r.text,/^TEST EMAIL/);assert.match(r.html,/\/api\/marketing\/test-unsubscribe\//);assert.doesNotMatch(r.html,/href="https:\/\/demo.example.test\/unsubscribe\//);});
test('invalid schema version and unsupported renderer fail closed',()=>{for(const change of [s=>s.content.version=3,s=>s.studio_snapshot.rendererVersion='unknown',s=>s.studio_snapshot.personalizationVersion=2,s=>s.content.document.content.push({type:'html',html:'<script/>'})]){const s=source();change(s);assert.throws(()=>validateStudioSend(s));}});
test('missing subject, sender, reply-to, branding identity and postal address block delivery',()=>{for(const change of [s=>s.subject='',s=>s.sender_name='',s=>s.reply_to='bad',s=>s.studio_snapshot.branding.postalAddress='',s=>s.studio_snapshot.branding.company='',s=>s.studio_snapshot.branding.email='bad',s=>s.studio_snapshot.branding.name='']){const s=source();change(s);assert.throws(()=>validateStudioSend(s));}});
test('unresolved images and image placeholders cannot be delivered',()=>{for(const id of [null,'asset_'+'a'.repeat(32)]){const s=source();s.content.document.content.push({type:'emailImage',attrs:{assetId:id,alt:'Image',width:100,alignment:'left',href:null}});assert.throws(()=>renderStudioDelivery(s,{},token));}});
test('immutable source and token produce byte-identical payloads despite profile edits',()=>{const frozen=source(),first=renderStudioDelivery(frozen,{preferredName:'Jim'},token);const edited=source();edited.studio_snapshot.branding.name='Changed';edited.content.document.content=[];assert.deepEqual(renderStudioDelivery(frozen,{preferredName:'Jim'},token),first);});
test('preview and delivery share rendering except inert links and personalization',()=>{const s=source(),out=renderStudioDelivery(s,{firstName:'Jordan'},token);const preview=renderStudioEmail(s.content,{subject:s.subject,preheader:s.preview_text,personalization:studioPersonalization({firstName:'Jordan'},branding.name),compliance:{sender:s.sender_name+' | '+branding.company,postalAddress:branding.postalAddress,unsubscribeUrl:s.studio_snapshot.publicOrigin+'/unsubscribe/'+token},preview:true,assets:{}});assert.equal(preview.text,out.text);assert.equal(preview.subject,out.subject);assert.match(preview.html,/Hello Jordan/);assert.doesNotMatch(preview.html,/<a /);assert.match(out.html,/<a /);});
test('explicit test recipient validation rejects reserved synthetic destinations',()=>{for(const email of ['alex@frangroove-demo.example','test@example.test','test@example.com','bad'])assert.equal(deliveryAddress.safeParse(email).success,false);assert.equal(deliveryAddress.safeParse('approved@real-domain.org').success,true);});
test('one-click accepts standards-compatible POST and hashes the token',async()=>{let digest;const r=await oneClickUnsubscribe(new Request('https://demo.example.test/u',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:'List-Unsubscribe=One-Click'}),token,async d=>{digest=d;return true;});assert.equal(r.status,200);assert.match(digest,/^[a-f0-9]{64}$/);assert.notEqual(digest,token);});
test('one-click rejects malformed tokens, oversized bodies and incorrect form fields',async()=>{let calls=0;for(const [raw,body,status]of [['bad','List-Unsubscribe=One-Click',400],[token,'x'.repeat(1025),413],[token,'List-Unsubscribe=No',400],[token,'List-Unsubscribe=One-Click&extra=bad',400]]){const r=await oneClickUnsubscribe(new Request('https://demo.example.test/u',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body}),raw,async()=>{calls++;return true;});assert.equal(r.status,status);}assert.equal(calls,0);});
test('Resend receives only supported unsubscribe headers and frozen HTML/text',async()=>{let body;const provider=new ResendMarketingDeliveryProvider({apiKey:'mock',fromEmail:'sender@real-domain.org'},async(_url,request)=>{body=JSON.parse(request.body);return Response.json({id:'mock-message'});});const rendered=renderStudioDelivery(source(),{},token);const result=await provider.submit({deliveryKey:'rcpt_test',senderName:'Alex',to:'approved@real-domain.org',replyTo:'alex@real-domain.org',...rendered,headers:{...rendered.headers,'X-Untrusted':'bad'},metadata:{}});assert.equal(result.kind,'accepted');assert.deepEqual(body.headers,rendered.headers);assert.equal(body.html,rendered.html);assert.equal(body.text,rendered.text);});

import {marketingPublicOrigin} from '../../feature/marketing/delivery/public-origin.ts';
test('public origin override drives both V2 body alternatives and supported one-click paths',()=>{
 const origin='https://frangroove-public-unsubscribe.vercel.app';
 for(const testSend of [false,true]){
  const s=source();s.studio_snapshot.publicOrigin=marketingPublicOrigin('https://protected.vercel.app',{MARKETING_PUBLIC_URL:origin});
  const output=renderStudioDelivery(s,{firstName:'James',preferredName:'Jim'},token,testSend);
  const bodyPath=testSend?'/api/marketing/test-unsubscribe/':'/unsubscribe/';
  const postPath=testSend?'/api/marketing/test-unsubscribe/':'/api/marketing/unsubscribe/';
  assert.ok(output.html.includes(origin+bodyPath+token));assert.ok(output.text.includes(origin+bodyPath+token));
  assert.equal(output.headers['List-Unsubscribe'],`<${origin}${postPath}${token}>`);
  assert.equal(output.headers['List-Unsubscribe-Post'],'List-Unsubscribe=One-Click');
 }
});
test('public origin fails closed for invalid overrides and preserves an unconfigured fallback',()=>{
 assert.equal(marketingPublicOrigin('http://localhost:3000',{}),'http://localhost:3000');
 for(const value of ['', 'http://example.test','https://example.test/path','https://user:secret@example.test','https://example.test/','https://example.test?x=1'])assert.throws(()=>marketingPublicOrigin('https://fallback.test',{MARKETING_PUBLIC_URL:value}));
});
