import test from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks,stripTypeScriptTypes} from 'node:module';
import {readFileSync} from 'node:fs';
import {emptyEmailDocument} from '../../feature/marketing/studio/document.ts';
registerHooks({resolve(s,c,next){
 if(s==='server-only')return{url:'data:text/javascript,export{}',shortCircuit:true};
 if(s==='@/lib/supabase/admin')return{url:'data:text/javascript,export const createAdminSupabaseClient=()=>globalThis.__studioWorkerDb',shortCircuit:true};
 if(s.startsWith('@/'))return next(new URL('../../'+s.slice(2)+'.ts',import.meta.url).href,c);
 try{return next(s,c);}catch(e){if(s.startsWith('.')&&!/\.[a-z]+$/.test(s))return next(s+'.ts',c);throw e;}
},load(url,c,next){if(/\/(StudioDeliveryService|SupabaseMarketingDeliveryRepository)\.ts$/.test(url))return{format:'module',source:stripTypeScriptTypes(readFileSync(new URL(url),'utf8'),{mode:'transform'}),shortCircuit:true};return next(url,c);}});
const {SupabaseMarketingDeliveryRepository}=await import('../../feature/marketing/delivery/SupabaseMarketingDeliveryRepository.ts');
function fixture(version=2){
 const branding={version:1,company:'Synthetic Company',website:'',postalAddress:'100 Synthetic Lane, Example City',primaryColor:'#172033',accentColor:'#2563EB',font:'arial',logo:null,headshot:null,name:'Alex',title:'Consultant',email:'alex@example.test',phone:'',linkedIn:'',scheduling:''};
 const run={id:'run-id',public_id:'send_test',organization_id:'org',content_version:version,content:version===2?emptyEmailDocument():{version:1,heading:'Hello',body:'Hi {{first_name}}',ctaLabel:'Meet',ctaUrl:'https://example.test',footer:'Footer'},subject:'Hello {{preferred_name}}',preview_text:'Preview',sender_name:'Alex',reply_to:branding.email,studio_snapshot:{version:1,rendererVersion:'studio-001c-1',personalizationVersion:1,branding,assets:{},mediaOrigin:'https://media.example.test',publicOrigin:'https://app.example.test',audienceFingerprint:'a'.repeat(64)},eligible_count:1,status:'sending'};
 const recipient={public_id:'rcpt_test',normalized_email:'recipient@example.test',personalization:{firstName:'James',preferredName:'Jim'},status:'processing'};
 const calls=[],state={payload:null,claimed:true};
 const db={from(){const q={select(){return q},eq(){return q},single:async()=>({data:run}),order(){return q},limit:async()=>({data:[recipient]})};return q;},async rpc(name,args){calls.push(name);if(name==='claim_campaign_recipients')return{data:state.claimed?[recipient]:[]};if(name==='studio_recipient_payload'){if(!state.payload&&args.new_payload)state.payload=structuredClone(args.new_payload);return{data:state.payload};}if(name==='complete_campaign_recipient'){recipient.status=args.result_status;state.claimed=false;}return{data:null};}};
 return{run,recipient,calls,state,db,repository:new SupabaseMarketingDeliveryRepository(db,null)};
}
test('existing worker persists both personalized alternatives before provider submission',async()=>{const f=fixture();const provider={mode:'external',async submit(p){assert.deepEqual(p,f.state.payload);assert.match(p.subject,/Jim/);assert.ok(p.html.length&&p.text.length);assert.ok(f.calls.includes('studio_recipient_payload'));return{kind:'accepted',providerMessageId:'mock-accepted'};}};await f.repository.processBatch('send_test',provider,'https://app.example.test',10);assert.equal(f.recipient.status,'accepted');assert.equal(f.state.payload.deliveryKey,'rcpt_test');});
test('worker crash after provider acceptance reuses frozen bytes and idempotency key',async()=>{const f=fixture();let first;await assert.rejects(f.repository.processBatch('send_test',{mode:'external',async submit(p){first=structuredClone(p);throw Error('connection lost after acceptance');}},'https://app.example.test',10));assert.ok(f.state.payload);await f.repository.processBatch('send_test',{mode:'external',async submit(p){assert.deepEqual(p,first);return{kind:'accepted',providerMessageId:'mock-same-id'};}},'https://changed.example.test',10);assert.equal(f.recipient.status,'accepted');});
test('provider failure is recorded and never labelled accepted',async()=>{const f=fixture();await f.repository.processBatch('send_test',{mode:'external',async submit(){return{kind:'permanent-failure',code:'mock-rejected'};}},'https://app.example.test',10);assert.equal(f.recipient.status,'failed');});
test('V2 transient provider errors retain the lease for frozen-payload retry',async()=>{const f=fixture();await f.repository.processBatch('send_test',{mode:'external',async submit(){return{kind:'transient-failure',code:'resend-timeout'};}},'https://app.example.test',10);assert.equal(f.recipient.status,'processing');assert.ok(!f.calls.includes('complete_campaign_recipient'));const frozen=structuredClone(f.state.payload);await f.repository.processBatch('send_test',{mode:'external',async submit(p){assert.deepEqual(p,frozen);return{kind:'accepted',providerMessageId:'mock-retry'};}},'https://app.example.test',10);assert.equal(f.recipient.status,'accepted');});
test('V1 continues through its existing renderer and unsubscribe registration',async()=>{const f=fixture(1);await f.repository.processBatch('send_test',{mode:'external',async submit(p){assert.match(p.text,/James/);assert.equal(p.deliveryKey,'rcpt_test');return{kind:'accepted',providerMessageId:'mock-v1'};}},'https://app.example.test',10);assert.ok(f.calls.includes('register_marketing_unsubscribe_token'));assert.ok(!f.calls.includes('studio_recipient_payload'));});
