import test from'node:test';import assert from'node:assert/strict';import{ResendMarketingDeliveryProvider}from'../../feature/marketing/delivery/resend/ResendMarketingDeliveryProvider.ts';
const submission={deliveryKey:'rcpt_public_safe',senderName:'Alex Morgan',to:'recipient@example.test',replyTo:'alex@example.test',subject:'Hello',html:'<p>Hello</p>',text:'Hello',metadata:{sendRunId:'send_public_safe',recipientId:'rcpt_public_safe',unsafe:'contains spaces'}};
test('Resend acceptance maps provider id and builds authenticated provider-neutral request',async()=>{let request;const fetcher=async(url,init)=>{request={url,init};return new Response(JSON.stringify({id:'resend-message-1'}),{status:200,headers:{'content-type':'application/json'}})};const provider=new ResendMarketingDeliveryProvider({apiKey:'fake-local-api-key',fromEmail:'mail@example.test'},fetcher);assert.deepEqual(await provider.submit(submission),{kind:'accepted',providerMessageId:'resend-message-1'});assert.equal(request.url,'https://api.resend.com/emails');assert.equal(request.init.headers.Authorization,'Bearer fake-local-api-key');assert.equal(request.init.headers['Idempotency-Key'],'frangroove/rcpt_public_safe');const body=JSON.parse(request.init.body);assert.equal(body.from,'Alex Morgan <mail@example.test>');assert.equal(body.reply_to,'alex@example.test');assert.deepEqual(body.tags,[{name:'sendRunId',value:'send_public_safe'},{name:'recipientId',value:'rcpt_public_safe'}]);assert.doesNotMatch(JSON.stringify(body),/fake-local-api-key/)});
test('Resend preserves a validated display-name sender mailbox without nesting it',async()=>{let body;const provider=new ResendMarketingDeliveryProvider({apiKey:'fake',fromEmail:'FranGroove <hello@mail.frangroove.com>'},async(_url,init)=>{body=JSON.parse(init.body);return new Response(JSON.stringify({id:'resend-message-1'}),{status:200})});assert.equal((await provider.submit(submission)).kind,'accepted');assert.equal(body.from,'FranGroove <hello@mail.frangroove.com>')});
test('Resend idempotency identity remains stable across safe retries',async()=>{const keys=[];const fetcher=async(_url,init)=>{keys.push(init.headers['Idempotency-Key']);return new Response(JSON.stringify({id:'same-id'}),{status:200})};const provider=new ResendMarketingDeliveryProvider({apiKey:'fake',fromEmail:'mail@example.test'},fetcher);await provider.submit(submission);await provider.submit(submission);assert.deepEqual(keys,['frangroove/rcpt_public_safe','frangroove/rcpt_public_safe'])});
test('Resend classifies rate limits and server errors as transient',async()=>{for(const status of[429,503]){const provider=new ResendMarketingDeliveryProvider({apiKey:'fake',fromEmail:'mail@example.test'},async()=>new Response('',{status}));assert.deepEqual(await provider.submit(submission),{kind:'transient-failure',code:`resend-http-${status}`})}});
test('Resend classifies validation failures as permanent without response leakage',async()=>{const provider=new ResendMarketingDeliveryProvider({apiKey:'fake',fromEmail:'mail@example.test'},async()=>new Response(JSON.stringify({message:'sensitive provider detail'}),{status:422}));assert.deepEqual(await provider.submit(submission),{kind:'permanent-failure',code:'resend-http-422'})});
test('Resend treats malformed success as retryable under the same idempotency key',async()=>{const provider=new ResendMarketingDeliveryProvider({apiKey:'fake',fromEmail:'mail@example.test'},async()=>new Response('{}',{status:200}));assert.deepEqual(await provider.submit(submission),{kind:'transient-failure',code:'resend-invalid-response'})});
test('Resend enforces an explicit request timeout',async()=>{const fetcher=async(_url,init)=>new Promise((_resolve,reject)=>init.signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError'))));const provider=new ResendMarketingDeliveryProvider({apiKey:'fake',fromEmail:'mail@example.test',timeoutMs:5},fetcher);assert.deepEqual(await provider.submit(submission),{kind:'transient-failure',code:'resend-timeout'})});
