import type { AssessmentEvidence, AssessmentTension, ConferenceAnalysis, ConferenceAnswers, ConferenceIntake, DiscoveryPriority, EvidenceCategory, OpportunityCharacteristic } from "./types";

const a = (answers: ConferenceAnswers, id: string) => answers[id] ?? [];
const one = (answers: ConferenceAnswers, id: string) => a(answers, id)[0] ?? "Not provided";
const has = (answers: ConferenceAnswers, id: string, value: string) => a(answers, id).includes(value);
const any = (answers: ConferenceAnswers, id: string, values: string[]) => a(answers, id).some((value) => values.includes(value));
function scale(answers: ConferenceAnswers, id: string, options: string[], fallback = 50) { const index=options.indexOf(one(answers,id));return index<0?fallback:Math.round(index/Math.max(1,options.length-1)*100); }
function confidence(count:number,expected:number,contradictions=0){const strength=Math.min(1,count/expected);const coverage=Math.min(1,count/expected);const consistency=1-Math.min(1,contradictions/Math.max(1,count));return Number((.45*strength+.3*coverage+.25*consistency).toFixed(2));}
function confidenceState(value:number):"High Confidence"|"Moderate Confidence"|"Explore During Discovery"{return value>=.8?"High Confidence":value>=.58?"Moderate Confidence":"Explore During Discovery";}

function profiles(d:Record<string,number>){return [...([
  ["Strategic Growth Builder",d.growthOrientation*1.2+d.delegationOrientation+d.leadershipCapability*.4],
  ["Relationship-Led Growth Owner",d.relationshipOrientation*1.2+d.businessDevelopmentCapability+d.communityVisibility*.35],
  ["Team-Building Leader",d.leadershipCapability*1.2+d.employeeAppetite+d.delegationOrientation*.45],
  ["Hands-On Business Operator",d.operatingInvolvement*1.2+d.executionOrientation-d.businessDevelopmentAppetite*.2],
  ["Executive Business Developer",d.businessDevelopmentCapability+d.businessDevelopmentAppetite*1.15+d.strategicOwnerPreference*.55],
  ["Independent Asset Builder",d.independentJudgment+d.assetOrientation*1.1+d.strategicOwnerPreference*.45],
] as const)].sort((x,y)=>y[1]-x[1]);}

export class ConferenceAssessmentAnalysisService {
  analyze(_intake:ConferenceIntake,answers:ConferenceAnswers):ConferenceAnalysis {
    const dimensions:Record<string,number>={
      businessDevelopmentCapability:Math.round((scale(answers,"q13",["Very uncomfortable","Somewhat uncomfortable","Neutral","Comfortable","Very comfortable"])+(a(answers,"q15").some(v=>v!=="None particularly appeal to me")?75:25)+(any(answers,"q16",["Ask questions to understand what's holding them back","Provide information addressing their concerns","Ask directly what would need to happen for them to move forward"])?85:50))/3),
      businessDevelopmentAppetite:Math.round((scale(answers,"q14",["I'd strongly prefer a business that doesn't depend on me doing that","I'd do it but want to delegate it as soon as practical","Willing because it's necessary","Comfortable with it","Energized by it"])+scale(answers,"q30",["Strongly prefer little owner selling","Want most selling handled by employees","Some selling is fine","Remain involved in important sales","Selling would remain a major part of my role"]))/2),
      leadershipCapability:any(answers,"q7",["I naturally organize people and resources around the objective","I establish the process and monitor execution","I focus on the highest-impact pieces and delegate the rest"])&&any(answers,"q8",["Clarify expectations and coach them toward improvement","Ask questions to understand what's preventing performance","Begin considering whether they're the right person for the role"])?90:any(answers,"q7",["I naturally organize people and resources around the objective","I establish the process and monitor execution"])?78:55,
      employeeAppetite:scale(answers,"q27",["Prefer as few employees as practical","Prefer a small professional team","I'm not sure","Comfortable managing a moderate-sized team","Prefer managing managers rather than frontline employees","Enjoy building and leading larger teams"]),
      systemAlignment:scale(answers,"q12",["Use my approach if I'm confident it will perform better","Test my idea carefully while monitoring results","Ask experienced franchisees how they handle it","Follow it while discussing my idea with the franchisor","Follow the system as designed until I understand it thoroughly"]),
      independentJudgment:scale(answers,"q11",["Understand the reasoning and consider whether I should adjust","Try the recommendation before deciding whether I agree","Compare the feedback against the results I'm getting","Listen, but generally trust my own judgment","Resist changing something I believe is already working"]),
      riskTolerance:scale(answers,"q24",["Prefer predictability even if it limits upside","Accept modest risk when the downside is well understood","Comfortable with calculated risk when opportunity justifies it","Comfortable with significant uncertainty when I believe in the upside","Tend to act on opportunities before all information is available"]),
      resilience:any(answers,"q22",["Analyze what happened and adjust my approach","Follow up later while immediately moving to other opportunities","Ask for feedback about why I lost"])&&any(answers,"q23",["Study the numbers, identify the problem and adjust","Increase activity and work through it","Seek advice from the franchisor or experienced operators"])?85:any(answers,"q22",["Take some time to recover before re-engaging","Question whether I'm approaching the market correctly"])?40:65,
      incomeUrgency:scale(answers,"q4",["Not important","Somewhat important","Important","Very important","Essential"]),
      growthOrientation:any(answers,"q18",["Develop multiple territories or locations over time","Build an organization led by managers","Build a business or portfolio I could eventually sell"])?90:one(answers,"q18")==="I'm not sure yet"?35:55,
      relationshipOrientation:any(answers,"q15",["Networking and referrals","Building long-term professional relationships","Consultative/solution selling","Community involvement","Strategic partnerships"])?88:45,
      operatingInvolvement:any(answers,"q5",["Closely involved in day-to-day operations","Lead the team while remaining involved in key operations"])?90:one(answers,"q5")==="I'm not sure yet"?45:30,
      executionOrientation:any(answers,"q7",["I establish the process and monitor execution","I want clear ownership and prefer to be personally accountable for the outcome"])||has(answers,"q9","Improving processes")?88:55,
      assetOrientation:a(answers,"q1").some(v=>v.includes("wealth")||v.includes("asset")||v.includes("investments"))?88:45,
      delegationOrientation:any(answers,"q5",["Build a management team that handles most daily operations","Ultimately provide strategic oversight rather than manage daily activity"])||has(answers,"q7","I focus on the highest-impact pieces and delegate the rest")?90:has(answers,"q5","Closely involved in day-to-day operations")?25:55,
      strategicOwnerPreference:one(answers,"q5")==="Ultimately provide strategic oversight rather than manage daily activity"?95:one(answers,"q5")==="Build a management team that handles most daily operations"?80:35,
      communityVisibility:scale(answers,"q17",["Very uncomfortable","Somewhat uncomfortable","Neutral","Comfortable","Very comfortable"]),
    };
    const evidence:AssessmentEvidence[]=[];
    const evidenceOf=(questionId:string,category:EvidenceCategory,dimension:string,statement:string)=>evidence.push({id:`ev-${questionId}-${evidence.length+1}`,questionId,category,dimension,statement,strength:.8,confidence:confidence(a(answers,questionId).length,1)});
    a(answers,"q1").forEach(value=>evidenceOf("q1","motivation","ownershipMotivation",value));
    evidenceOf("q5","preference","ownerRole",`Preferred owner role: ${one(answers,"q5")}`);evidenceOf("q13","capability","businessDevelopmentCapability",`Prospecting comfort: ${one(answers,"q13")}`);evidenceOf("q14","preference","businessDevelopmentAppetite",`Launch-stage sales appetite: ${one(answers,"q14")}`);evidenceOf("q27","preference","employeeAppetite",`Staffing preference: ${one(answers,"q27")}`);evidenceOf("q12","preference","systemAlignment",`System response: ${one(answers,"q12")}`);evidenceOf("q35","constraint","householdRunway",`Household runway: ${one(answers,"q35")}`);evidenceOf("q33","constraint","liquidCapital",`Candidate-reported liquid capital: ${one(answers,"q33")}`);

    const tensions:AssessmentTension[]=[];const tension=(title:string,explanation:string,evidenceRefs:string[],priority:"high"|"normal"="normal")=>tensions.push({title,explanation,evidenceRefs,priority});
    if(dimensions.businessDevelopmentCapability>=65&&dimensions.businessDevelopmentAppetite<=45)tension("Sales Capability vs Sales Appetite","The responses suggest customer-development capability alongside a preference to reduce sustained owner-led selling. Explore models where launch requirements and the mature sales role are both acceptable.",["q13","q14","q15","q30"],"high");
    if(dimensions.leadershipCapability>=70&&dimensions.employeeAppetite<=45)tension("Leadership Capability vs Workforce Appetite","The responses suggest leadership capability alongside a preference for limited direct employee management. A lean or manager-led structure may deserve attention.",["q7","q8","q27","q28"],"high");
    if(dimensions.incomeUrgency>=75&&["Less than 3 months","3–6 months"].includes(one(answers,"q35")))tension("Income Urgency vs Ramp Capacity","The desired income-replacement pace may be faster than the reported household runway comfortably allows. Validate timing and contingency assumptions before narrowing models.",["q4","q35"],"high");
    if(dimensions.independentJudgment>=70&&dimensions.systemAlignment<=35)tension("Autonomy vs Franchise-System Alignment","The responses indicate strong confidence in personal judgment and a preference to change systems. Explore how much operating latitude is necessary within a franchise model.",["q11","q12"],"high");
    const highLiquidity=["$250,000–$499,999","$500,000–$999,999","$1,000,000+"].includes(one(answers,"q33"));const modestComfort=a(answers,"q34").length>0&&a(answers,"q34").every(v=>["Under $50,000","$50,000–$99,999","$100,000–$149,999"].includes(v));
    if((highLiquidity&&modestComfort)||one(answers,"q34").includes("guidance")||one(answers,"q33").includes("discuss"))tension("Financial Capacity vs Investment Comfort","Available capital and willingness to invest are separate decisions. Clarify the amount the candidate would feel comfortable placing at risk, regardless of capacity.",["q32","q33","q34"]);
    if(dimensions.growthOrientation>=75&&dimensions.delegationOrientation<=35)tension("Growth Ambition vs Delegation Preference","Multi-unit growth may require the owner to shift from personal control toward management systems and delegated execution.",["q5","q7","q18"],"high");

    const priorities:DiscoveryPriority[]=[];const priority=(title:string,whyItMatters:string,suggestedQuestion:string,evidenceRefs:string[],high=false)=>priorities.push({title,whyItMatters,suggestedQuestion,evidenceRefs,priority:high?"high":"normal",confidence:confidence(evidenceRefs.length,3)});
    if(dimensions.incomeUrgency>=60)priority("Income Ramp","Income replacement timing may materially narrow suitable operating models.","What income milestone would feel meaningful, by when, and what flexibility exists if the ramp takes longer?",["q4","q35"],dimensions.incomeUrgency>=75);
    priority("Owner-Led Sales","Launch and mature-stage selling preferences should align with the customer-acquisition model.","What role are you willing to personally play in customer acquisition during the first 18–24 months?",["q13","q14","q15","q30"],tensions.some(t=>t.title.startsWith("Sales")));
    priority("Franchise-System Autonomy","The right model should balance operating playbooks with room for judgment.","Where do you want clear franchisor direction, and where do you need latitude to make your own decisions?",["q11","q12"],tensions.some(t=>t.title.startsWith("Autonomy")));
    priority("Staffing Model","Team scale and management intensity shape the owner's daily work.","What size and type of team would you still want to lead after the business is established?",["q7","q8","q27","q28"],tensions.some(t=>t.title.startsWith("Leadership")));
    if(!has(answers,"q36-stakeholders","Decision is primarily mine"))priority("Decision Stakeholder Alignment","Other stakeholders may influence timing and investment comfort.","Who needs to be involved before you can confidently move forward, and what will each person need to understand?",["q20","q36-stakeholders"]);
    if(has(answers,"q1","I'm still figuring that out")||one(answers,"q18")==="I'm not sure yet")priority("Ownership Direction","Exploratory responses are an invitation to clarify success criteria, not a negative signal.","Which ownership outcome would make this exploration worthwhile even before choosing a business model?",["q1","q18"]);
    if(tensions.some(t=>t.title==="Financial Capacity vs Investment Comfort"))priority("Investment Comfort","Capacity does not establish willingness to invest or an acceptable downside.","Independent of what you could invest, what amount would you feel comfortable placing at risk and why?",["q32","q33","q34"]);
    if(tensions.some(t=>t.title==="Growth Ambition vs Delegation Preference"))priority("Scale and Delegation","The desired growth path may require a different owner role over time.","Which responsibilities would you need to delegate before a second territory or location could succeed?",["q5","q7","q18"],true);
    const unique=[...new Map(priorities.map(item=>[item.title,item])).values()];

    const characteristics:OpportunityCharacteristic[]=[
      {characteristic:"B2B",disposition:any(answers,"q25",["Businesses and executives","Professional practices","Local small businesses","Large companies"])?"Attractive":"Acceptable",reason:"Reflects selected customer environments."},
      {characteristic:"B2C",disposition:any(answers,"q25",["Individual consumers","Families","Children","Seniors","Homeowners"])?"Attractive":"Acceptable",reason:"Reflects selected customer environments."},
      {characteristic:"relationship-led",disposition:dimensions.relationshipOrientation>=70?"Attractive":"Acceptable",reason:"Derived from preferred business-development styles."},
      {characteristic:"owner selling",disposition:dimensions.businessDevelopmentAppetite>=65?"Attractive":dimensions.businessDevelopmentAppetite<=35?"Potential Constraint":"Validate",reason:"Keeps demonstrated capability separate from willingness to sell."},
      {characteristic:"lean team",disposition:dimensions.employeeAppetite<=45?"Attractive":"Acceptable",reason:"Reflects stated workforce appetite."},
      {characteristic:"employee-intensive",disposition:dimensions.employeeAppetite>=70?"Attractive":dimensions.employeeAppetite<=35?"Potential Constraint":"Validate",reason:"Reflects preferred workforce scale, not leadership ability."},
      {characteristic:"manager-led",disposition:dimensions.delegationOrientation>=75?"Attractive":dimensions.delegationOrientation<=35?"Potential Constraint":"Validate",reason:"Reflects the preferred mature owner role and delegation pattern."},
      {characteristic:"owner-operated",disposition:dimensions.operatingInvolvement>=70?"Attractive":"Acceptable",reason:"Reflects desired day-to-day involvement."},
      {characteristic:"home-based",disposition:has(answers,"q26","Home-based or remote")?"Attractive":"Acceptable",reason:"Reflects selected operating environments."},
      {characteristic:"retail",disposition:has(answers,"q31","Retail hours")?"Potential Constraint":has(answers,"q26","Retail storefront")?"Attractive":"Validate",reason:"Combines operating-environment interest with stated exclusions."},
      {characteristic:"business-hours",disposition:has(answers,"q29","Primarily weekday/business hours")?"Attractive":"Acceptable",reason:"Reflects stated schedule preferences."},
      {characteristic:"scalable territories",disposition:dimensions.growthOrientation>=75?"Attractive":"Acceptable",reason:"Reflects growth and expansion orientation."},
      {characteristic:"franchise-system intensive",disposition:dimensions.systemAlignment>=65?"Attractive":dimensions.systemAlignment<=35?"Potential Constraint":"Validate",reason:"Reflects comfort operating within a proven system."},
      {characteristic:"fast ramp",disposition:dimensions.incomeUrgency>=75?"Validate":"Acceptable",reason:"Income timing requires validation against business economics and household runway."},
      {characteristic:"stated investment range",disposition:one(answers,"q34").includes("guidance")||tensions.some(t=>t.title==="Financial Capacity vs Investment Comfort")?"Validate":"Acceptable",reason:"Uses stated comfort independently from reported capacity."},
    ];
    const ranked=profiles(dimensions);const uncertain=[one(answers,"q5"),one(answers,"q18")].filter(v=>v.includes("not sure")).length;const profileConfidence=confidence(evidence.length,9,tensions.length+uncertain*2);const shaping=has(answers,"q1","I'm still figuring that out")&&uncertain>0;const primary=shaping?"Your ownership profile is still taking shape.":ranked[0][0];
    return {version:"franchise-ownership-v1",evidence,dimensions,tensions:tensions.slice(0,4),discoveryPriorities:unique.slice(0,6),opportunityCharacteristics:characteristics,ownershipProfile:{primary,supporting:shaping?[]:ranked.slice(1,3).map(([name])=>name),confidence:profileConfidence,confidenceState:shaping?"Explore During Discovery":confidenceState(profileConfidence),motivations:a(answers,"q1"),operatingPreferences:[one(answers,"q5"),...a(answers,"q29")],strengths:[dimensions.leadershipCapability>=70?"Organizing people and execution":"Personal accountability",dimensions.businessDevelopmentCapability>=65?"Developing customer relationships":"Thoughtful decision-making",dimensions.resilience>=65?"Learning and adapting through setbacks":"Deliberate reflection under pressure"],characteristics:characteristics.filter(item=>item.disposition==="Attractive").map(item=>item.characteristic),consultantQuestions:unique.slice(0,4).map(item=>item.suggestedQuestion)},executiveSummary:shaping?`The ownership profile is still taking shape. Discovery should first clarify ${unique.slice(0,3).map(item=>item.title.toLowerCase()).join(", ")}.`:`The responses most closely reflect a ${primary}. Discovery should focus on ${unique.slice(0,3).map(item=>item.title.toLowerCase()).join(", ")}.`,financial:{netWorth:one(answers,"q32"),liquidCapital:one(answers,"q33"),investmentRange:a(answers,"q34").join(", "),disclaimer:"Candidate-reported and not independently verified by FranGroove."}};
  }
}
