import type { ConferenceQuestion } from "./types";

const o = (...values: string[]) => values;
export const conferenceSectionTitles = ["What You Want From Ownership", "How You Lead and Operate", "Customers, Sales & Growth", "How You Make Decisions", "The Business You Want", "Investment, Readiness & Discovery Context"];

export const conferenceQuestions: ConferenceQuestion[] = [
  { id:"q1",section:1,kind:"multi",prompt:"What is driving you to explore business ownership right now?",options:o("Build long-term wealth","Replace or exceed my current income","Gain greater control over my career","Create more flexibility in my life","Build an asset I could eventually sell","Create opportunities for my family","Make a greater impact in my community","Diversify my income or investments","Leave corporate employment","Put my experience and skills to work for myself","Build something I can be proud of","I'm still figuring that out"),exclusive:o("I'm still figuring that out"),evidence:"motivation breadth" },
  { id:"q2",section:1,kind:"single",prompt:"Of the motivations you selected, which one matters most?",primaryOf:"q1",evidence:"primary motivation" },
  { id:"q3",section:1,kind:"multi",prompt:"Imagine it's three years after buying your business. What would make you feel the decision had been successful?",options:o("I'm earning the income I wanted","I've built meaningful business equity","I have greater control over my schedule","I've built a strong team","The business can operate without me handling everything","I've expanded into additional territories, locations, or revenue streams","I'm doing work I find meaningful","My family has greater financial security","I've created something I could eventually sell","I have more control over the direction of my career"),evidence:"desired ownership outcomes" },
  { id:"q4",section:1,kind:"single",prompt:"How important is it that the business replace your current income relatively quickly?",options:o("Not important","Somewhat important","Important","Very important","Essential"),evidence:"income urgency" },
  { id:"q5",section:1,kind:"single",prompt:"Which statement comes closest to the role you'd ideally like to have in your business?",options:o("Closely involved in day-to-day operations","Lead the team while remaining involved in key operations","Spend most of my time developing customers and growing the business","Build a management team that handles most daily operations","Ultimately provide strategic oversight rather than manage daily activity","I'm not sure yet"),evidence:"preferred owner role" },
  { id:"q6",section:1,kind:"single",prompt:"If the right opportunity required you to work harder than you do today during the first 12–18 months, how would you feel?",options:o("I'd welcome it if I were building something of my own","I'd be comfortable with it for a defined period","I'd accept it, but work-life balance would remain important","I'd be reluctant to make that tradeoff","That would probably make the opportunity unattractive"),evidence:"startup intensity tolerance" },
  { id:"q7",section:2,kind:"single",prompt:"When you're responsible for an important result, which statement sounds most like you?",options:o("I want clear ownership and prefer to be personally accountable for the outcome","I naturally organize people and resources around the objective","I establish the process and monitor execution","I focus on the highest-impact pieces and delegate the rest","I prefer shared responsibility rather than carrying the result personally"),evidence:"accountability and leadership" },
  { id:"q8",section:2,kind:"single",prompt:"A capable employee repeatedly misses an important performance expectation. What are you most likely to do first?",options:o("Step in and handle the work myself","Clarify expectations and coach them toward improvement","Ask questions to understand what's preventing performance","Give them additional time to solve the problem independently","Reassign the responsibility to someone better suited","Begin considering whether they're the right person for the role"),evidence:"people-management behavior" },
  { id:"q9",section:2,kind:"multi",prompt:"Which business responsibilities would you genuinely enjoy?",options:o("Developing employees","Building customer relationships","Finding new customers","Negotiating","Improving processes","Managing financial performance","Solving difficult problems","Developing strategy","Managing projects","Recruiting and hiring","Networking","Leading managers","Working directly with customers","Analyzing performance data"),evidence:"activity appetite" },
  { id:"q10",section:2,kind:"multi",prompt:"Which responsibilities would you prefer to minimize or eventually delegate?",options:o("Developing employees","Building customer relationships","Finding new customers","Negotiating","Improving processes","Managing financial performance","Solving difficult problems","Developing strategy","Managing projects","Recruiting and hiring","Networking","Leading managers","Working directly with customers","Analyzing performance data"),evidence:"delegation preference" },
  { id:"q11",section:2,kind:"single",prompt:"When someone gives you constructive feedback that challenges your approach, what is your natural first reaction?",options:o("Understand the reasoning and consider whether I should adjust","Compare the feedback against the results I'm getting","Try the recommendation before deciding whether I agree","Listen, but generally trust my own judgment","Resist changing something I believe is already working"),evidence:"feedback receptivity" },
  { id:"q12",section:2,kind:"single",prompt:"You join a franchise system and discover a process you believe could be improved. What would you most likely do?",options:o("Follow the system as designed until I understand it thoroughly","Follow it while discussing my idea with the franchisor","Ask experienced franchisees how they handle it","Test my idea carefully while monitoring results","Use my approach if I'm confident it will perform better"),evidence:"franchise-system alignment" },
  { id:"q13",section:3,kind:"single",prompt:"How comfortable are you initiating a business conversation with someone you've never met?",options:o("Very uncomfortable","Somewhat uncomfortable","Neutral","Comfortable","Very comfortable"),evidence:"prospecting comfort" },
  { id:"q14",section:3,kind:"single",prompt:"Suppose your business required you personally to develop new customer relationships every week for the first two years. How would you feel?",options:o("Energized by it","Comfortable with it","Willing because it's necessary","I'd do it but want to delegate it as soon as practical","I'd strongly prefer a business that doesn't depend on me doing that"),evidence:"launch-stage sales appetite" },
  { id:"q15",section:3,kind:"multi",prompt:"Which types of business development feel most natural to you?",options:o("Networking and referrals","Building long-term professional relationships","Consultative/solution selling","Presenting to groups","One-on-one consumer sales","Digital/online lead follow-up","Community involvement","Strategic partnerships","Managing a sales team","Negotiating and closing","None particularly appeal to me"),exclusive:o("None particularly appeal to me"),evidence:"business-development style" },
  { id:"q16",section:3,kind:"single",prompt:"A prospective customer is interested but isn't ready to move forward. What would you most naturally do?",options:o("Give them space and wait","Ask questions to understand what's holding them back","Continue following up periodically","Provide information addressing their concerns","Ask directly what would need to happen for them to move forward","Focus my attention on more immediate opportunities"),evidence:"consultative sales behavior" },
  { id:"q17",section:3,kind:"single",prompt:"How comfortable would you be becoming a visible representative of your business in your local or professional community?",options:o("Very uncomfortable","Somewhat uncomfortable","Neutral","Comfortable","Very comfortable"),evidence:"community visibility appetite" },
  { id:"q18",section:3,kind:"single",prompt:"Which growth path sounds most appealing?",options:o("Build one strong business that provides excellent income","Build one business first and decide about expansion later","Develop multiple territories or locations over time","Build an organization led by managers","Build a business or portfolio I could eventually sell","I'm not sure yet"),evidence:"growth orientation" },
  { id:"q19",section:4,kind:"single",prompt:"You're considering an opportunity that fits most of what you want, but some unknowns remain. What are you most likely to do?",options:o("Continue researching until most uncertainty is eliminated","Define the important criteria and evaluate the evidence","Speak with people who have already made a similar decision","Trust my judgment once I have enough information","Wait until circumstances make the decision clearer","Walk away unless I feel highly certain"),evidence:"decision behavior under uncertainty" },
  { id:"q20",section:4,kind:"multi",prompt:"When making a significant financial decision, what helps you gain confidence?",options:o("Detailed financial analysis","Understanding downside risk","Talking with people who have already done it","Advice from trusted professionals","Understanding the operating model","Evidence of successful outcomes","Having adequate cash reserves","My own experience and judgment","Support from spouse/partner/family"),evidence:"decision-confidence evidence" },
  { id:"q21",section:4,kind:"single",prompt:"Of those factors, which one matters most?",primaryOf:"q20",evidence:"primary decision-confidence driver" },
  { id:"q22",section:4,kind:"single",prompt:"You spend several weeks pursuing an important customer and lose the business to a competitor. What are you most likely to do next?",options:o("Analyze what happened and adjust my approach","Follow up later while immediately moving to other opportunities","Ask for feedback about why I lost","Increase my effort on the next opportunity","Take some time to recover before re-engaging","Question whether I'm approaching the market correctly"),evidence:"setback recovery behavior" },
  { id:"q23",section:4,kind:"single",prompt:"Business results have been below expectations for several months. What are you most likely to do?",options:o("Study the numbers, identify the problem and adjust","Increase activity and work through it","Seek advice from the franchisor or experienced operators","Reconsider assumptions behind the business plan","Become concerned about whether I made the right decision","Give the strategy more time before changing anything"),evidence:"sustained-adversity response" },
  { id:"q24",section:4,kind:"single",prompt:"Which statement best describes your relationship with risk?",options:o("Prefer predictability even if it limits upside","Accept modest risk when the downside is well understood","Comfortable with calculated risk when opportunity justifies it","Comfortable with significant uncertainty when I believe in the upside","Tend to act on opportunities before all information is available"),evidence:"risk orientation" },
  { id:"q25",section:5,kind:"multi",prompt:"Which customer environments would you be comfortable serving?",options:o("Businesses and executives","Individual consumers","Families","Children","Seniors","Homeowners","Professional practices","Local small businesses","Large companies","No strong preference"),exclusive:o("No strong preference"),evidence:"customer-environment preference" },
  { id:"q26",section:5,kind:"multi",prompt:"Which operating environments appeal to you?",options:o("Home-based or remote","Professional office","Retail storefront","Service business operating in the field","Industrial/warehouse","Mobile business","Health/wellness","Food/hospitality","No strong preference"),exclusive:o("No strong preference"),evidence:"operating-environment preference" },
  { id:"q27",section:5,kind:"single",prompt:"How do you feel about managing employees?",options:o("Enjoy building and leading larger teams","Comfortable managing a moderate-sized team","Prefer a small professional team","Prefer as few employees as practical","Prefer managing managers rather than frontline employees","I'm not sure"),evidence:"employee appetite" },
  { id:"q28",section:5,kind:"multi",prompt:"Which workforce types would you be comfortable managing?",options:o("Professional salaried employees","Salespeople","Skilled technicians","Hourly employees","Part-time employees","Managers","High-turnover workforces","I strongly prefer a low-employee model"),exclusive:o("I strongly prefer a low-employee model"),evidence:"workforce tolerance" },
  { id:"q29",section:5,kind:"multi",prompt:"Which schedule characteristics matter to you?",options:o("Primarily weekday/business hours","Ability to work from home","Limited evenings","Limited weekends","Ability to travel periodically","Flexibility around family commitments","I'm comfortable working whenever the business requires it","Schedule isn't a major consideration"),exclusive:o("Schedule isn't a major consideration"),evidence:"schedule preferences" },
  { id:"q30",section:5,kind:"single",prompt:"How much personal selling would you ideally want to perform once the business is established?",options:o("Selling would remain a major part of my role","Remain involved in important sales","Some selling is fine","Want most selling handled by employees","Strongly prefer little owner selling"),evidence:"mature-stage sales appetite" },
  { id:"q31",section:5,kind:"multi",prompt:"What characteristics would make an opportunity less attractive?",options:o("Large number of employees","Significant owner selling","Retail hours","Nights/weekends","High fixed overhead","Large physical location","Heavy inventory","Significant travel","Highly seasonal revenue","Long ramp before meaningful income","Highly transactional customer relationships","Complex operations","None automatically rule an opportunity out"),exclusive:o("None automatically rule an opportunity out"),evidence:"negative opportunity preferences" },
  { id:"q32",section:6,kind:"single",prompt:"What is your approximate net worth?",options:o("Under $100,000","$100,000–$249,999","$250,000–$499,999","$500,000–$999,999","$1,000,000–$1,999,999","$2,000,000–$4,999,999","$5,000,000+","Prefer to discuss with my consultant"),evidence:"candidate-reported net worth" },
  { id:"q33",section:6,kind:"single",prompt:"Approximately how much liquid capital could you potentially make available for the right opportunity?",options:o("Under $25,000","$25,000–$49,999","$50,000–$99,999","$100,000–$149,999","$150,000–$249,999","$250,000–$499,999","$500,000–$999,999","$1,000,000+","Prefer to discuss with my consultant"),evidence:"candidate-reported liquid capital" },
  { id:"q34",section:6,kind:"multi",prompt:"What total investment ranges would you realistically consider?",options:o("Under $50,000","$50,000–$99,999","$100,000–$149,999","$150,000–$249,999","$250,000–$499,999","$500,000–$749,999","$750,000–$999,999","$1,000,000+","I need more guidance before setting an investment range"),exclusive:o("I need more guidance before setting an investment range"),evidence:"stated investment range" },
  { id:"q35",section:6,kind:"single",prompt:"How long could you comfortably support your household before the business needs to replace a meaningful portion of your current income?",options:o("Less than 3 months","3–6 months","6–12 months","12–18 months","18–24 months","More than 24 months","I'm not sure"),evidence:"household runway" },
  { id:"q36",section:6,kind:"context",prompt:"Final Discovery Context",evidence:"geography, stakeholders, and ownership stage" },
];

export const concernOptions = o("Losing financial security","Making the wrong investment","Generating enough customers","Managing employees","Replacing my income","Learning an unfamiliar business","Having enough time for family/personal life","Being personally responsible for the outcome","Following someone else's franchise system","Financing the investment","Choosing the wrong franchise","I don't have a major concern right now");
export const concernExclusive = "I don't have a major concern right now";
export const geographyOptions = o("Need to remain near my current location","Open to a broader local/regional territory","Open to serving a large territory","Open to remote/home-based ownership","Willing to relocate","Have specific requirements to discuss");
export const stakeholderOptions = o("Spouse/partner","Family","Business partner","Financial advisor/accountant","Attorney","Lender","Other trusted advisor","Decision is primarily mine");
export const ownershipStageOptions = o("Exploring whether ownership is right for me","Committed to ownership but evaluating paths","Actively researching franchises","Comparing specific opportunities","Prepared to move forward when I find the right one","Already working on financial/funding preparation");
