"use client";
import {useState} from "react";
import Link from "next/link";
import type {CalendarWorkspaceState} from "../models/CalendarWorkspaceState";
export function CalendarGrid({state}:{state:CalendarWorkspaceState}){
 const[mode,setMode]=useState<"week"|"month">("week"),[offset,setOffset]=useState(0),[day,setDay]=useState(state.todayKey);
 const anchor=new Date(state.todayKey+"T12:00:00Z");
 if(mode==="week")anchor.setUTCDate(anchor.getUTCDate()+offset*7-anchor.getUTCDay());else{anchor.setUTCDate(1);anchor.setUTCMonth(anchor.getUTCMonth()+offset);anchor.setUTCDate(anchor.getUTCDate()-anchor.getUTCDay());}
 const days=Array.from({length:mode==="week"?7:42},(_,i)=>{const d=new Date(anchor);d.setUTCDate(d.getUTCDate()+i);return d});
 const events=state.events.filter(e=>e.dateKey===day&&e.status!=="cancelled");
 return <section aria-label="Calendar grid" className="rounded-2xl border bg-white p-3 sm:p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2">{(["week","month"]as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>{setMode(m);setOffset(0)}} className={`rounded-lg px-4 py-2 font-bold capitalize ${mode===m?"bg-slate-900 text-white":"bg-slate-100"}`}>{m}</button>)}</div><div className="flex items-center gap-3"><button aria-label="Previous period" onClick={()=>setOffset(o=>o-1)} className="p-3">←</button><button onClick={()=>{setOffset(0);setDay(state.todayKey)}} className="font-bold">Today</button><button aria-label="Next period" onClick={()=>setOffset(o=>o+1)} className="p-3">→</button></div></div><p className="my-3 font-bold">{days[mode==="month"?15:0].toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"})}</p><div className="grid grid-cols-7 gap-1 sm:gap-2">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><span key={d} className="text-center text-[10px] font-bold text-slate-500">{d}</span>)}{days.map(d=>{const key=d.toISOString().slice(0,10),items=state.events.filter(e=>e.dateKey===key&&e.status!=="cancelled");return <div key={key} className={`min-w-0 rounded-lg border ${key===day?"border-teal-500 bg-teal-50":"bg-slate-50"}`}><button aria-label={`Show meetings for ${key}`} aria-pressed={key===day} onClick={()=>setDay(key)} className="min-h-11 w-full p-1 text-sm font-bold"><time dateTime={key}>{d.getUTCDate()}</time>{items.length>0&&<span className="mx-auto mt-1 block h-1 w-1 rounded-full bg-teal-700"/>}</button><div className="hidden sm:block">{items.map(e=><Link key={e.id} href={`/crm/calendar?event=${e.id}`} className="m-1 block break-words rounded bg-white p-2 text-xs text-blue-800"><strong>{e.timeLabel}</strong><span className="mt-1 block">{e.title}</span></Link>)}</div></div>})}</div><div className="mt-4 space-y-2 border-t pt-4"><h3 className="font-bold">{new Date(day+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric',timeZone:'UTC'})}</h3><p className="text-xs text-slate-500">{state.timezone} · No external calendar sync</p>{events.map(e=><Link key={e.id} href={`/crm/calendar?event=${e.id}`} className="block rounded-xl bg-slate-50 p-3 text-sm"><strong className="text-blue-700">{e.timeLabel} · {e.title}</strong><span className="mt-1 block">{e.candidateName}</span></Link>)}{!events.length&&<p className="text-sm text-slate-500">No meetings scheduled for this day.</p>}</div></section>;
}
